# Cryptocurrency Price Prediction

In [1]:
%pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.65)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.3.8)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (3.18.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.5)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2025.8.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [2]:
import pandas as pd
import numpy as np
import yfinance as yf
import datetime
from datetime import date,timedelta

In [3]:
today = date.today()
d1 = today.strftime('%Y-%m-%d')
end_date = d1
d2 = date.today() - timedelta(days=768)
d2 = d2.strftime('%Y-%m-%d')
start_date = d2

In [4]:
data = yf.download('BTC-USD',start=start_date,end=end_date,progress=False)
data.columns = [col[0] if isinstance(col, tuple) else col for col in data.columns]
data = data.reset_index()
data["Date"] = pd.to_datetime(data['Date'])
data = data[['Date','Open','High','Low','Close','Volume']]
# data.reset_index(drop=True,inplace=True)

/tmp/ipython-input-2624692765.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download('BTC-USD',start=start_date,end=end_date,progress=False)

In [5]:
data.head()

,Date,Open,High,Low,Close,Volume
0,2023-07-23,29790.111328,30330.640625,29741.527344,30084.539062,9220145050
1,2023-07-24,30081.662109,30093.394531,28934.294922,29176.916016,15395817395
2,2023-07-25,29178.970703,29353.160156,29062.433594,29227.390625,10266772793
3,2023-07-26,29225.759766,29675.552734,29113.912109,29354.972656,13497554655
4,2023-07-27,29353.798828,29560.966797,29099.351562,29210.689453,10770779217

In [6]:
data.tail()

,Date,Open,High,Low,Close,Volume
763,2025-08-24,115387.390625,115615.085938,111060.546875,113458.429688,73961489632
764,2025-08-25,113456.898438,113637.843750,109324.281250,110124.351562,85706860190
765,2025-08-26,110124.101562,112397.015625,108762.039062,111802.656250,69396320317
766,2025-08-27,111795.710938,112619.414062,110398.265625,111222.062500,62137056409
767,2025-08-28,111219.054688,113450.078125,110900.921875,112544.804688,58860155962

In [7]:
data.shape

(768, 6)

In [8]:
import plotly.graph_objects as go

In [9]:
figure = go.Figure(data=[go.Candlestick(
    x=data['Date'],
    open=data['Open'],
    high=data['High'],
    low=data['Low'],
    close=data['Close']
)])
figure.update_layout(title='Bitcoin Price Analysis',
                     xaxis_rangeslider_visible=False)
figure.show()

In [11]:
correlation = data.corr()
correlation["Close"].sort_values(ascending=False)

Close     1.000000
High      0.999156
Low       0.998852
Open      0.997876
Date      0.949120
Volume    0.654984
Name: Close, dtype: float64

In [12]:
%pip install autots

Collecting autots
  Downloading autots-0.6.21-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.12/dist-packages (from autots) (2.0.2)
Requirement already satisfied: pandas>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from autots) (2.2.2)
Requirement already satisfied: statsmodels>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from autots) (0.14.5)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from autots) (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.0->autots) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.0->autots) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.0->autots) (2025.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.0->autots) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.0->autots) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.0->autots) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.10.0->autots) (1.0.1)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.10.0->autots) (25.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.0->autots) (1.17.0)
Downloading autots-0.6.21-py3-none-any.whl (974 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 974.9/974.9 kB 41.0 MB/s eta 0:00:00
Installing collected packages: autots
Successfully installed autots-0.6.21

In [13]:
from autots import AutoTS
model = AutoTS(forecast_length = 30,frequency = 'infer',ensemble='simple')
model = model.fit(data,date_col='Date',value_col = 'Close',id_col = None)
prediction = model.predict()
forecast = prediction.forecast
print(forecast)

Using 1 cpus for n_jobs.
Data frequency is: D, used frequency is: D
Model Number: 1 with model AverageValueNaive in generation 0 of 25
Model Number: 2 with model AverageValueNaive in generation 0 of 25
Model Number: 3 with model AverageValueNaive in generation 0 of 25
Model Number: 4 with model DatepartRegression in generation 0 of 25
Model Number: 5 with model DatepartRegression in generation 0 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning:

Liblinear failed to converge, increase the number of iterations.

Model Number: 6 with model DatepartRegression in generation 0 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

Model Number: 7 with model DatepartRegression in generation 0 of 25

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 15s 18ms/step - loss: 0.4267
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.4167
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.4108
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.4048
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.4030
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.4007
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.3995
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.3969
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.3970
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3954
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.3938
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.3939
Epoch 13/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.3877
Epoch 14/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3909
Epoch 15/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.3928
Epoch 16/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.3916
Epoch 17/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3906
Epoch 18/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.3908
Epoch 19/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.3886
Epoch 20/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3902
Epoch 21/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.3859
Epoch 22/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.3857
Epoch 23/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3870
Epoch 24/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.3854
Epoch 25/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.3859
Epoch 26/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.3873
Epoch 27/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.3862
Epoch 28/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.3840
Epoch 29/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.3817
Epoch 30/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.3859
Epoch 31/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3815
Epoch 32/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.3798
Epoch 33/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3798
Epoch 34/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.3819
Epoch 35/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3831
Epoch 36/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3840
Epoch 37/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3835
Epoch 38/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3740
Epoch 39/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3808
Epoch 40/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3761
Epoch 41/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3756
Epoch 42/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3748
Epoch 43/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3724
Epoch 44/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3714
Epoch 45/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3691
Epoch 46/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3677
Epoch 47/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3601
Epoch 48/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3587
Epoch 49/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.3626
Epoch 50/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.3587
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 732ms/step
Model Number: 8 with model ETS in generation 0 of 25
Model Number: 9 with model ETS in generation 0 of 25
Model Number: 10 with model GLM in generation 0 of 25
Model Number: 11 with model GLM in generation 0 of 25
Model Number: 12 with model GLS in generation 0 of 25
Model Number: 13 with model GLS in generation 0 of 25
Model Number: 14 with model LastValueNaive in generation 0 of 25
Model Number: 15 with model LastValueNaive in generation 0 of 25
Model Number: 16 with model LastValueNaive in generation 0 of 25
Model Number: 17 with model LastValueNaive in generation 0 of 25
Model Number: 18 with model SeasonalNaive in generation 0 of 25
Model Number: 19 with model SeasonalNaive in generation 0 of 25
Model Number: 20 with model SeasonalNaive in generation 0 of 25
Model Number: 21 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 21 in generation 0: VAR
Model Number: 22 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 22 in generation 0: VAR
Model Number: 23 with model WindowRegression in generation 0 of 25
Model Number: 24 with model ConstantNaive in generation 0 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

Model Number: 25 with model FBProphet in generation 0 of 25

DEBUG:cmdstanpy:input tempfile: /tmp/tmpuqj7uuqs/ctbwfwqx.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpuqj7uuqs/aeqa0nfj.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.12/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56099', 'data', 'file=/tmp/tmpuqj7uuqs/ctbwfwqx.json', 'init=/tmp/tmpuqj7uuqs/aeqa0nfj.json', 'output', 'file=/tmp/tmpuqj7uuqs/prophet_modela0rsaq_y/prophet_model-20250829092826.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
09:28:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
09:28:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Model Number: 26 with model DatepartRegression in generation 0 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 26 in generation 0: DatepartRegression
Model Number: 27 with model SeasonalNaive in generation 0 of 25
Model Number: 28 with model DatepartRegression in generation 0 of 25
Model Number: 29 with model ETS in generation 0 of 25
Model Number: 30 with model ARDL in generation 0 of 25
Model Number: 31 with model UnivariateMotif in generation 0 of 25
Model Number: 32 with model UnivariateMotif in generation 0 of 25
Model Number: 33 with model SectionalMotif in generation 0 of 25
Model Number: 34 with model SectionalMotif in generation 0 of 25
Model Number: 35 with model FBProphet in generation 0 of 25
Model Number: 36 with model SeasonalNaive in generation 0 of 25
Model Number: 37 with model DatepartRegression in generation 0 of 25
Model Number: 38 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 38 in generation 0: ARCH
Model Number: 39 with model Cassandra in generation 0 of 25
Model Number: 40 with model SeasonalityMotif in generation 0 of 25
Model Number: 41 with model Cassandra in generation 0 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 42 with model Cassandra in generation 0 of 25
Model Number: 43 with model Cassandra in generation 0 of 25
Model Number: 44 with model SectionalMotif in generation 0 of 25
Model Number: 45 with model FBProphet in generation 0 of 25

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 46 with model ARDL in generation 0 of 25

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 47 with model FFT in generation 0 of 25
Model Number: 48 with model BasicLinearModel in generation 0 of 25
Template Eval Error: ValueError('matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 738 is different from 2003)') in model 48 in generation 0: BasicLinearModel
Model Number: 49 with model BasicLinearModel in generation 0 of 25
Model Number: 50 with model SeasonalityMotif in generation 0 of 25
Model Number: 51 with model BasicLinearModel in generation 0 of 25
Model Number: 52 with model FBProphet in generation 0 of 25
Model Number: 53 with model ETS in generation 0 of 25
Model Number: 54 with model FBProphet in generation 0 of 25
Model Number: 55 with model GLM in generation 0 of 25
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 55 in generation 0: GLM
Model Number: 56 with model UnivariateMotif in generation 0 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:527: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:445: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:445: RuntimeWarning:

overflow encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:1328: RuntimeWarning:

invalid value encountered in multiply

Model Number: 57 with model ARDL in generation 0 of 25
Model Number: 58 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 58 in generation 0: ARCH
Model Number: 59 with model ConstantNaive in generation 0 of 25
Model Number: 60 with model LastValueNaive in generation 0 of 25
Model Number: 61 with model AverageValueNaive in generation 0 of 25
Model Number: 62 with model GLS in generation 0 of 25
Model Number: 63 with model SeasonalNaive in generation 0 of 25
Model Number: 64 with model VAR in generation 0 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 65 with model WindowRegression in generation 0 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 65 in generation 0: WindowRegression
Model Number: 66 with model DatepartRegression in generation 0 of 25
Model Number: 67 with model SectionalMotif in generation 0 of 25
Model Number: 68 with model RRVAR in generation 0 of 25
Model Number: 69 with model MetricMotif in generation 0 of 25
Template Eval Error: ValueError('Shape of passed values is (30, 2), indices imply (30, 1)') in model 69 in generation 0: MetricMotif
Model Number: 70 with model Cassandra in generation 0 of 25
Model Number: 71 with model SeasonalityMotif in generation 0 of 25
Model Number: 72 with model FFT in generation 0 of 25
Model Number: 73 with model BasicLinearModel in generation 0 of 25
Model Number: 74 with model AverageValueNaive in generation 0 of 25
Model Number: 75 with model ConstantNaive in generation 0 of 25
Model Number: 76 with model LastValueNaive in generation 0 of 25
Model Number: 77 with model DatepartRegression in generation 0 of 25
Model Number: 78 with model SeasonalNaive in generation 0 of 25
Model Number: 79 with model MetricMotif in generation 0 of 25
Model Number: 80 with model ETS in generation 0 of 25
2025-07-30 00:00:00
2025-07-30 00:00:00
2025-07-30 00:00:00
Model Number: 81 with model LastValueNaive in generation 0 of 25
Model Number: 82 with model LastValueNaive in generation 0 of 25
Model Number: 83 with model SectionalMotif in generation 0 of 25
Model Number: 84 with model UnivariateMotif in generation 0 of 25
Model Number: 85 with model UnivariateMotif in generation 0 of 25
Model Number: 86 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 86 in generation 0: ARCH
Model Number: 87 with model ETS in generation 0 of 25
Model Number: 88 with model LastValueNaive in generation 0 of 25
Model Number: 89 with model ETS in generation 0 of 25
Model Number: 90 with model SeasonalNaive in generation 0 of 25
Model Number: 91 with model SeasonalityMotif in generation 0 of 25
Model Number: 92 with model FFT in generation 0 of 25
Model Number: 93 with model RRVAR in generation 0 of 25
Model Number: 94 with model GLM in generation 0 of 25
Template Eval Error: ValueError('regression_type=user and no future_regressor passed') in model 94 in generation 0: GLM
Model Number: 95 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 95 in generation 0: VAR
Model Number: 96 with model SeasonalNaive in generation 0 of 25
Model Number: 97 with model ARDL in generation 0 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 97 in generation 0: ARDL
Model Number: 98 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 98 in generation 0: ARCH
Model Number: 99 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 99 in generation 0: ARCH
Model Number: 100 with model GLM in generation 0 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 101 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 101 in generation 0: VAR
Model Number: 102 with model FBProphet in generation 0 of 25
Model Number: 103 with model LastValueNaive in generation 0 of 25
Model Number: 104 with model RRVAR in generation 0 of 25
Model Number: 105 with model AverageValueNaive in generation 0 of 25
2025-07-30 00:00:00
2025-07-30 00:00:00
2025-07-30 00:00:00
Template Eval Error: ValueError('Model AverageValueNaive returned improper forecast_length. Returned: 28 and requested: 30') in model 105 in generation 0: AverageValueNaive
Model Number: 106 with model SeasonalityMotif in generation 0 of 25
Model Number: 107 with model SectionalMotif in generation 0 of 25
Model Number: 108 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 108 in generation 0: VAR
Model Number: 109 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 109 in generation 0: ARCH
Model Number: 110 with model SeasonalityMotif in generation 0 of 25
Model Number: 111 with model FFT in generation 0 of 25
Model Number: 112 with model AverageValueNaive in generation 0 of 25
Model Number: 113 with model ConstantNaive in generation 0 of 25
Model Number: 114 with model ETS in generation 0 of 25
Model Number: 115 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 115 in generation 0: ARCH
Model Number: 116 with model AverageValueNaive in generation 0 of 25
Model Number: 117 with model AverageValueNaive in generation 0 of 25
Model Number: 118 with model LastValueNaive in generation 0 of 25
Model Number: 119 with model FBProphet in generation 0 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 120 with model ConstantNaive in generation 0 of 25
Model Number: 121 with model SeasonalityMotif in generation 0 of 25
Model Number: 122 with model ETS in generation 0 of 25
Model Number: 123 with model UnivariateMotif in generation 0 of 25
Model Number: 124 with model UnivariateMotif in generation 0 of 25
Model Number: 125 with model ARDL in generation 0 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 125 in generation 0: ARDL
Model Number: 126 with model GLM in generation 0 of 25
Template Eval Error: ValueError('regression_type=user and no future_regressor passed') in model 126 in generation 0: GLM
Model Number: 127 with model VAR in generation 0 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 127 in generation 0: VAR
Model Number: 128 with model RRVAR in generation 0 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 129 with model MetricMotif in generation 0 of 25
Model Number: 130 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 130 in generation 0: ARCH
Model Number: 131 with model ARCH in generation 0 of 25
Template Eval Error: ImportError('`arch` package must be installed from pip') in model 131 in generation 0: ARCH
Model Number: 132 with model SeasonalityMotif in generation 0 of 25
Model Number: 133 with model LastValueNaive in generation 0 of 25
Model Number: 134 with model SectionalMotif in generation 0 of 25
Model Number: 135 with model LastValueNaive in generation 0 of 25
Model Number: 136 with model AverageValueNaive in generation 0 of 25
Model Number: 137 with model LastValueNaive in generation 0 of 25
Model Number: 138 with model ARDL in generation 0 of 25
Model Number: 139 with model SeasonalityMotif in generation 0 of 25
Model Number: 140 with model ConstantNaive in generation 0 of 25
Model Number: 141 with model SectionalMotif in generation 0 of 25
Model Number: 142 with model SeasonalityMotif in generation 0 of 25
Model Number: 143 with model SectionalMotif in generation 0 of 25
Model Number: 144 with model SeasonalityMotif in generation 0 of 25
Model Number: 145 with model MetricMotif in generation 0 of 25
Model Number: 146 with model SeasonalNaive in generation 0 of 25
Model Number: 147 with model ARDL in generation 0 of 25
Model Number: 148 with model AverageValueNaive in generation 0 of 25
Model Number: 149 with model ARDL in generation 0 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 149 in generation 0: ARDL
Model Number: 150 with model SeasonalityMotif in generation 0 of 25
Model Number: 151 with model MetricMotif in generation 0 of 25
Model Number: 152 with model SeasonalityMotif in generation 0 of 25
Model Number: 153 with model FBProphet in generation 0 of 25
No anomalies detected.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 154 with model SectionalMotif in generation 0 of 25

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 155 with model SeasonalNaive in generation 0 of 25
Template Eval Error: Exception("Transformer FIRFilter failed on fit from params mean {'0': {'method': 'IQR', 'method_params': {'iqr_threshold': 2.0, 'iqr_quantiles': [0.25, 0.75]}, 'fillna': 'rolling_mean_24', 'transform_dict': None, 'isolated_only': False, 'on_inverse': False}, '1': {'numtaps': 7, 'cutoff_hz': 50, 'window': 'hamming', 'sampling_frequency': 72, 'on_transform': True, 'on_inverse': False, 'bounds_only': False}, '2': {'fixed': True, 'window': 3, 'macro_micro': False, 'center': False}, '3': {'method': 'minmax', 'method_params': {'alpha': 0.05}, 'transform_dict': None, 'reverse_alignment': False, 'isolated_only': False, 'fillna': 'time'}, '4': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 3, 'threshold_method': 'max'}} with error ValueError('Invalid cutoff frequency: frequencies must be greater than 0 and less than fs/2.')") in model 155 in generation 0: SeasonalNaive
Model Number: 156 with model ETS in generation 0 of 25
Model Number: 157 with model SeasonalityMotif in generation 0 of 25
New Generation: 1 of 25
Model Number: 158 with model FFT in generation 1 of 25
Model Number: 159 with model SeasonalityMotif in generation 1 of 25
Model Number: 160 with model SectionalMotif in generation 1 of 25
Model Number: 161 with model SeasonalityMotif in generation 1 of 25
Model Number: 162 with model SeasonalityMotif in generation 1 of 25
Model Number: 163 with model SeasonalNaive in generation 1 of 25
Model Number: 164 with model LastValueNaive in generation 1 of 25
Model Number: 165 with model VAR in generation 1 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 165 in generation 1: VAR
Model Number: 166 with model ETS in generation 1 of 25
Model Number: 167 with model GLM in generation 1 of 25
Model Number: 168 with model AverageValueNaive in generation 1 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 169 with model FBProphet in generation 1 of 25
Model Number: 170 with model SeasonalNaive in generation 1 of 25
Model Number: 171 with model FBProphet in generation 1 of 25
Model Number: 172 with model SectionalMotif in generation 1 of 25
Model Number: 173 with model FFT in generation 1 of 25
Model Number: 174 with model LastValueNaive in generation 1 of 25
Model Number: 175 with model ConstantNaive in generation 1 of 25
Model Number: 176 with model WindowRegression in generation 1 of 25
Model Number: 177 with model AverageValueNaive in generation 1 of 25
Model Number: 178 with model SeasonalityMotif in generation 1 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

Model Number: 179 with model SectionalMotif in generation 1 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params ffill {'0': {'rows': 4, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': True, 'threshold': 1, 'threshold_method': 'mean'}, '1': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 2}} with error ValueError('BTCD only works on multivarate series')") in model 179 in generation 1: SectionalMotif
Model Number: 180 with model ConstantNaive in generation 1 of 25
SVD did not converge, attempting more robust approach...
Template Eval Error: Exception("Transformer KalmanSmoothing failed on fit from params quadratic {'0': {'model_name': 'locallinear_weekly_fourier', 'state_transition': [[1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9998520419557735, 0.017201575418260506, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.017201575418260506, 0.9998520419557735, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9994082116062598, 0.03439806061360801, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.03439806061360801, 0.9994082116062598, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9986686402879997, 0.051584366869408364, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.051584366869408364, 0.9986686402879997, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9976335468520451, 0.06875540848113941, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.06875540848113941, 0.9976335468520451, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9963032375991965, 0.08590610426133272, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.08590610426133272, 0.9963032375991965, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9946781061893646, 0.10303137904317879, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.10303137904317879, 0.9946781061893646, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]], 'process_noise': [[0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01]], 'observation_model': [[1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9998520419557735, 0.017201575418260506, 0.9994082116062598, 0.03439806061360801, 0.9986686402879997, 0.051584366869408364, 0.9976335468520451, 0.06875540848113941, 0.9963032375991965, 0.08590610426133272, 0.9946781061893646, 0.10303137904317879]], 'observation_noise': 0.01, 'em_iter': 10, 'on_transform': True, 'on_inverse': False}, '1': {}} with error LinAlgError('SVD did not converge')") in model 180 in generation 1: ConstantNaive
Model Number: 181 with model SectionalMotif in generation 1 of 25
Model Number: 182 with model GLS in generation 1 of 25
Model Number: 183 with model LastValueNaive in generation 1 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/fast_kalman.py:1142: RuntimeWarning:

overflow encountered in cast

/usr/local/lib/python3.12/dist-packages/autots/tools/fast_kalman.py:1359: RuntimeWarning:

invalid value encountered in matmul

/usr/local/lib/python3.12/dist-packages/autots/tools/fast_kalman.py:1346: RuntimeWarning:

invalid value encountered in matmul

Model Number: 184 with model LastValueNaive in generation 1 of 25
Model Number: 185 with model RRVAR in generation 1 of 25
Model Number: 186 with model GLM in generation 1 of 25
Model Number: 187 with model MetricMotif in generation 1 of 25
Model Number: 188 with model MetricMotif in generation 1 of 25
Model Number: 189 with model SectionalMotif in generation 1 of 25
Model Number: 190 with model AverageValueNaive in generation 1 of 25
Model Number: 191 with model LastValueNaive in generation 1 of 25
Model Number: 192 with model SeasonalityMotif in generation 1 of 25
Model Number: 193 with model UnivariateMotif in generation 1 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.44489e-25): result may not be accurate.

Model Number: 194 with model DatepartRegression in generation 1 of 25
Model Number: 195 with model DatepartRegression in generation 1 of 25
Model Number: 196 with model MetricMotif in generation 1 of 25
Model Number: 197 with model VAR in generation 1 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 197 in generation 1: VAR
Model Number: 198 with model ARDL in generation 1 of 25
Model Number: 199 with model LastValueNaive in generation 1 of 25
Model Number: 200 with model ARDL in generation 1 of 25
Model Number: 201 with model ARDL in generation 1 of 25
Model Number: 202 with model SeasonalityMotif in generation 1 of 25
Model Number: 203 with model LastValueNaive in generation 1 of 25
Model Number: 204 with model AverageValueNaive in generation 1 of 25
Model Number: 205 with model LastValueNaive in generation 1 of 25
Model Number: 206 with model DatepartRegression in generation 1 of 25
Model Number: 207 with model DatepartRegression in generation 1 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 208 with model ConstantNaive in generation 1 of 25
Model Number: 209 with model MetricMotif in generation 1 of 25
Model Number: 210 with model ETS in generation 1 of 25
Model Number: 211 with model FBProphet in generation 1 of 25
No anomalies detected.

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 212 with model LastValueNaive in generation 1 of 25
Model Number: 213 with model AverageValueNaive in generation 1 of 25

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 214 with model SeasonalNaive in generation 1 of 25
Model Number: 215 with model DatepartRegression in generation 1 of 25
Model Number: 216 with model BasicLinearModel in generation 1 of 25
Model Number: 217 with model SeasonalNaive in generation 1 of 25
Model Number: 218 with model UnivariateMotif in generation 1 of 25
Model Number: 219 with model SeasonalityMotif in generation 1 of 25
Model Number: 220 with model SectionalMotif in generation 1 of 25
Model Number: 221 with model BasicLinearModel in generation 1 of 25
Model Number: 222 with model SeasonalityMotif in generation 1 of 25
Template Eval Error: ValueError('Model SeasonalityMotif returned NaN for one or more series. fail_on_forecast_nan=True') in model 222 in generation 1: SeasonalityMotif
Model Number: 223 with model ARDL in generation 1 of 25
Model Number: 224 with model Cassandra in generation 1 of 25

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning:

Mean of empty slice.

/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:130: RuntimeWarning:

invalid value encountered in divide

Model Number: 225 with model BasicLinearModel in generation 1 of 25
Model Number: 226 with model AverageValueNaive in generation 1 of 25
Model Number: 227 with model Cassandra in generation 1 of 25
Model Number: 228 with model ConstantNaive in generation 1 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 229 with model ETS in generation 1 of 25
Model Number: 230 with model SeasonalityMotif in generation 1 of 25
Model Number: 231 with model ConstantNaive in generation 1 of 25
Model Number: 232 with model SeasonalNaive in generation 1 of 25
Model Number: 233 with model SeasonalityMotif in generation 1 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 234 with model Cassandra in generation 1 of 25
Model Number: 235 with model UnivariateMotif in generation 1 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 236 with model Cassandra in generation 1 of 25
Model Number: 237 with model SectionalMotif in generation 1 of 25
Model Number: 238 with model LastValueNaive in generation 1 of 25
Model Number: 239 with model FBProphet in generation 1 of 25
Model Number: 240 with model ETS in generation 1 of 25
Model Number: 241 with model ARDL in generation 1 of 25
Model Number: 242 with model GLM in generation 1 of 25
Model Number: 243 with model ConstantNaive in generation 1 of 25
Model Number: 244 with model ETS in generation 1 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 245 with model FBProphet in generation 1 of 25
Model Number: 246 with model LastValueNaive in generation 1 of 25
Model Number: 247 with model AverageValueNaive in generation 1 of 25
Model Number: 248 with model UnivariateMotif in generation 1 of 25
Model Number: 249 with model DatepartRegression in generation 1 of 25
Model Number: 250 with model LastValueNaive in generation 1 of 25
Model Number: 251 with model ETS in generation 1 of 25
Model Number: 252 with model SeasonalityMotif in generation 1 of 25
Model Number: 253 with model SeasonalNaive in generation 1 of 25
Model Number: 254 with model SeasonalNaive in generation 1 of 25
Model Number: 255 with model SeasonalNaive in generation 1 of 25
Model Number: 256 with model MetricMotif in generation 1 of 25
Model Number: 257 with model SeasonalNaive in generation 1 of 25
Model Number: 258 with model SectionalMotif in generation 1 of 25
Model Number: 259 with model ARDL in generation 1 of 25
Model Number: 260 with model AverageValueNaive in generation 1 of 25
Model Number: 261 with model UnivariateMotif in generation 1 of 25
Model Number: 262 with model LastValueNaive in generation 1 of 25
New Generation: 2 of 25
Model Number: 263 with model Cassandra in generation 2 of 25
Model Number: 264 with model FFT in generation 2 of 25
Model Number: 265 with model ETS in generation 2 of 25
Model Number: 266 with model ConstantNaive in generation 2 of 25
Model Number: 267 with model BasicLinearModel in generation 2 of 25
Model Number: 268 with model GLM in generation 2 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:308: DomainWarning:

The InversePower link function does not respect the domain of the Gamma family.

Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 268 in generation 2: GLM
Model Number: 269 with model UnivariateMotif in generation 2 of 25
Model Number: 270 with model LastValueNaive in generation 2 of 25
Model Number: 271 with model SeasonalityMotif in generation 2 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

overflow encountered in square

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:325: RuntimeWarning:

divide by zero encountered in power

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:775: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:1328: RuntimeWarning:

invalid value encountered in multiply

Model Number: 272 with model SeasonalityMotif in generation 2 of 25
Template Eval Error: Exception("Transformer Detrend failed on fit from params fake_date {'0': {'n_harmonics': 20, 'detrend': 'quadratic'}, '1': {'model': 'Tweedie', 'phi': 0.999, 'window': 30, 'transform_dict': {'fillna': None, 'transformations': {'0': 'EWMAFilter'}, 'transformation_params': {'0': {'span': 2}}}}, '2': {'method': 'zscore', 'method_params': {'distribution': 'uniform', 'alpha': 0.05}, 'fillna': None, 'transform_dict': {'fillna': 'pchip', 'transformations': {'0': 'AlignLastValue'}, 'transformation_params': {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': None, 'threshold_method': 'mean'}}}, 'isolated_only': False, 'on_inverse': False}, '3': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': True, 'threshold': 10, 'threshold_method': 'mean'}, '4': {'decimals': 0, 'on_transform': True, 'on_inverse': True}} with error ValueError('Found input variables with inconsistent numbers of samples: [30, 738]')") in model 272 in generation 2: SeasonalityMotif
Model Number: 273 with model BasicLinearModel in generation 2 of 25
Model Number: 274 with model AverageValueNaive in generation 2 of 25
Model Number: 275 with model SeasonalNaive in generation 2 of 25
Model Number: 276 with model UnivariateMotif in generation 2 of 25
Model Number: 277 with model MetricMotif in generation 2 of 25
Model Number: 278 with model AverageValueNaive in generation 2 of 25
Model Number: 279 with model RRVAR in generation 2 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 280 with model ARDL in generation 2 of 25
Model Number: 281 with model LastValueNaive in generation 2 of 25
Model Number: 282 with model FBProphet in generation 2 of 25
Model Number: 283 with model ARDL in generation 2 of 25
Model Number: 284 with model MetricMotif in generation 2 of 25
Model Number: 285 with model LastValueNaive in generation 2 of 25
Model Number: 286 with model Cassandra in generation 2 of 25
Model Number: 287 with model FFT in generation 2 of 25
Model Number: 288 with model FFT in generation 2 of 25
Model Number: 289 with model Cassandra in generation 2 of 25
Model Number: 290 with model ARDL in generation 2 of 25
Model Number: 291 with model SeasonalNaive in generation 2 of 25
Model Number: 292 with model ETS in generation 2 of 25
Model Number: 293 with model LastValueNaive in generation 2 of 25
Model Number: 294 with model Cassandra in generation 2 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params None {'0': {}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {}, '3': {'constant': 1, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gbtree', 'max_depth': 3, 'eta': 0.03, 'min_child_weight': 1, 'subsample': 0.7, 'colsample_bylevel': 1, 'reg_alpha': 0, 'reg_lambda': 1}, 'datepart_method': ['weekdayofmonth', 'common_fourier']}, 'fillna': 'ffill'}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 294 in generation 2: Cassandra
Model Number: 295 with model RRVAR in generation 2 of 25
Template Eval Error: ValueError('operands could not be broadcast together with shapes (150,1) (30,1) ') in model 295 in generation 2: RRVAR
Model Number: 296 with model SeasonalityMotif in generation 2 of 25
Model Number: 297 with model SeasonalNaive in generation 2 of 25
Model Number: 298 with model SeasonalNaive in generation 2 of 25
Model Number: 299 with model ConstantNaive in generation 2 of 25
Model Number: 300 with model DatepartRegression in generation 2 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 300 in generation 2: DatepartRegression
Model Number: 301 with model ETS in generation 2 of 25
Model Number: 302 with model UnivariateMotif in generation 2 of 25
Model Number: 303 with model UnivariateMotif in generation 2 of 25
Model Number: 304 with model MetricMotif in generation 2 of 25
Model Number: 305 with model ETS in generation 2 of 25
Model Number: 306 with model DatepartRegression in generation 2 of 25
Model Number: 307 with model DatepartRegression in generation 2 of 25
Model Number: 308 with model ARDL in generation 2 of 25
Model Number: 309 with model FBProphet in generation 2 of 25
Model Number: 310 with model AverageValueNaive in generation 2 of 25
Model Number: 311 with model DatepartRegression in generation 2 of 25
interpolating
Template Eval Error: ValueError('Model DatepartRegression returned NaN for one or more series. fail_on_forecast_nan=True') in model 311 in generation 2: DatepartRegression
Model Number: 312 with model ARDL in generation 2 of 25
Template Eval Error: Exception("Transformer DatepartRegression failed on fit from params nearest {'0': {'output_distribution': 'uniform', 'n_quantiles': 246}, '1': {'regression_model': {'model': 'ElasticNet', 'model_params': {'l1_ratio': 0.9, 'fit_intercept': True, 'selection': 'cyclic', 'max_iter': 1000}}, 'datepart_method': 'simple_binarized', 'polynomial_degree': None, 'transform_dict': {'fillna': None, 'transformations': {'0': 'ScipyFilter'}, 'transformation_params': {'0': {'method': 'savgol_filter', 'method_args': {'window_length': 31, 'polyorder': 3, 'deriv': 0, 'mode': 'interp'}}}}, 'holiday_countries_used': True, 'lags': None, 'forward_lags': 2}, '2': {}, '3': {'model': 'Poisson', 'phi': 1, 'window': None, 'transform_dict': None}} with error ValueError('Found input variables with inconsistent numbers of samples: [2003, 738]')") in model 312 in generation 2: ARDL
Model Number: 313 with model FFT in generation 2 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_regression.py:508: UserWarning:

One or more samples have no neighbors within specified radius; predicting NaN.

Model Number: 314 with model ETS in generation 2 of 25
Model Number: 315 with model SectionalMotif in generation 2 of 25
Model Number: 316 with model LastValueNaive in generation 2 of 25
Model Number: 317 with model SectionalMotif in generation 2 of 25
Model Number: 318 with model AverageValueNaive in generation 2 of 25
Model Number: 319 with model UnivariateMotif in generation 2 of 25
Model Number: 320 with model Cassandra in generation 2 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 321 with model FBProphet in generation 2 of 25
Model Number: 322 with model ETS in generation 2 of 25
Model Number: 323 with model BasicLinearModel in generation 2 of 25
Model Number: 324 with model SeasonalNaive in generation 2 of 25
Model Number: 325 with model AverageValueNaive in generation 2 of 25
Model Number: 326 with model ETS in generation 2 of 25
Model Number: 327 with model SeasonalityMotif in generation 2 of 25
Model Number: 328 with model UnivariateMotif in generation 2 of 25
Model Number: 329 with model BasicLinearModel in generation 2 of 25
Model Number: 330 with model GLS in generation 2 of 25
Model Number: 331 with model GLS in generation 2 of 25
Model Number: 332 with model BasicLinearModel in generation 2 of 25
Model Number: 333 with model ARDL in generation 2 of 25
Model Number: 334 with model SectionalMotif in generation 2 of 25
Model Number: 335 with model DatepartRegression in generation 2 of 25
Model Number: 336 with model FFT in generation 2 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params zero {'0': {'det_order': 0, 'k_ar_diff': 1}, '1': {'window_size': 70, 'alpha': 2.5, 'grouping_forward_limit': 5, 'max_level_shifts': 30, 'alignment': 'average'}, '2': {}, '3': {'output_distribution': 'uniform', 'n_quantiles': 1000}} with error ValueError('Coint only works on multivarate series')") in model 336 in generation 2: FFT
Model Number: 337 with model RRVAR in generation 2 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params ffill {'0': {'rows': 4, 'lag': 1, 'method': 'additive', 'strength': 0.5, 'first_value_only': True, 'threshold': None, 'threshold_method': 'max'}, '1': {}, '2': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'n_estimators': 7, 'max_leaves': 4, 'min_child_weight': 2.5, 'learning_rate': 0.35, 'subsample': 0.95, 'colsample_bylevel': 0.56, 'colsample_bytree': 0.46, 'reg_alpha': 0.0016, 'reg_lambda': 5.3}, 'datepart_method': 'recurring'}, 'fillna': None}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 337 in generation 2: RRVAR
Model Number: 338 with model ARDL in generation 2 of 25
Model Number: 339 with model Cassandra in generation 2 of 25
Model Number: 340 with model MetricMotif in generation 2 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 341 with model AverageValueNaive in generation 2 of 25
Model Number: 342 with model SeasonalNaive in generation 2 of 25
Model Number: 343 with model SeasonalityMotif in generation 2 of 25
Model Number: 344 with model FBProphet in generation 2 of 25
Model Number: 345 with model MetricMotif in generation 2 of 25
Model Number: 346 with model GLM in generation 2 of 25
Model Number: 347 with model MetricMotif in generation 2 of 25
Model Number: 348 with model FFT in generation 2 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 349 with model VAR in generation 2 of 25
Template Eval Error: IndexError('tuple index out of range') in model 349 in generation 2: VAR
Model Number: 350 with model AverageValueNaive in generation 2 of 25
Model Number: 351 with model MetricMotif in generation 2 of 25
Model Number: 352 with model MetricMotif in generation 2 of 25
Model Number: 353 with model ARDL in generation 2 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 353 in generation 2: ARDL
Model Number: 354 with model SeasonalityMotif in generation 2 of 25
Model Number: 355 with model FBProphet in generation 2 of 25
Model Number: 356 with model SeasonalNaive in generation 2 of 25
Model Number: 357 with model ConstantNaive in generation 2 of 25
Model Number: 358 with model LastValueNaive in generation 2 of 25
Model Number: 359 with model ARDL in generation 2 of 25
Model Number: 360 with model ARDL in generation 2 of 25
Model Number: 361 with model LastValueNaive in generation 2 of 25
Model Number: 362 with model SeasonalNaive in generation 2 of 25
Model Number: 363 with model SectionalMotif in generation 2 of 25
Model Number: 364 with model ETS in generation 2 of 25
Model Number: 365 with model SeasonalityMotif in generation 2 of 25
Model Number: 366 with model VAR in generation 2 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 366 in generation 2: VAR
Model Number: 367 with model WindowRegression in generation 2 of 25
Epoch 1/10

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 2043.3831
Epoch 2/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 466.2643
Epoch 3/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 270.7771
Epoch 4/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 186.6067
Epoch 5/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 108.9375
Epoch 6/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 52.0758
Epoch 7/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.1444
Epoch 8/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 11.7145
Epoch 9/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.7444
Epoch 10/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.4400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
New Generation: 3 of 25
Model Number: 368 with model RRVAR in generation 3 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params fake_date {'0': {'det_order': 1, 'k_ar_diff': 1}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {}, '3': {'part': 'trend', 'lamb': 1600}} with error ValueError('Coint only works on multivarate series')") in model 368 in generation 3: RRVAR
Model Number: 369 with model ETS in generation 3 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params nearest {'0': {'mode': 'upscale', 'factor': 3, 'down_method': 'decimate', 'fill_method': 'linear'}, '1': {'rows': 7, 'lag': 7, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': None, 'threshold_method': 'max'}, '2': {'det_order': -1, 'k_ar_diff': 1}} with error ValueError('Coint only works on multivarate series')") in model 369 in generation 3: ETS
Model Number: 370 with model SeasonalityMotif in generation 3 of 25
Model Number: 371 with model GLM in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

Model Number: 372 with model ARDL in generation 3 of 25
Model Number: 373 with model FFT in generation 3 of 25
Model Number: 374 with model MetricMotif in generation 3 of 25
Model Number: 375 with model SeasonalityMotif in generation 3 of 25
Model Number: 376 with model BasicLinearModel in generation 3 of 25
Model Number: 377 with model SeasonalityMotif in generation 3 of 25
Model Number: 378 with model SeasonalityMotif in generation 3 of 25
Model Number: 379 with model Cassandra in generation 3 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params ffill {'0': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gbtree', 'colsample_bylevel': 0.54, 'learning_rate': 0.0125, 'max_depth': 11, 'min_child_weight': 0.0127203, 'n_estimators': 319}, 'datepart_method': 'simple_binarized'}, 'fillna': 'linear'}, '1': {'fixed': True, 'window': 7, 'macro_micro': False, 'center': True}, '2': {}, '3': {}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 379 in generation 3: Cassandra
Model Number: 380 with model FBProphet in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.937e+08, tolerance: 2.178e+07

Model Number: 381 with model ConstantNaive in generation 3 of 25
Model Number: 382 with model SeasonalityMotif in generation 3 of 25
Model Number: 383 with model LastValueNaive in generation 3 of 25
Model Number: 384 with model MetricMotif in generation 3 of 25
Model Number: 385 with model DatepartRegression in generation 3 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params ffill {'0': {'lag': 1, 'fill': 'one'}, '1': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 1}, '2': {'decomp_type': 'seasonal_decompose', 'part': 'trend'}} with error ValueError('BTCD only works on multivarate series')") in model 385 in generation 3: DatepartRegression
Model Number: 386 with model AverageValueNaive in generation 3 of 25
Model Number: 387 with model AverageValueNaive in generation 3 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params ffill {'0': {'det_order': 0, 'k_ar_diff': 2}, '1': {'model': 'Linear', 'phi': 1, 'window': None, 'transform_dict': None}, '2': {'numtaps': 128, 'cutoff_hz': 0.01, 'window': 'hamming', 'sampling_frequency': 26, 'on_transform': True, 'on_inverse': False, 'bounds_only': False}} with error ValueError('Coint only works on multivarate series')") in model 387 in generation 3: AverageValueNaive
Model Number: 388 with model ConstantNaive in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/decomposition/_fastica.py:592: UserWarning:

Ignoring n_components with whiten=False.

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.44489e-25): result may not be accurate.

Template Eval Error: Exception("Transformer RegressionFilter failed on fit from params rolling_mean {'0': {'sigma': 1, 'rolling_window': 90, 'run_order': 'trend_first', 'regression_params': {'regression_model': {'model': 'ElasticNet', 'model_params': {'l1_ratio': 0.1, 'fit_intercept': True, 'selection': 'random', 'max_iter': 2000}}, 'datepart_method': 'expanded_binarized', 'polynomial_degree': None, 'transform_dict': {'fillna': None, 'transformations': {'0': 'AnomalyRemoval'}, 'transformation_params': {'0': {'method': 'zscore', 'transform_dict': {'transformations': {'0': 'DatepartRegression'}, 'transformation_params': {'0': {'datepart_method': 'simple_3', 'regression_model': {'model': 'ElasticNet', 'model_params': {}}}}}, 'method_params': {'distribution': 'uniform', 'alpha': 0.05}}}}, 'holiday_countries_used': False, 'lags': 2, 'forward_lags': None}, 'holiday_params': {'threshold': 0.8, 'splash_threshold': None, 'use_dayofmonth_holidays': True, 'use_wkdom_holidays': True, 'use_wkdeom_holidays': False, 'use_lunar_holidays': False, 'use_lunar_weekday': False, 'use_islamic_holidays': False, 'use_hebrew_holidays': False, 'use_hindu_holidays': False, 'anomaly_detector_params': {'method': 'mad', 'method_params': {'distribution': 'uniform', 'alpha': 0.05}, 'fillna': 'fake_date', 'transform_dict': {'transformations': {'0': 'DatepartRegression'}, 'transformation_params': {'0': {'datepart_method': 'simple_3', 'regression_model': {'model': 'FastRidge', 'model_params': {}}}}}, 'isolated_only': False, 'on_inverse': False}, 'remove_excess_anomalies': False, 'impact': 'datepart_regression', 'regression_params': {'regression_model': {'model': 'ElasticNet', 'model_params': {'l1_ratio': 0.1, 'fit_intercept': True, 'selection': 'random', 'max_iter': 2000}}, 'datepart_method': 'expanded_binarized', 'polynomial_degree': None, 'transform_dict': {'fillna': None, 'transformations': {'0': 'AnomalyRemoval'}, 'transformation_params': {'0': {'method': 'zscore', 'transform_dict': {'transformations': {'0': 'DatepartRegression'}, 'transformation_params': {'0': {'datepart_method': 'simple_3', 'regression_model': {'model': 'ElasticNet', 'model_params': {}}}}}, 'method_params': {'distribution': 'uniform', 'alpha': 0.05}}}}, 'holiday_countries_used': False, 'lags': 2, 'forward_lags': None}}, 'trend_method': 'rolling_mean'}, '1': {'fixed': True, 'window': 7, 'macro_micro': False, 'center': False}, '2': {}, '3': {'lag': 2, 'fill': 'bfill'}, '4': {}} with error ValueError('Found input variables with inconsistent numbers of samples: [2003, 738]')") in model 388 in generation 3: ConstantNaive
Model Number: 389 with model GLS in generation 3 of 25
Model Number: 390 with model SeasonalNaive in generation 3 of 25
Model Number: 391 with model ARDL in generation 3 of 25
Model Number: 392 with model MetricMotif in generation 3 of 25
Model Number: 393 with model SectionalMotif in generation 3 of 25
Model Number: 394 with model LastValueNaive in generation 3 of 25
Model Number: 395 with model DatepartRegression in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.003e+08, tolerance: 5.772e+07

Model Number: 396 with model Cassandra in generation 3 of 25
Model Number: 397 with model BasicLinearModel in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 398 with model ETS in generation 3 of 25
Model Number: 399 with model AverageValueNaive in generation 3 of 25
Model Number: 400 with model FFT in generation 3 of 25
Model Number: 401 with model SeasonalityMotif in generation 3 of 25
Model Number: 402 with model FFT in generation 3 of 25
Model Number: 403 with model ARDL in generation 3 of 25
Model Number: 404 with model SeasonalityMotif in generation 3 of 25
Model Number: 405 with model ARDL in generation 3 of 25
Model Number: 406 with model VAR in generation 3 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 406 in generation 3: VAR
Model Number: 407 with model SectionalMotif in generation 3 of 25
Model Number: 408 with model SeasonalNaive in generation 3 of 25
Model Number: 409 with model Cassandra in generation 3 of 25
Model Number: 410 with model SectionalMotif in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 411 with model SeasonalNaive in generation 3 of 25
Model Number: 412 with model LastValueNaive in generation 3 of 25
Model Number: 413 with model GLS in generation 3 of 25
Model Number: 414 with model UnivariateMotif in generation 3 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params ffill {'0': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 2}, '1': {'decomp_type': 'seasonal_decompose', 'part': 'trend'}, '2': {'rows': 1, 'lag': 7, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}} with error ValueError('BTCD only works on multivarate series')") in model 414 in generation 3: UnivariateMotif
Model Number: 415 with model RRVAR in generation 3 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params time {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'max'}, '1': {'window_size': 120, 'alpha': 3.0, 'grouping_forward_limit': 2, 'max_level_shifts': 30, 'alignment': 'average'}, '2': {'lag_1': 7, 'method': 'LastValue'}, '3': {'output_distribution': 'uniform', 'n_quantiles': 246}, '4': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 1}} with error ValueError('BTCD only works on multivarate series')") in model 415 in generation 3: RRVAR
Model Number: 416 with model SectionalMotif in generation 3 of 25
Model Number: 417 with model FFT in generation 3 of 25
Model Number: 418 with model Cassandra in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

Model Number: 419 with model SectionalMotif in generation 3 of 25
Model Number: 420 with model UnivariateMotif in generation 3 of 25
Model Number: 421 with model DatepartRegression in generation 3 of 25
Model Number: 422 with model DatepartRegression in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning:

Liblinear failed to converge, increase the number of iterations.

Model Number: 423 with model ARDL in generation 3 of 25
Model Number: 424 with model FFT in generation 3 of 25
Model Number: 425 with model UnivariateMotif in generation 3 of 25
Model Number: 426 with model Cassandra in generation 3 of 25
Model Number: 427 with model BasicLinearModel in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

Model Number: 428 with model SeasonalityMotif in generation 3 of 25
Model Number: 429 with model SectionalMotif in generation 3 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params linear {'0': {}, '1': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 0.5, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '2': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 1}, '3': {'discretization': 'sklearn-uniform', 'n_bins': 10}} with error ValueError('BTCD only works on multivarate series')") in model 429 in generation 3: SectionalMotif
Model Number: 430 with model ARDL in generation 3 of 25
Model Number: 431 with model GLM in generation 3 of 25
Model Number: 432 with model SectionalMotif in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Template Eval Error: ValueError('Model SectionalMotif returned NaN for one or more series. fail_on_forecast_nan=True') in model 432 in generation 3: SectionalMotif
Model Number: 433 with model SeasonalNaive in generation 3 of 25
Model Number: 434 with model MetricMotif in generation 3 of 25
Model Number: 435 with model GLM in generation 3 of 25
Model Number: 436 with model UnivariateMotif in generation 3 of 25
Model Number: 437 with model ETS in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 438 with model SeasonalNaive in generation 3 of 25
Model Number: 439 with model SeasonalNaive in generation 3 of 25
Model Number: 440 with model FFT in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 441 with model ARDL in generation 3 of 25
Model Number: 442 with model AverageValueNaive in generation 3 of 25
Model Number: 443 with model RRVAR in generation 3 of 25
Model Number: 444 with model DatepartRegression in generation 3 of 25
Model Number: 445 with model FFT in generation 3 of 25
Model Number: 446 with model ARDL in generation 3 of 25
Model Number: 447 with model ARDL in generation 3 of 25
Model Number: 448 with model Cassandra in generation 3 of 25
Model Number: 449 with model MetricMotif in generation 3 of 25
Model Number: 450 with model BasicLinearModel in generation 3 of 25
Model Number: 451 with model FBProphet in generation 3 of 25
Model Number: 452 with model SectionalMotif in generation 3 of 25
Model Number: 453 with model ConstantNaive in generation 3 of 25
Model Number: 454 with model Cassandra in generation 3 of 25
Model Number: 455 with model MetricMotif in generation 3 of 25
Model Number: 456 with model ARDL in generation 3 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params fake_date {'0': {'det_order': 0, 'k_ar_diff': 2}, '1': {}, '2': {'window': 10}, '3': {'rows': 1, 'lag': 84, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'max'}} with error ValueError('Coint only works on multivarate series')") in model 456 in generation 3: ARDL
Model Number: 457 with model BasicLinearModel in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_glm/glm.py:285: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

Model Number: 458 with model FBProphet in generation 3 of 25
No anomalies detected.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 459 with model UnivariateMotif in generation 3 of 25
Model Number: 460 with model BasicLinearModel in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 461 with model ETS in generation 3 of 25
Model Number: 462 with model ConstantNaive in generation 3 of 25
Model Number: 463 with model GLM in generation 3 of 25
Model Number: 464 with model ETS in generation 3 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 465 with model ETS in generation 3 of 25
Model Number: 466 with model FBProphet in generation 3 of 25
Model Number: 467 with model FBProphet in generation 3 of 25
Model Number: 468 with model DatepartRegression in generation 3 of 25
Model Number: 469 with model Cassandra in generation 3 of 25
Model Number: 470 with model MetricMotif in generation 3 of 25
Model Number: 471 with model ETS in generation 3 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params mean {'0': {'mode': 'upscale', 'factor': 3, 'down_method': 'decimate', 'fill_method': 'linear'}, '1': {}, '2': {}, '3': {'det_order': -1, 'k_ar_diff': 1}} with error ValueError('Coint only works on multivarate series')") in model 471 in generation 3: ETS
Model Number: 472 with model FFT in generation 3 of 25
New Generation: 4 of 25
Model Number: 473 with model FFT in generation 4 of 25
Model Number: 474 with model MetricMotif in generation 4 of 25
Model Number: 475 with model ARDL in generation 4 of 25
Model Number: 476 with model Cassandra in generation 4 of 25
Model Number: 477 with model ConstantNaive in generation 4 of 25
Model Number: 478 with model ETS in generation 4 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params mean {'0': {}, '1': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gbtree', 'max_depth': 6, 'eta': 0.01, 'min_child_weight': 0.5, 'subsample': 1, 'colsample_bylevel': 0.9, 'reg_alpha': 0, 'reg_lambda': 1, 'n_estimators': 10, 'multi_strategy': 'multi_output_tree', 'tree_method': 'hist'}, 'datepart_method': [7, 365.25]}, 'fillna': 'ffill'}, '2': {}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 478 in generation 4: ETS
Model Number: 479 with model DatepartRegression in generation 4 of 25
Model Number: 480 with model FBProphet in generation 4 of 25
Model Number: 481 with model MetricMotif in generation 4 of 25
Model Number: 482 with model FBProphet in generation 4 of 25

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 483 with model FBProphet in generation 4 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

Model Number: 484 with model Cassandra in generation 4 of 25
Model Number: 485 with model SectionalMotif in generation 4 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 485 in generation 4: SectionalMotif
Model Number: 486 with model FFT in generation 4 of 25
Model Number: 487 with model GLM in generation 4 of 25
Template Eval Error: ValueError('The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.') in model 487 in generation 4: GLM
Model Number: 488 with model SectionalMotif in generation 4 of 25
Model Number: 489 with model Cassandra in generation 4 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

invalid value encountered in log

Model Number: 490 with model BasicLinearModel in generation 4 of 25
Model Number: 491 with model SeasonalityMotif in generation 4 of 25
Model Number: 492 with model ETS in generation 4 of 25
Template Eval Error: Exception('Transformer FIRFilter failed on fit from params rolling_mean {\'0\': {\'numtaps\': 256, \'cutoff_hz\': 0.1, \'window\': [\'kaiser\', 4.0], \'sampling_frequency\': 24, \'on_transform\': True, \'on_inverse\': False, \'bounds_only\': False}, \'1\': {}, \'2\': {}, \'3\': {\'method\': 100}, \'4\': {\'rolling_window\': 0.1, \'n_tails\': 30, \'n_future\': 0.2, \'method\': \'mean\', \'macro_micro\': False}} with error ValueError("<class \'list\'> as window type is not supported.")') in model 492 in generation 4: ETS
Model Number: 493 with model SeasonalityMotif in generation 4 of 25
Model Number: 494 with model ETS in generation 4 of 25
Model Number: 495 with model BasicLinearModel in generation 4 of 25
Model Number: 496 with model AverageValueNaive in generation 4 of 25
Model Number: 497 with model WindowRegression in generation 4 of 25
Model Number: 498 with model ARDL in generation 4 of 25
Model Number: 499 with model SeasonalNaive in generation 4 of 25
Model Number: 500 with model LastValueNaive in generation 4 of 25
Model Number: 501 with model GLS in generation 4 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params ffill {'0': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 2}, '1': {'lag_1': 22, 'method': 'LastValue'}, '2': {'model_name': 'local linear hidden state with seasonal 7', 'state_transition': [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]], 'process_noise': [[0.0016, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1e-06, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]], 'observation_model': [[1, 1, 0, 0, 0, 0, 0, 0]], 'observation_noise': 0.1, 'em_iter': 10, 'on_transform': True, 'on_inverse': False}, '3': {'rows': 1, 'lag': 7, 'method': 'additive', 'strength': 0.9, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}, '4': {'model': 'Linear', 'changepoint_spacing': None, 'changepoint_distance_end': 5040, 'datepart_method': ['dayofweek', [365.25, 14]]}} with error ValueError('BTCD only works on multivarate series')") in model 501 in generation 4: GLS
Model Number: 502 with model FBProphet in generation 4 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 502 in generation 4: FBProphet
Model Number: 503 with model UnivariateMotif in generation 4 of 25
Model Number: 504 with model ConstantNaive in generation 4 of 25
Model Number: 505 with model SeasonalNaive in generation 4 of 25
Model Number: 506 with model FFT in generation 4 of 25
Model Number: 507 with model FFT in generation 4 of 25
Model Number: 508 with model ETS in generation 4 of 25
Model Number: 509 with model SectionalMotif in generation 4 of 25
Model Number: 510 with model SeasonalNaive in generation 4 of 25
Model Number: 511 with model LastValueNaive in generation 4 of 25
Model Number: 512 with model RRVAR in generation 4 of 25
Model Number: 513 with model AverageValueNaive in generation 4 of 25
Model Number: 514 with model Cassandra in generation 4 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning:

invalid value encountered in divide

Model Number: 515 with model ETS in generation 4 of 25
Model Number: 516 with model BasicLinearModel in generation 4 of 25
Model Number: 517 with model FBProphet in generation 4 of 25
No anomalies detected.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 518 with model BasicLinearModel in generation 4 of 25
Template Eval Error: Exception('Transformer PCA failed on fit from params fake_date {\'0\': {}, \'1\': {}, \'2\': {\'whiten\': False, \'n_components\': 24}, \'3\': {\'det_order\': -1, \'k_ar_diff\': 1}} with error ValueError("n_components=24 must be between 0 and min(n_samples, n_features)=1 with svd_solver=\'covariance_eigh\'")') in model 518 in generation 4: BasicLinearModel
Model Number: 519 with model ConstantNaive in generation 4 of 25
Model Number: 520 with model FFT in generation 4 of 25
Model Number: 521 with model GLS in generation 4 of 25
Model Number: 522 with model DatepartRegression in generation 4 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 522 in generation 4: DatepartRegression
Model Number: 523 with model SeasonalNaive in generation 4 of 25
Model Number: 524 with model FBProphet in generation 4 of 25
Model Number: 525 with model LastValueNaive in generation 4 of 25
Model Number: 526 with model SeasonalityMotif in generation 4 of 25
Model Number: 527 with model ARDL in generation 4 of 25
Model Number: 528 with model ConstantNaive in generation 4 of 25
Model Number: 529 with model GLM in generation 4 of 25
Model Number: 530 with model GLM in generation 4 of 25
Model Number: 531 with model UnivariateMotif in generation 4 of 25
Model Number: 532 with model SectionalMotif in generation 4 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 533 with model Cassandra in generation 4 of 25
Model Number: 534 with model Cassandra in generation 4 of 25
Model Number: 535 with model SeasonalityMotif in generation 4 of 25
Model Number: 536 with model SeasonalityMotif in generation 4 of 25
Model Number: 537 with model FFT in generation 4 of 25
Model Number: 538 with model FFT in generation 4 of 25
Model Number: 539 with model SeasonalNaive in generation 4 of 25
Model Number: 540 with model ARDL in generation 4 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params rolling_mean {'0': {}, '1': {'window_size': 90, 'alpha': 1.0, 'grouping_forward_limit': 6, 'max_level_shifts': 5, 'alignment': 'rolling_diff_3nn'}, '2': {}, '3': {'det_order': -1, 'k_ar_diff': 2}, '4': {'rows': 1, 'lag': 7, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'max'}} with error ValueError('Coint only works on multivarate series')") in model 540 in generation 4: ARDL
Model Number: 541 with model ETS in generation 4 of 25
Model Number: 542 with model FFT in generation 4 of 25
Model Number: 543 with model SeasonalNaive in generation 4 of 25
Model Number: 544 with model SectionalMotif in generation 4 of 25
Model Number: 545 with model ETS in generation 4 of 25
Model Number: 546 with model UnivariateMotif in generation 4 of 25
Model Number: 547 with model SeasonalityMotif in generation 4 of 25
Model Number: 548 with model ETS in generation 4 of 25
Model Number: 549 with model ETS in generation 4 of 25
Model Number: 550 with model BasicLinearModel in generation 4 of 25
Model Number: 551 with model Cassandra in generation 4 of 25
Model Number: 552 with model ARDL in generation 4 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 553 with model GLM in generation 4 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning:

invalid value encountered in matmul

Model Number: 554 with model ARDL in generation 4 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 554 in generation 4: ARDL
Model Number: 555 with model GLM in generation 4 of 25
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 555 in generation 4: GLM
Model Number: 556 with model ARDL in generation 4 of 25
Model Number: 557 with model AverageValueNaive in generation 4 of 25
Model Number: 558 with model ETS in generation 4 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1402: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

invalid value encountered in log

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:527: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

divide by zero encountered in log

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:86: RuntimeWarning:

invalid value encountered in reduce

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:1328: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 559 with model Cassandra in generation 4 of 25
Model Number: 560 with model SeasonalNaive in generation 4 of 25
Model Number: 561 with model GLM in generation 4 of 25
Model Number: 562 with model ETS in generation 4 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params ffill {'0': {}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gblinear', 'max_depth': 2, 'eta': 0.03, 'min_child_weight': 1, 'subsample': 1, 'colsample_bylevel': 0.9, 'reg_alpha': 0, 'reg_lambda': 1, 'n_estimators': 1000, 'grow_policy': 'lossguide'}, 'datepart_method': 'recurring'}, 'fillna': 'ffill'}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 562 in generation 4: ETS
Model Number: 563 with model GLM in generation 4 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 564 with model SeasonalityMotif in generation 4 of 25
Model Number: 565 with model Cassandra in generation 4 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 566 with model FBProphet in generation 4 of 25
Model Number: 567 with model FFT in generation 4 of 25
Model Number: 568 with model UnivariateMotif in generation 4 of 25
Model Number: 569 with model AverageValueNaive in generation 4 of 25
Model Number: 570 with model ConstantNaive in generation 4 of 25
Model Number: 571 with model BasicLinearModel in generation 4 of 25
Template Eval Error: ValueError('matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 738 is different from 2003)') in model 571 in generation 4: BasicLinearModel
Model Number: 572 with model GLS in generation 4 of 25
Model Number: 573 with model DatepartRegression in generation 4 of 25
Model Number: 574 with model SeasonalNaive in generation 4 of 25
Model Number: 575 with model SectionalMotif in generation 4 of 25
Model Number: 576 with model ARDL in generation 4 of 25
Model Number: 577 with model FBProphet in generation 4 of 25

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

New Generation: 5 of 25
Model Number: 578 with model BasicLinearModel in generation 5 of 25
Model Number: 579 with model ARDL in generation 5 of 25
Model Number: 580 with model UnivariateMotif in generation 5 of 25
Model Number: 581 with model GLM in generation 5 of 25
Model Number: 582 with model Cassandra in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 583 with model SeasonalNaive in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 584 with model BasicLinearModel in generation 5 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 584 in generation 5: BasicLinearModel
Model Number: 585 with model DatepartRegression in generation 5 of 25
Model Number: 586 with model BasicLinearModel in generation 5 of 25
Model Number: 587 with model ARDL in generation 5 of 25
Model Number: 588 with model MetricMotif in generation 5 of 25
Model Number: 589 with model BasicLinearModel in generation 5 of 25
Model Number: 590 with model SectionalMotif in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.487e+09, tolerance: 5.138e+07

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 591 with model SeasonalNaive in generation 5 of 25
Model Number: 592 with model GLM in generation 5 of 25
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 592 in generation 5: GLM
Model Number: 593 with model LastValueNaive in generation 5 of 25
Model Number: 594 with model DatepartRegression in generation 5 of 25
Model Number: 595 with model ConstantNaive in generation 5 of 25
Model Number: 596 with model ARDL in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:527: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:445: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:1328: RuntimeWarning:

invalid value encountered in multiply

Model Number: 597 with model ARDL in generation 5 of 25
Model Number: 598 with model AverageValueNaive in generation 5 of 25
Model Number: 599 with model AverageValueNaive in generation 5 of 25
Model Number: 600 with model FBProphet in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 601 with model SeasonalityMotif in generation 5 of 25
Model Number: 602 with model FBProphet in generation 5 of 25
Model Number: 603 with model UnivariateMotif in generation 5 of 25
Model Number: 604 with model AverageValueNaive in generation 5 of 25
Model Number: 605 with model Cassandra in generation 5 of 25
Model Number: 606 with model FFT in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 607 with model FBProphet in generation 5 of 25
Model Number: 608 with model FBProphet in generation 5 of 25
Model Number: 609 with model DatepartRegression in generation 5 of 25
Model Number: 610 with model SeasonalityMotif in generation 5 of 25
Model Number: 611 with model ARDL in generation 5 of 25
Model Number: 612 with model FFT in generation 5 of 25
Model Number: 613 with model GLM in generation 5 of 25
Model Number: 614 with model SeasonalityMotif in generation 5 of 25
Model Number: 615 with model SectionalMotif in generation 5 of 25
Model Number: 616 with model SeasonalNaive in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 617 with model MetricMotif in generation 5 of 25
Model Number: 618 with model Cassandra in generation 5 of 25
Model Number: 619 with model BasicLinearModel in generation 5 of 25
Model Number: 620 with model FBProphet in generation 5 of 25
Model Number: 621 with model ETS in generation 5 of 25
Model Number: 622 with model ConstantNaive in generation 5 of 25
Model Number: 623 with model FFT in generation 5 of 25
Model Number: 624 with model ARDL in generation 5 of 25
Model Number: 625 with model Cassandra in generation 5 of 25
Model Number: 626 with model ETS in generation 5 of 25
Model Number: 627 with model Cassandra in generation 5 of 25
Model Number: 628 with model FBProphet in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning:

invalid value encountered in divide

Model Number: 629 with model FFT in generation 5 of 25
Model Number: 630 with model SectionalMotif in generation 5 of 25
Model Number: 631 with model SeasonalNaive in generation 5 of 25
Model Number: 632 with model RRVAR in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 633 with model ETS in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.44489e-25): result may not be accurate.

Model Number: 634 with model GLM in generation 5 of 25
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 634 in generation 5: GLM
Model Number: 635 with model SectionalMotif in generation 5 of 25
Model Number: 636 with model MetricMotif in generation 5 of 25
Model Number: 637 with model FFT in generation 5 of 25
Model Number: 638 with model FFT in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1402: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

invalid value encountered in log

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:527: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

divide by zero encountered in log

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:86: RuntimeWarning:

invalid value encountered in reduce

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:1328: RuntimeWarning:

invalid value encountered in multiply

Model Number: 639 with model SeasonalNaive in generation 5 of 25
Model Number: 640 with model UnivariateMotif in generation 5 of 25
Model Number: 641 with model ARDL in generation 5 of 25
Model Number: 642 with model GLS in generation 5 of 25
Model Number: 643 with model Cassandra in generation 5 of 25
Template Eval Error: Exception('Transformer ChangepointDetrend failed on fit from params fake_date {\'0\': {}, \'1\': {\'n_harmonics\': 10, \'detrend\': \'linear\'}, \'2\': {}, \'3\': {\'model\': \'Poisson\', \'changepoint_spacing\': 28, \'changepoint_distance_end\': 360, \'datepart_method\': None}, \'4\': {}, \'5\': {\'part\': \'trend\', \'lamb\': 1600}} with error ValueError("Some value(s) of y are out of the valid range of the loss \'HalfPoissonLoss\'.")') in model 643 in generation 5: Cassandra
Model Number: 644 with model SeasonalityMotif in generation 5 of 25
Model Number: 645 with model SectionalMotif in generation 5 of 25
Template Eval Error: Exception('Transformer ChangepointDetrend failed on fit from params ffill {\'0\': {\'lag_1\': 24, \'method\': 5}, \'1\': {\'model\': \'Gamma\', \'changepoint_spacing\': 5040, \'changepoint_distance_end\': 5040, \'datepart_method\': None}, \'2\': {}, \'3\': {\'rows\': 1, \'lag\': 7, \'method\': \'additive\', \'strength\': 1.0, \'first_value_only\': False, \'threshold\': 10, \'threshold_method\': \'mean\'}} with error ValueError("Some value(s) of y are out of the valid range of the loss \'HalfGammaLoss\'.")') in model 645 in generation 5: SectionalMotif
Model Number: 646 with model BasicLinearModel in generation 5 of 25
Template Eval Error: Exception('Transformer FIRFilter failed on fit from params linear {\'0\': {\'rows\': 1, \'lag\': 1, \'method\': \'additive\', \'strength\': 1.0, \'first_value_only\': False, \'threshold\': 1, \'threshold_method\': \'max\'}, \'1\': {\'rolling_window\': 0.05, \'n_tails\': 0.1, \'n_future\': 0.1, \'method\': \'mean\', \'macro_micro\': False}, \'2\': {\'numtaps\': 64, \'cutoff_hz\': 0.1, \'window\': [\'gaussian\', 1.0], \'sampling_frequency\': 2, \'on_transform\': True, \'on_inverse\': False, \'bounds_only\': False}, \'3\': {\'output_distribution\': \'uniform\', \'n_quantiles\': 1000}, \'4\': {}} with error ValueError("<class \'list\'> as window type is not supported.")') in model 646 in generation 5: BasicLinearModel
Model Number: 647 with model AverageValueNaive in generation 5 of 25
Model Number: 648 with model GLM in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 649 with model FFT in generation 5 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params rolling_mean {'0': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 2}, '1': {'rows': 4}, '2': {'model': 'Linear', 'phi': 1, 'window': 10, 'transform_dict': None}} with error ValueError('BTCD only works on multivarate series')") in model 649 in generation 5: FFT
Model Number: 650 with model LastValueNaive in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 651 with model SeasonalNaive in generation 5 of 25
Model Number: 652 with model ETS in generation 5 of 25
Model Number: 653 with model Cassandra in generation 5 of 25
Model Number: 654 with model GLM in generation 5 of 25
Model Number: 655 with model BasicLinearModel in generation 5 of 25
Model Number: 656 with model FFT in generation 5 of 25
Model Number: 657 with model FFT in generation 5 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'mean'}, '1': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 1}, '2': {'lag': 1, 'fill': 'bfill'}, '3': {'regression_model': {'model': 'MLP', 'model_params': {'hidden_layer_sizes': [25, 15, 25], 'max_iter': 1000, 'activation': 'tanh', 'solver': 'lbfgs', 'early_stopping': False, 'learning_rate_init': 0.001, 'alpha': 0.1}}, 'datepart_method': 'simple_binarized', 'polynomial_degree': None, 'transform_dict': {'fillna': None, 'transformations': {'0': 'ScipyFilter'}, 'transformation_params': {'0': {'method': 'savgol_filter', 'method_args': {'window_length': 31, 'polyorder': 3, 'deriv': 0, 'mode': 'interp'}}}}, 'holiday_countries_used': True, 'lags': None, 'forward_lags': None}} with error ValueError('BTCD only works on multivarate series')") in model 657 in generation 5: FFT
Model Number: 658 with model Cassandra in generation 5 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 659 with model ETS in generation 5 of 25
Model Number: 660 with model ARDL in generation 5 of 25
Model Number: 661 with model FFT in generation 5 of 25
New Generation: 6 of 25
Model Number: 662 with model AverageValueNaive in generation 6 of 25
Model Number: 663 with model SectionalMotif in generation 6 of 25
Model Number: 664 with model BasicLinearModel in generation 6 of 25
Model Number: 665 with model UnivariateMotif in generation 6 of 25
Model Number: 666 with model ARDL in generation 6 of 25
Model Number: 667 with model ETS in generation 6 of 25
Model Number: 668 with model ARDL in generation 6 of 25
Model Number: 669 with model SeasonalNaive in generation 6 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 670 with model AverageValueNaive in generation 6 of 25
Model Number: 671 with model SeasonalNaive in generation 6 of 25
Model Number: 672 with model Cassandra in generation 6 of 25
Model Number: 673 with model ARDL in generation 6 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 674 with model Cassandra in generation 6 of 25
Model Number: 675 with model SeasonalNaive in generation 6 of 25
Model Number: 676 with model GLM in generation 6 of 25
Model Number: 677 with model SeasonalNaive in generation 6 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 678 with model FBProphet in generation 6 of 25
Model Number: 679 with model FFT in generation 6 of 25
Model Number: 680 with model UnivariateMotif in generation 6 of 25
Model Number: 681 with model SeasonalityMotif in generation 6 of 25
Template Eval Error: ValueError('Model SeasonalityMotif returned NaN for one or more series. fail_on_forecast_nan=True') in model 681 in generation 6: SeasonalityMotif
Model Number: 682 with model GLM in generation 6 of 25
Model Number: 683 with model Cassandra in generation 6 of 25

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning:

Mean of empty slice.

/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:130: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 684 with model UnivariateMotif in generation 6 of 25
Model Number: 685 with model AverageValueNaive in generation 6 of 25
Model Number: 686 with model DatepartRegression in generation 6 of 25
Model Number: 687 with model UnivariateMotif in generation 6 of 25
Model Number: 688 with model FFT in generation 6 of 25
Model Number: 689 with model Cassandra in generation 6 of 25
Model Number: 690 with model GLS in generation 6 of 25
Model Number: 691 with model SectionalMotif in generation 6 of 25
Model Number: 692 with model GLM in generation 6 of 25
Model Number: 693 with model FFT in generation 6 of 25
Model Number: 694 with model UnivariateMotif in generation 6 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1402: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1402: RuntimeWarning:

overflow encountered in divide

Model Number: 695 with model DatepartRegression in generation 6 of 25
Epoch 1/50

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

24/24 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 75.8096
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 42.3928
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 42.1644
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 41.5828
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 41.7017
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 40.2549
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.9870
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 41.1003
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.6659
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 40.7675
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.8164
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 39.6022
Epoch 13/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 39.7079
Epoch 14/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 41.3006
Epoch 15/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 40.3763
Epoch 16/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.9372
Epoch 17/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 39.7393
Epoch 18/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.3835
Epoch 19/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.4307
Epoch 20/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.5374
Epoch 21/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.8010
Epoch 22/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.8749
Epoch 23/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.0984
Epoch 24/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 40.2939
Epoch 25/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 40.4495
Epoch 26/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 39.7162
Epoch 27/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 40.5269
Epoch 28/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 40.9610
Epoch 29/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 40.6337
Epoch 30/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 40.0023
Epoch 31/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 41.1335
Epoch 32/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 41.1880
Epoch 33/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 40.4935
Epoch 34/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.3074
Epoch 35/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 40.0376
Epoch 36/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.7492
Epoch 37/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 40.0323
Epoch 38/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.5992
Epoch 39/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 39.8726
Epoch 40/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 39.9480
Epoch 41/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.2580
Epoch 42/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 39.7489
Epoch 43/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 40.7747
Epoch 44/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 39.5998
Epoch 45/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 39.6121
Epoch 46/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 40.2982
Epoch 47/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 40.3481
Epoch 48/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 39.6795
Epoch 49/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 40.3317
Epoch 50/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 39.7838
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 680ms/step
Model Number: 696 with model ETS in generation 6 of 25
Model Number: 697 with model FFT in generation 6 of 25
Model Number: 698 with model ARDL in generation 6 of 25
Model Number: 699 with model ETS in generation 6 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params ffill {'0': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'n_estimators': 7, 'max_leaves': 4, 'min_child_weight': 2.5, 'learning_rate': 0.35, 'subsample': 0.95, 'colsample_bylevel': 0.56, 'colsample_bytree': 0.46, 'reg_alpha': 0.0016, 'reg_lambda': 5.3}, 'datepart_method': 'simple_2'}, 'fillna': None}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 699 in generation 6: ETS
Model Number: 700 with model Cassandra in generation 6 of 25
Model Number: 701 with model ARDL in generation 6 of 25
Model Number: 702 with model FFT in generation 6 of 25
Model Number: 703 with model BasicLinearModel in generation 6 of 25
Model Number: 704 with model SeasonalityMotif in generation 6 of 25
Model Number: 705 with model AverageValueNaive in generation 6 of 25
Model Number: 706 with model FFT in generation 6 of 25
Model Number: 707 with model GLM in generation 6 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Template Eval Error: ValueError('The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.') in model 707 in generation 6: GLM
Model Number: 708 with model DatepartRegression in generation 6 of 25
Model Number: 709 with model UnivariateMotif in generation 6 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

invalid value encountered in log

Model Number: 710 with model SeasonalNaive in generation 6 of 25
Model Number: 711 with model GLS in generation 6 of 25
Model Number: 712 with model Cassandra in generation 6 of 25
Model Number: 713 with model GLM in generation 6 of 25
Template Eval Error: ValueError('regression_type=user and no future_regressor passed') in model 713 in generation 6: GLM
Model Number: 714 with model LastValueNaive in generation 6 of 25
Model Number: 715 with model Cassandra in generation 6 of 25
Model Number: 716 with model GLS in generation 6 of 25
Model Number: 717 with model BasicLinearModel in generation 6 of 25
Model Number: 718 with model ARDL in generation 6 of 25
Model Number: 719 with model LastValueNaive in generation 6 of 25
Model Number: 720 with model SeasonalNaive in generation 6 of 25
Model Number: 721 with model ETS in generation 6 of 25
Model Number: 722 with model Cassandra in generation 6 of 25
Model Number: 723 with model AverageValueNaive in generation 6 of 25
Model Number: 724 with model AverageValueNaive in generation 6 of 25
Model Number: 725 with model SeasonalNaive in generation 6 of 25
Model Number: 726 with model DatepartRegression in generation 6 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 727 with model RRVAR in generation 6 of 25

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.44489e-25): result may not be accurate.

Model Number: 728 with model FFT in generation 6 of 25
Model Number: 729 with model GLM in generation 6 of 25
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 729 in generation 6: GLM
Model Number: 730 with model DatepartRegression in generation 6 of 25
Model Number: 731 with model DatepartRegression in generation 6 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 731 in generation 6: DatepartRegression
Model Number: 732 with model FBProphet in generation 6 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:527: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

divide by zero encountered in log

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:1328: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 733 with model ETS in generation 6 of 25
Model Number: 734 with model Cassandra in generation 6 of 25
Model Number: 735 with model GLS in generation 6 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 736 with model BasicLinearModel in generation 6 of 25
Model Number: 737 with model UnivariateMotif in generation 6 of 25
Model Number: 738 with model SectionalMotif in generation 6 of 25
Model Number: 739 with model Cassandra in generation 6 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 740 with model ETS in generation 6 of 25
Model Number: 741 with model SeasonalityMotif in generation 6 of 25
Model Number: 742 with model ARDL in generation 6 of 25
Model Number: 743 with model ARDL in generation 6 of 25
Model Number: 744 with model GLM in generation 6 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/decomposition/_fastica.py:592: UserWarning:

Ignoring n_components with whiten=False.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 745 with model GLS in generation 6 of 25
New Generation: 7 of 25
Model Number: 746 with model DatepartRegression in generation 7 of 25
Model Number: 747 with model MetricMotif in generation 7 of 25
Model Number: 748 with model AverageValueNaive in generation 7 of 25
Model Number: 749 with model RRVAR in generation 7 of 25
Model Number: 750 with model GLS in generation 7 of 25
Model Number: 751 with model FFT in generation 7 of 25
Model Number: 752 with model SeasonalNaive in generation 7 of 25
Model Number: 753 with model UnivariateMotif in generation 7 of 25
Model Number: 754 with model SectionalMotif in generation 7 of 25
Model Number: 755 with model FBProphet in generation 7 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 755 in generation 7: FBProphet
Model Number: 756 with model Cassandra in generation 7 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params fake_date {'0': {}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {}, '3': {'lag': 1, 'fill': 'bfill'}, '4': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 1}} with error ValueError('BTCD only works on multivarate series')") in model 756 in generation 7: Cassandra
Model Number: 757 with model SeasonalNaive in generation 7 of 25
Model Number: 758 with model BasicLinearModel in generation 7 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 759 with model ETS in generation 7 of 25
Model Number: 760 with model SeasonalNaive in generation 7 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 761 with model SeasonalityMotif in generation 7 of 25
Model Number: 762 with model SectionalMotif in generation 7 of 25
Model Number: 763 with model SeasonalNaive in generation 7 of 25
Model Number: 764 with model UnivariateMotif in generation 7 of 25
Model Number: 765 with model Cassandra in generation 7 of 25
Model Number: 766 with model GLM in generation 7 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params fake_date {'0': {}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 2}, '3': {}, '4': {}} with error ValueError('BTCD only works on multivarate series')") in model 766 in generation 7: GLM
Model Number: 767 with model BasicLinearModel in generation 7 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 768 with model Cassandra in generation 7 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 769 with model Cassandra in generation 7 of 25

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.44489e-25): result may not be accurate.

Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 769 in generation 7: Cassandra
Model Number: 770 with model DatepartRegression in generation 7 of 25
Model Number: 771 with model Cassandra in generation 7 of 25
Model Number: 772 with model FFT in generation 7 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 773 with model GLM in generation 7 of 25
Model Number: 774 with model ETS in generation 7 of 25
Model Number: 775 with model SeasonalNaive in generation 7 of 25
Model Number: 776 with model AverageValueNaive in generation 7 of 25
Model Number: 777 with model FFT in generation 7 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 778 with model ConstantNaive in generation 7 of 25
Model Number: 779 with model ARDL in generation 7 of 25
Model Number: 780 with model FBProphet in generation 7 of 25
No anomalies detected.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 781 with model LastValueNaive in generation 7 of 25
Model Number: 782 with model ETS in generation 7 of 25
Model Number: 783 with model GLS in generation 7 of 25
Model Number: 784 with model SeasonalNaive in generation 7 of 25
Model Number: 785 with model GLS in generation 7 of 25
Model Number: 786 with model GLM in generation 7 of 25
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 786 in generation 7: GLM
Model Number: 787 with model FFT in generation 7 of 25
Model Number: 788 with model AverageValueNaive in generation 7 of 25
Model Number: 789 with model GLS in generation 7 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1402: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

invalid value encountered in log

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:527: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

divide by zero encountered in log

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:86: RuntimeWarning:

invalid value encountered in reduce

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:1328: RuntimeWarning:

invalid value encountered in multiply

Model Number: 790 with model FBProphet in generation 7 of 25
Model Number: 791 with model ARDL in generation 7 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params ffill {'0': {'method': 'rolling_zscore', 'method_params': {'distribution': 'norm', 'alpha': 0.05, 'rolling_periods': 28, 'center': False}, 'fillna': 'linear', 'transform_dict': None, 'isolated_only': False, 'on_inverse': False}, '1': {'constant': 0, 'reintroduction_model': None, 'fillna': 'linear'}, '2': {'output_distribution': 'uniform', 'n_quantiles': 246}, '3': {'det_order': -1, 'k_ar_diff': 1}, '4': {'model_name': 'local linear stochastic seasonal dummy', 'state_transition': [[1, 0, 0, 0], [0, -1, -1, -1], [0, 1, 0, 0], [0, 0, 1, 0]], 'process_noise': [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], 'observation_model': [[1, 1, 0, 0]], 'observation_noise': 0.04, 'em_iter': 10, 'on_transform': True, 'on_inverse': False}} with error ValueError('Coint only works on multivarate series')") in model 791 in generation 7: ARDL
Model Number: 792 with model FFT in generation 7 of 25
Model Number: 793 with model LastValueNaive in generation 7 of 25
Model Number: 794 with model AverageValueNaive in generation 7 of 25
Model Number: 795 with model ETS in generation 7 of 25
Model Number: 796 with model ETS in generation 7 of 25
Model Number: 797 with model SectionalMotif in generation 7 of 25
Model Number: 798 with model ARDL in generation 7 of 25
Model Number: 799 with model GLM in generation 7 of 25
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 799 in generation 7: GLM
Model Number: 800 with model Cassandra in generation 7 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1402: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

invalid value encountered in log

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:527: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

divide by zero encountered in log

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:86: RuntimeWarning:

invalid value encountered in reduce

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:1328: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 801 with model SeasonalNaive in generation 7 of 25
Model Number: 802 with model BasicLinearModel in generation 7 of 25
Model Number: 803 with model ARDL in generation 7 of 25
Model Number: 804 with model SeasonalNaive in generation 7 of 25
Model Number: 805 with model Cassandra in generation 7 of 25
Model Number: 806 with model BasicLinearModel in generation 7 of 25
Model Number: 807 with model ARDL in generation 7 of 25
Model Number: 808 with model SeasonalNaive in generation 7 of 25
Model Number: 809 with model DatepartRegression in generation 7 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 809 in generation 7: DatepartRegression
Model Number: 810 with model BasicLinearModel in generation 7 of 25
Model Number: 811 with model ETS in generation 7 of 25
Model Number: 812 with model LastValueNaive in generation 7 of 25
Model Number: 813 with model SectionalMotif in generation 7 of 25
Model Number: 814 with model LastValueNaive in generation 7 of 25
Model Number: 815 with model SeasonalNaive in generation 7 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning:

datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).

Model Number: 816 with model AverageValueNaive in generation 7 of 25
Model Number: 817 with model AverageValueNaive in generation 7 of 25
Model Number: 818 with model AverageValueNaive in generation 7 of 25
Model Number: 819 with model Cassandra in generation 7 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:793: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 820 with model FFT in generation 7 of 25
Template Eval Error: ValueError('Model FFT returned NaN for one or more series. fail_on_forecast_nan=True') in model 820 in generation 7: FFT
Model Number: 821 with model FFT in generation 7 of 25
Model Number: 822 with model ARDL in generation 7 of 25
Model Number: 823 with model SectionalMotif in generation 7 of 25
Model Number: 824 with model DatepartRegression in generation 7 of 25
Model Number: 825 with model LastValueNaive in generation 7 of 25
Model Number: 826 with model BasicLinearModel in generation 7 of 25
Model Number: 827 with model ConstantNaive in generation 7 of 25
Model Number: 828 with model SeasonalityMotif in generation 7 of 25
Model Number: 829 with model SeasonalityMotif in generation 7 of 25
New Generation: 8 of 25
Model Number: 830 with model SeasonalNaive in generation 8 of 25
Model Number: 831 with model FFT in generation 8 of 25
Model Number: 832 with model FBProphet in generation 8 of 25
Template Eval Error: Exception('Transformer ChangepointDetrend failed on fit from params akima {\'0\': {\'window\': \'forecast_length\'}, \'1\': {\'regression_model\': {\'model\': \'FastRidge\', \'model_params\': {}}, \'max_lags\': 1}, \'2\': {\'lag_1\': 96, \'method\': \'Mean\'}, \'3\': {\'model\': \'Gamma\', \'changepoint_spacing\': 120, \'changepoint_distance_end\': 60, \'datepart_method\': \'common_fourier\'}} with error ValueError("Some value(s) of y are out of the valid range of the loss \'HalfGammaLoss\'.")') in model 832 in generation 8: FBProphet
Model Number: 833 with model AverageValueNaive in generation 8 of 25
Model Number: 834 with model GLM in generation 8 of 25
Template Eval Error: Exception("Transformer DatepartRegression failed on fit from params ffill {'0': {'lag': 1, 'fill': 'bfill'}, '1': {'regression_model': {'model': 'ExtraTrees', 'model_params': {'n_estimators': 100, 'min_samples_leaf': 1, 'min_samples_split': 4, 'max_depth': 30, 'criterion': 'poisson', 'max_features': 1}}, 'datepart_method': 'recurring', 'polynomial_degree': None, 'transform_dict': None, 'holiday_countries_used': False, 'lags': None, 'forward_lags': None}, '2': {'whiten': False, 'n_components': None}, '3': {'discretization': 'lower', 'n_bins': 5}, '4': {'algorithm': 'parallel', 'fun': 'logcosh', 'max_iter': 250, 'whiten': 'unit-variance'}} with error ValueError('Some value(s) of y are negative which is not allowed for Poisson regression.')") in model 834 in generation 8: GLM
Model Number: 835 with model LastValueNaive in generation 8 of 25
Model Number: 836 with model ARDL in generation 8 of 25
Model Number: 837 with model AverageValueNaive in generation 8 of 25
Model Number: 838 with model GLS in generation 8 of 25
Model Number: 839 with model ETS in generation 8 of 25
Model Number: 840 with model BasicLinearModel in generation 8 of 25
Template Eval Error: Exception('Transformer FIRFilter failed on fit from params ffill {\'0\': {\'numtaps\': 32, \'cutoff_hz\': 10, \'window\': [\'exponential\', None, 0.25], \'sampling_frequency\': 24, \'on_transform\': True, \'on_inverse\': False, \'bounds_only\': False}, \'1\': {\'rows\': 84, \'lag\': 1, \'method\': \'additive\', \'strength\': 1.0, \'first_value_only\': False, \'threshold\': 10, \'threshold_method\': \'mean\'}, \'2\': {\'rows\': 1, \'lag\': 2, \'method\': \'additive\', \'strength\': 0.5, \'first_value_only\': False, \'threshold\': 3, \'threshold_method\': \'max\'}, \'3\': {\'window_size\': 364, \'alpha\': 2.5, \'grouping_forward_limit\': 4, \'max_level_shifts\': 30, \'alignment\': \'average\'}, \'4\': {\'decimals\': 0, \'on_transform\': True, \'on_inverse\': True}, \'5\': {\'method\': \'savgol_filter\', \'method_args\': {\'window_length\': 91, \'polyorder\': 4, \'deriv\': 0, \'mode\': \'mirror\'}}} with error ValueError("<class \'list\'> as window type is not supported.")') in model 840 in generation 8: BasicLinearModel
Model Number: 841 with model LastValueNaive in generation 8 of 25
Model Number: 842 with model ARDL in generation 8 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 842 in generation 8: ARDL
Model Number: 843 with model SeasonalNaive in generation 8 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.400e+10, tolerance: 5.124e+07

Model Number: 844 with model ARDL in generation 8 of 25
Template Eval Error: Exception('Transformer FIRFilter failed on fit from params ffill {\'0\': {\'numtaps\': 128, \'cutoff_hz\': 0.1, \'window\': [\'exponential\', None, 3.0], \'sampling_frequency\': 2, \'on_transform\': True, \'on_inverse\': False, \'bounds_only\': False}, \'1\': {\'n_harmonics\': 10, \'detrend\': \'linear\'}, \'2\': {}} with error ValueError("<class \'list\'> as window type is not supported.")') in model 844 in generation 8: ARDL
Model Number: 845 with model FFT in generation 8 of 25
Model Number: 846 with model SeasonalNaive in generation 8 of 25
Model Number: 847 with model UnivariateMotif in generation 8 of 25
Model Number: 848 with model GLS in generation 8 of 25
Model Number: 849 with model SeasonalityMotif in generation 8 of 25
Model Number: 850 with model FBProphet in generation 8 of 25
Model Number: 851 with model Cassandra in generation 8 of 25
Model Number: 852 with model ARDL in generation 8 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 852 in generation 8: ARDL
Model Number: 853 with model AverageValueNaive in generation 8 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 854 with model FFT in generation 8 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params rolling_mean {'0': {'rows': 4, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'threshold': 1.0, 'splash_threshold': None, 'use_dayofmonth_holidays': True, 'use_wkdom_holidays': False, 'use_wkdeom_holidays': False, 'use_lunar_holidays': False, 'use_lunar_weekday': False, 'use_islamic_holidays': False, 'use_hebrew_holidays': False, 'use_hindu_holidays': False, 'anomaly_detector_params': {'method': 'IQR', 'method_params': {'iqr_threshold': 1.5, 'iqr_quantiles': [0.4, 0.6]}, 'fillna': 'mean', 'transform_dict': None, 'isolated_only': False, 'on_inverse': False}, 'remove_excess_anomalies': True, 'impact': 'median_value', 'regression_params': {}}, '2': {'det_order': -1, 'k_ar_diff': 1}, '3': {'method': 'zscore', 'method_params': {'distribution': 'uniform', 'alpha': 0.1}, 'fillna': 'ffill', 'transform_dict': {'transformations': {'0': 'DifferencedTransformer'}, 'transformation_params': {'0': {}}}, 'isolated_only': False, 'on_inverse': True}, '4': {'n_harmonics': 10, 'detrend': 'quadratic'}, '5': {}} with error ValueError('Coint only works on multivarate series')") in model 854 in generation 8: FFT
Model Number: 855 with model FFT in generation 8 of 25
Model Number: 856 with model ARDL in generation 8 of 25
Model Number: 857 with model AverageValueNaive in generation 8 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 858 with model GLS in generation 8 of 25
Model Number: 859 with model GLM in generation 8 of 25
Model Number: 860 with model FFT in generation 8 of 25
Model Number: 861 with model AverageValueNaive in generation 8 of 25
Model Number: 862 with model ETS in generation 8 of 25
Model Number: 863 with model ETS in generation 8 of 25
Model Number: 864 with model FFT in generation 8 of 25
Model Number: 865 with model BasicLinearModel in generation 8 of 25
Model Number: 866 with model GLM in generation 8 of 25
Model Number: 867 with model MetricMotif in generation 8 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 868 with model FFT in generation 8 of 25
Model Number: 869 with model ConstantNaive in generation 8 of 25
Model Number: 870 with model ARDL in generation 8 of 25
Template Eval Error: Exception('Transformer FIRFilter failed on fit from params ffill {\'0\': {\'numtaps\': 128, \'cutoff_hz\': 0.1, \'window\': [\'exponential\', None, 3.0], \'sampling_frequency\': 2, \'on_transform\': True, \'on_inverse\': False, \'bounds_only\': False}, \'1\': {}} with error ValueError("<class \'list\'> as window type is not supported.")') in model 870 in generation 8: ARDL
Model Number: 871 with model SeasonalityMotif in generation 8 of 25
Model Number: 872 with model AverageValueNaive in generation 8 of 25
Model Number: 873 with model SeasonalityMotif in generation 8 of 25
Model Number: 874 with model SeasonalNaive in generation 8 of 25
Model Number: 875 with model LastValueNaive in generation 8 of 25
Model Number: 876 with model UnivariateMotif in generation 8 of 25
Model Number: 877 with model SectionalMotif in generation 8 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params ffill {'0': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 1}, '1': {'lag_1': 2, 'method': 'LastValue'}, '2': {}, '3': {'lag_1': 364, 'method': 'LastValue'}} with error ValueError('BTCD only works on multivarate series')") in model 877 in generation 8: SectionalMotif
Model Number: 878 with model FFT in generation 8 of 25
Model Number: 879 with model DatepartRegression in generation 8 of 25
Model Number: 880 with model SeasonalNaive in generation 8 of 25
Model Number: 881 with model Cassandra in generation 8 of 25
Model Number: 882 with model ETS in generation 8 of 25
Model Number: 883 with model MetricMotif in generation 8 of 25
Model Number: 884 with model DatepartRegression in generation 8 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 884 in generation 8: DatepartRegression
Model Number: 885 with model BasicLinearModel in generation 8 of 25
Model Number: 886 with model MetricMotif in generation 8 of 25
Model Number: 887 with model Cassandra in generation 8 of 25
Model Number: 888 with model UnivariateMotif in generation 8 of 25
Model Number: 889 with model GLS in generation 8 of 25
Model Number: 890 with model SectionalMotif in generation 8 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 891 with model Cassandra in generation 8 of 25
Model Number: 892 with model AverageValueNaive in generation 8 of 25
Model Number: 893 with model ETS in generation 8 of 25
Model Number: 894 with model DatepartRegression in generation 8 of 25
Model Number: 895 with model ARDL in generation 8 of 25
Model Number: 896 with model GLM in generation 8 of 25
Model Number: 897 with model ETS in generation 8 of 25
Model Number: 898 with model AverageValueNaive in generation 8 of 25
Model Number: 899 with model SeasonalNaive in generation 8 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

2025-07-30 00:00:00
Template Eval Error: Exception("Transformer PowerTransformer failed on inverse from params cubic {'0': {}, '1': {}, '2': {}, '3': {'model_name': 'randomly generated', 'state_transition': [[0.6254851193880471, -0.5045352462944331], [-1.2065625115981105, -0.6254696547056868]], 'process_noise': [[0.004, 0.0], [0.0, 0.019]], 'observation_model': [[1.2632121579993911, -1.7282057889665703]], 'observation_noise': 0.16033456483191233, 'em_iter': 10, 'on_transform': True, 'on_inverse': False}, '4': {'mode': 'downscale', 'factor': 4, 'down_method': 'mean', 'fill_method': 'akima'}} with ValueError('Shape of passed values is (23, 1), indices imply (30, 1)')") in model 899 in generation 8: SeasonalNaive
Model Number: 900 with model ETS in generation 8 of 25
Model Number: 901 with model UnivariateMotif in generation 8 of 25
Model Number: 902 with model AverageValueNaive in generation 8 of 25
Model Number: 903 with model FBProphet in generation 8 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 903 in generation 8: FBProphet
Model Number: 904 with model LastValueNaive in generation 8 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 905 with model Cassandra in generation 8 of 25
Model Number: 906 with model SeasonalNaive in generation 8 of 25
Model Number: 907 with model GLM in generation 8 of 25
Model Number: 908 with model GLM in generation 8 of 25
Template Eval Error: ValueError('The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.') in model 908 in generation 8: GLM
Model Number: 909 with model AverageValueNaive in generation 8 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params nearest {'0': {}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {}, '3': {'window': None}, '4': {'det_order': 0, 'k_ar_diff': 1}} with error ValueError('Coint only works on multivarate series')") in model 909 in generation 8: AverageValueNaive
Model Number: 910 with model ETS in generation 8 of 25
Model Number: 911 with model ARDL in generation 8 of 25
Template Eval Error: ValueError("ARDL series Close failed with error ValueError('integer orders must be at least 1 when causal is True.') exog train             HolidayFlag_US\nDate                      \n2023-07-23             0.0\n2023-07-24             0.0\n2023-07-25             0.0\n2023-07-26             0.0\n2023-07-27             0.0\n...                    ...\n2025-07-25             0.0\n2025-07-26             0.0\n2025-07-27             0.0\n2025-07-28             0.0\n2025-07-29             0.0\n\n[738 rows x 1 columns] and predict             HolidayFlag_US\n2025-07-30             0.0\n2025-07-31             0.0\n2025-08-01             0.0\n2025-08-02             0.0\n2025-08-03             0.0\n2025-08-04             0.0\n2025-08-05             0.0\n2025-08-06             0.0\n2025-08-07             0.0\n2025-08-08             0.0\n2025-08-09             0.0\n2025-08-10             0.0\n2025-08-11             0.0\n2025-08-12             0.0\n2025-08-13             0.0\n2025-08-14             0.0\n2025-08-15             0.0\n2025-08-16             0.0\n2025-08-17             0.0\n2025-08-18             0.0\n2025-08-19             0.0\n2025-08-20             0.0\n2025-08-21             0.0\n2025-08-22             0.0\n2025-08-23             0.0\n2025-08-24             0.0\n2025-08-25             0.0\n2025-08-26             0.0\n2025-08-27             0.0\n2025-08-28             0.0") in model 911 in generation 8: ARDL
Model Number: 912 with model SeasonalNaive in generation 8 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

invalid value encountered in log

Model Number: 913 with model FFT in generation 8 of 25
New Generation: 9 of 25
Model Number: 914 with model AverageValueNaive in generation 9 of 25
Model Number: 915 with model BasicLinearModel in generation 9 of 25
Model Number: 916 with model SeasonalNaive in generation 9 of 25
Model Number: 917 with model SeasonalNaive in generation 9 of 25
Model Number: 918 with model SectionalMotif in generation 9 of 25
Model Number: 919 with model LastValueNaive in generation 9 of 25
Model Number: 920 with model FBProphet in generation 9 of 25
Model Number: 921 with model BasicLinearModel in generation 9 of 25
Model Number: 922 with model DatepartRegression in generation 9 of 25
Model Number: 923 with model SeasonalNaive in generation 9 of 25
Model Number: 924 with model AverageValueNaive in generation 9 of 25
Model Number: 925 with model Cassandra in generation 9 of 25
Model Number: 926 with model ETS in generation 9 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 927 with model ARDL in generation 9 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 927 in generation 9: ARDL
Model Number: 928 with model GLM in generation 9 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

Model Number: 929 with model Cassandra in generation 9 of 25
Model Number: 930 with model ConstantNaive in generation 9 of 25
Model Number: 931 with model ARDL in generation 9 of 25
Model Number: 932 with model FFT in generation 9 of 25
Model Number: 933 with model SeasonalNaive in generation 9 of 25
Model Number: 934 with model GLS in generation 9 of 25
Model Number: 935 with model Cassandra in generation 9 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 935 in generation 9: Cassandra
Model Number: 936 with model GLS in generation 9 of 25
Model Number: 937 with model SeasonalNaive in generation 9 of 25
Model Number: 938 with model ETS in generation 9 of 25
Model Number: 939 with model AverageValueNaive in generation 9 of 25
Model Number: 940 with model SectionalMotif in generation 9 of 25
Model Number: 941 with model GLS in generation 9 of 25
Model Number: 942 with model ARDL in generation 9 of 25
Model Number: 943 with model AverageValueNaive in generation 9 of 25
Model Number: 944 with model DatepartRegression in generation 9 of 25
Model Number: 945 with model DatepartRegression in generation 9 of 25
Model Number: 946 with model FFT in generation 9 of 25
Model Number: 947 with model FBProphet in generation 9 of 25
Model Number: 948 with model FBProphet in generation 9 of 25
Model Number: 949 with model LastValueNaive in generation 9 of 25
Model Number: 950 with model BasicLinearModel in generation 9 of 25
Model Number: 951 with model LastValueNaive in generation 9 of 25
Model Number: 952 with model FFT in generation 9 of 25
Model Number: 953 with model UnivariateMotif in generation 9 of 25
Model Number: 954 with model RRVAR in generation 9 of 25
Model Number: 955 with model SeasonalityMotif in generation 9 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 956 with model ETS in generation 9 of 25
Model Number: 957 with model FFT in generation 9 of 25
Model Number: 958 with model BasicLinearModel in generation 9 of 25
Template Eval Error: ValueError('matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 738 is different from 2003)') in model 958 in generation 9: BasicLinearModel
Model Number: 959 with model DatepartRegression in generation 9 of 25
Model Number: 960 with model DatepartRegression in generation 9 of 25
Model Number: 961 with model LastValueNaive in generation 9 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params fake_date {'0': {'rows': 28}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {}, '3': {'det_order': 0, 'k_ar_diff': 2}, '4': {'regression_model': {'model': 'DecisionTree', 'model_params': {'max_depth': 3, 'min_samples_split': 1.0}}, 'datepart_method': 'expanded_binarized', 'polynomial_degree': None, 'transform_dict': {'fillna': None, 'transformations': {'0': 'AnomalyRemoval'}, 'transformation_params': {'0': {'method': 'zscore', 'transform_dict': {'transformations': {'0': 'DatepartRegression'}, 'transformation_params': {'0': {'datepart_method': 'simple_3', 'regression_model': {'model': 'ElasticNet', 'model_params': {}}}}}, 'method_params': {'distribution': 'uniform', 'alpha': 0.05}}}}, 'holiday_countries_used': True, 'lags': None, 'forward_lags': None}} with error ValueError('Coint only works on multivarate series')") in model 961 in generation 9: LastValueNaive
Model Number: 962 with model DatepartRegression in generation 9 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning:

Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 963 with model ARDL in generation 9 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 963 in generation 9: ARDL
Model Number: 964 with model MetricMotif in generation 9 of 25
Model Number: 965 with model BasicLinearModel in generation 9 of 25
Template Eval Error: ValueError('matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 738 is different from 2003)') in model 965 in generation 9: BasicLinearModel
Model Number: 966 with model BasicLinearModel in generation 9 of 25
Model Number: 967 with model ARDL in generation 9 of 25
Model Number: 968 with model SeasonalNaive in generation 9 of 25
Model Number: 969 with model Cassandra in generation 9 of 25
Model Number: 970 with model DatepartRegression in generation 9 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 970 in generation 9: DatepartRegression
Model Number: 971 with model GLM in generation 9 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 972 with model SeasonalNaive in generation 9 of 25
Model Number: 973 with model Cassandra in generation 9 of 25
Model Number: 974 with model Cassandra in generation 9 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning:

invalid value encountered in divide

Model Number: 975 with model BasicLinearModel in generation 9 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params linear {'0': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gblinear', 'max_depth': 6, 'eta': 0.01, 'min_child_weight': 1, 'subsample': 1, 'colsample_bylevel': 0.7, 'reg_alpha': 0.001, 'reg_lambda': 1, 'n_estimators': 100, 'multi_strategy': 'multi_output_tree', 'tree_method': 'hist'}, 'datepart_method': 'simple_binarized'}, 'fillna': 'linear'}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 975 in generation 9: BasicLinearModel
Model Number: 976 with model Cassandra in generation 9 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_base.py:172: RuntimeWarning:

overflow encountered in square

/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

2025-07-30 00:00:00
2025-07-30 00:00:00
2025-07-30 00:00:00
Template Eval Error: ValueError('Model WindowRegression returned improper forecast_length. Returned: 23 and requested: 30') in model 976 in generation 9: Cassandra
Model Number: 977 with model GLM in generation 9 of 25
Template Eval Error: Exception("Transformer HolidayTransformer failed on fit from params ffill {'0': {'low': 6, 'high': 32, 'K': 1, 'lanczos_factor': False, 'return_diff': True, 'on_transform': True, 'on_inverse': False}, '1': {'threshold': 0.8, 'splash_threshold': None, 'use_dayofmonth_holidays': True, 'use_wkdom_holidays': True, 'use_wkdeom_holidays': False, 'use_lunar_holidays': True, 'use_lunar_weekday': False, 'use_islamic_holidays': False, 'use_hebrew_holidays': False, 'use_hindu_holidays': False, 'anomaly_detector_params': {'method': 'IQR', 'method_params': {'iqr_threshold': 2.5, 'iqr_quantiles': [0.25, 0.75]}, 'fillna': 'rolling_mean_24', 'transform_dict': {'transformations': {'0': 'DatepartRegression'}, 'transformation_params': {'0': {'datepart_method': 'simple_3', 'regression_model': {'model': 'DecisionTree', 'model_params': {'max_depth': None, 'min_samples_split': 0.1}}}}}, 'isolated_only': False, 'on_inverse': False}, 'remove_excess_anomalies': True, 'impact': 'datepart_regression', 'regression_params': {'regression_model': {'model': 'MLP', 'model_params': {'hidden_layer_sizes': [72, 36, 72], 'max_iter': 250, 'activation': 'relu', 'solver': 'sgd', 'early_stopping': False, 'learning_rate_init': 0.001, 'alpha': 0.0001}}, 'datepart_method': 'recurring', 'polynomial_degree': 2, 'transform_dict': None, 'holiday_countries_used': False, 'lags': None, 'forward_lags': None}}, '2': {'lag_1': 28, 'method': 20}, '3': {'rows': 5}} with error ValueError('Solver produced non-finite parameter weights. The input data may contain large values and need to be preprocessed.')") in model 977 in generation 9: GLM
Model Number: 978 with model GLS in generation 9 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning:

Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 979 with model GLM in generation 9 of 25
Model Number: 980 with model ETS in generation 9 of 25
Model Number: 981 with model ARDL in generation 9 of 25
Model Number: 982 with model FFT in generation 9 of 25
Model Number: 983 with model Cassandra in generation 9 of 25
Model Number: 984 with model FBProphet in generation 9 of 25
Template Eval Error: Exception('Transformer DatepartRegression failed on fit from params ffill {\'0\': {\'window\': \'forecast_length\'}, \'1\': {\'det_order\': 1, \'k_ar_diff\': 2}, \'2\': {}, \'3\': {\'rows\': 1, \'lag\': 7, \'method\': \'multiplicative\', \'strength\': 1.0, \'first_value_only\': False, \'threshold\': 10, \'threshold_method\': \'max\'}, \'4\': {\'rows\': 168, \'lag\': 7, \'method\': \'multiplicative\', \'strength\': 0.7, \'first_value_only\': True, \'threshold\': 10, \'threshold_method\': \'max\'}, \'5\': {\'regression_model\': {\'model\': \'MLP\', \'model_params\': {\'hidden_layer_sizes\': [32, 32, 32], \'max_iter\': 500, \'activation\': \'identity\', \'solver\': \'adam\', \'early_stopping\': True, \'learning_rate_init\': 0.001, \'alpha\': None}}, \'datepart_method\': \'common_fourier\', \'polynomial_degree\': None, \'transform_dict\': None, \'holiday_countries_used\': False, \'lags\': None, \'forward_lags\': None}} with error InvalidParameterError("The \'alpha\' parameter of MLPRegressor must be a float in the range [0.0, inf). Got None instead.")') in model 984 in generation 9: FBProphet
Model Number: 985 with model AverageValueNaive in generation 9 of 25
Model Number: 986 with model ARDL in generation 9 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 987 with model GLM in generation 9 of 25
Model Number: 988 with model ARDL in generation 9 of 25
Model Number: 989 with model ARDL in generation 9 of 25
Model Number: 990 with model SeasonalityMotif in generation 9 of 25
Model Number: 991 with model FFT in generation 9 of 25
Model Number: 992 with model BasicLinearModel in generation 9 of 25
Model Number: 993 with model FFT in generation 9 of 25
Model Number: 994 with model FFT in generation 9 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning:

invalid value encountered in matmul

Model Number: 995 with model ARDL in generation 9 of 25
Model Number: 996 with model UnivariateMotif in generation 9 of 25
Model Number: 997 with model AverageValueNaive in generation 9 of 25
New Generation: 10 of 25
Model Number: 998 with model FFT in generation 10 of 25
Model Number: 999 with model GLM in generation 10 of 25
Model Number: 1000 with model ARDL in generation 10 of 25
Model Number: 1001 with model FBProphet in generation 10 of 25
Model Number: 1002 with model SeasonalityMotif in generation 10 of 25
Model Number: 1003 with model SeasonalNaive in generation 10 of 25
Model Number: 1004 with model FBProphet in generation 10 of 25
Model Number: 1005 with model ARDL in generation 10 of 25
Model Number: 1006 with model FFT in generation 10 of 25
Model Number: 1007 with model GLM in generation 10 of 25
Model Number: 1008 with model FFT in generation 10 of 25
Model Number: 1009 with model ARDL in generation 10 of 25
Model Number: 1010 with model ETS in generation 10 of 25
Model Number: 1011 with model AverageValueNaive in generation 10 of 25
Model Number: 1012 with model SeasonalityMotif in generation 10 of 25
Model Number: 1013 with model SeasonalNaive in generation 10 of 25
Model Number: 1014 with model FFT in generation 10 of 25
Model Number: 1015 with model AverageValueNaive in generation 10 of 25
Model Number: 1016 with model Cassandra in generation 10 of 25
Model Number: 1017 with model FBProphet in generation 10 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1017 in generation 10: FBProphet
Model Number: 1018 with model SeasonalNaive in generation 10 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 1019 with model GLM in generation 10 of 25
Model Number: 1020 with model DatepartRegression in generation 10 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1020 in generation 10: DatepartRegression
Model Number: 1021 with model GLM in generation 10 of 25
Model Number: 1022 with model AverageValueNaive in generation 10 of 25
Model Number: 1023 with model AverageValueNaive in generation 10 of 25
Model Number: 1024 with model GLM in generation 10 of 25
Model Number: 1025 with model ETS in generation 10 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

Model Number: 1026 with model Cassandra in generation 10 of 25
Model Number: 1027 with model SeasonalNaive in generation 10 of 25

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1028 with model AverageValueNaive in generation 10 of 25
Model Number: 1029 with model GLS in generation 10 of 25
Model Number: 1030 with model Cassandra in generation 10 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 1030 in generation 10: Cassandra
Model Number: 1031 with model SeasonalNaive in generation 10 of 25
Model Number: 1032 with model FFT in generation 10 of 25
Model Number: 1033 with model Cassandra in generation 10 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1034 with model AverageValueNaive in generation 10 of 25
Model Number: 1035 with model FBProphet in generation 10 of 25

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 1036 with model ARDL in generation 10 of 25

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1037 with model FFT in generation 10 of 25
Model Number: 1038 with model Cassandra in generation 10 of 25
Cassandra transformed data is all 0.0! Adding noise...

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1039 with model ETS in generation 10 of 25
Model Number: 1040 with model Cassandra in generation 10 of 25
Template Eval Error: AttributeError("'float' object has no attribute 'shape'") in model 1040 in generation 10: Cassandra
Model Number: 1041 with model FBProphet in generation 10 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1042 with model DatepartRegression in generation 10 of 25
Model Number: 1043 with model Cassandra in generation 10 of 25
Model Number: 1044 with model Cassandra in generation 10 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1045 with model BasicLinearModel in generation 10 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1045 in generation 10: BasicLinearModel
Model Number: 1046 with model FFT in generation 10 of 25
Model Number: 1047 with model GLS in generation 10 of 25
Model Number: 1048 with model ARDL in generation 10 of 25
Model Number: 1049 with model DatepartRegression in generation 10 of 25
Model Number: 1050 with model Cassandra in generation 10 of 25
Model Number: 1051 with model BasicLinearModel in generation 10 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1052 with model AverageValueNaive in generation 10 of 25
Model Number: 1053 with model DatepartRegression in generation 10 of 25
Model Number: 1054 with model DatepartRegression in generation 10 of 25
Template Eval Error: ValueError('Number of labels=738 does not match number of samples=2003') in model 1054 in generation 10: DatepartRegression
Model Number: 1055 with model ETS in generation 10 of 25
Model Number: 1056 with model AverageValueNaive in generation 10 of 25
Model Number: 1057 with model FBProphet in generation 10 of 25
Model Number: 1058 with model AverageValueNaive in generation 10 of 25
Model Number: 1059 with model GLM in generation 10 of 25
Model Number: 1060 with model FFT in generation 10 of 25
New Generation: 11 of 25
Model Number: 1061 with model ETS in generation 11 of 25
Model Number: 1062 with model ETS in generation 11 of 25
Model Number: 1063 with model BasicLinearModel in generation 11 of 25
Model Number: 1064 with model BasicLinearModel in generation 11 of 25
Model Number: 1065 with model ARDL in generation 11 of 25
Model Number: 1066 with model DatepartRegression in generation 11 of 25
Template Eval Error: IndexError('tuple index out of range') in model 1066 in generation 11: DatepartRegression
Model Number: 1067 with model FFT in generation 11 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params fake_date {'0': {'rows': 1}, '1': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 2}, '2': {}} with error ValueError('BTCD only works on multivarate series')") in model 1067 in generation 11: FFT
Model Number: 1068 with model GLS in generation 11 of 25
Model Number: 1069 with model ETS in generation 11 of 25
Model Number: 1070 with model Cassandra in generation 11 of 25
Model Number: 1071 with model BasicLinearModel in generation 11 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1072 with model FFT in generation 11 of 25
Model Number: 1073 with model Cassandra in generation 11 of 25
Model Number: 1074 with model ETS in generation 11 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1075 with model GLS in generation 11 of 25
Model Number: 1076 with model FBProphet in generation 11 of 25

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 1077 with model Cassandra in generation 11 of 25
Model Number: 1078 with model ETS in generation 11 of 25
Model Number: 1079 with model GLS in generation 11 of 25
Model Number: 1080 with model FFT in generation 11 of 25
Model Number: 1081 with model Cassandra in generation 11 of 25
Model Number: 1082 with model GLM in generation 11 of 25
Template Eval Error: ValueError('The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.') in model 1082 in generation 11: GLM
Model Number: 1083 with model AverageValueNaive in generation 11 of 25
Model Number: 1084 with model BasicLinearModel in generation 11 of 25
Template Eval Error: ValueError('matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 738 is different from 2003)') in model 1084 in generation 11: BasicLinearModel
Model Number: 1085 with model Cassandra in generation 11 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

invalid value encountered in log

Model Number: 1086 with model LastValueNaive in generation 11 of 25
Model Number: 1087 with model SectionalMotif in generation 11 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1087 in generation 11: SectionalMotif
Model Number: 1088 with model GLS in generation 11 of 25
Model Number: 1089 with model SeasonalityMotif in generation 11 of 25
Model Number: 1090 with model ARDL in generation 11 of 25
Model Number: 1091 with model AverageValueNaive in generation 11 of 25
Model Number: 1092 with model GLS in generation 11 of 25
Model Number: 1093 with model GLM in generation 11 of 25
Model Number: 1094 with model SeasonalNaive in generation 11 of 25
Model Number: 1095 with model SeasonalNaive in generation 11 of 25
Model Number: 1096 with model ARDL in generation 11 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 1096 in generation 11: ARDL
Model Number: 1097 with model ARDL in generation 11 of 25
Model Number: 1098 with model GLM in generation 11 of 25
Model Number: 1099 with model FFT in generation 11 of 25
Model Number: 1100 with model UnivariateMotif in generation 11 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 1101 with model AverageValueNaive in generation 11 of 25
Model Number: 1102 with model SeasonalNaive in generation 11 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params rolling_mean_24 {'0': {'det_order': -1, 'k_ar_diff': 1}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {'method': 'clip', 'std_threshold': 2, 'fillna': None}} with error ValueError('Coint only works on multivarate series')") in model 1102 in generation 11: SeasonalNaive
Model Number: 1103 with model SeasonalNaive in generation 11 of 25
Model Number: 1104 with model FBProphet in generation 11 of 25
Model Number: 1105 with model AverageValueNaive in generation 11 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params mean {'0': {}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {'det_order': 0, 'k_ar_diff': 2}, '3': {}} with error ValueError('Coint only works on multivarate series')") in model 1105 in generation 11: AverageValueNaive
Model Number: 1106 with model GLS in generation 11 of 25
Model Number: 1107 with model UnivariateMotif in generation 11 of 25
Model Number: 1108 with model RRVAR in generation 11 of 25
Model Number: 1109 with model AverageValueNaive in generation 11 of 25
Model Number: 1110 with model GLM in generation 11 of 25
Model Number: 1111 with model FBProphet in generation 11 of 25
Model Number: 1112 with model FFT in generation 11 of 25
Model Number: 1113 with model FFT in generation 11 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params fake_date {'0': {}, '1': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 2}} with error ValueError('BTCD only works on multivarate series')") in model 1113 in generation 11: FFT
Model Number: 1114 with model BasicLinearModel in generation 11 of 25
2025-07-30 00:00:00
2025-07-30 00:00:00
2025-07-30 00:00:00
Template Eval Error: ValueError('Model BasicLinearModel returned improper forecast_length. Returned: 29 and requested: 30') in model 1114 in generation 11: BasicLinearModel
Model Number: 1115 with model SeasonalNaive in generation 11 of 25

/usr/local/lib/python3.12/dist-packages/autots/models/basics.py:3647: RuntimeWarning:

invalid value encountered in sqrt

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.400e+10, tolerance: 5.124e+07

Model Number: 1116 with model Cassandra in generation 11 of 25
Model Number: 1117 with model AverageValueNaive in generation 11 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1118 with model SeasonalNaive in generation 11 of 25
Model Number: 1119 with model ETS in generation 11 of 25
Model Number: 1120 with model SeasonalNaive in generation 11 of 25
Model Number: 1121 with model AverageValueNaive in generation 11 of 25
Model Number: 1122 with model ARDL in generation 11 of 25
Model Number: 1123 with model FFT in generation 11 of 25
New Generation: 12 of 25
Model Number: 1124 with model FFT in generation 12 of 25
Model Number: 1125 with model ARDL in generation 12 of 25
Model Number: 1126 with model UnivariateMotif in generation 12 of 25
Model Number: 1127 with model FFT in generation 12 of 25
Model Number: 1128 with model GLS in generation 12 of 25
Model Number: 1129 with model FBProphet in generation 12 of 25
Model Number: 1130 with model BasicLinearModel in generation 12 of 25
Model Number: 1131 with model Cassandra in generation 12 of 25
2025-07-30 00:00:00
Template Eval Error: Exception("Transformer MaxAbsScaler failed on inverse from params cubic {'0': {}, '1': {'rows': 1, 'lag': 1, 'method': 'multiplicative', 'strength': 0.9, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '2': {'mode': 'downscale', 'factor': 4, 'down_method': 'decimate', 'fill_method': 'linear'}, '3': {'fixed': True, 'window': 4, 'macro_micro': False, 'center': True}} with ValueError('Shape of passed values is (28, 1), indices imply (30, 1)')") in model 1131 in generation 12: Cassandra
Model Number: 1132 with model AverageValueNaive in generation 12 of 25
Model Number: 1133 with model SeasonalNaive in generation 12 of 25
Model Number: 1134 with model SectionalMotif in generation 12 of 25
Model Number: 1135 with model SeasonalNaive in generation 12 of 25
Model Number: 1136 with model Cassandra in generation 12 of 25
Model Number: 1137 with model UnivariateMotif in generation 12 of 25
Model Number: 1138 with model GLS in generation 12 of 25
Model Number: 1139 with model SeasonalityMotif in generation 12 of 25
Model Number: 1140 with model Cassandra in generation 12 of 25
Model Number: 1141 with model Cassandra in generation 12 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1142 with model SeasonalityMotif in generation 12 of 25
Model Number: 1143 with model FFT in generation 12 of 25
Model Number: 1144 with model SeasonalNaive in generation 12 of 25
Model Number: 1145 with model FBProphet in generation 12 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1145 in generation 12: FBProphet
Model Number: 1146 with model Cassandra in generation 12 of 25

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.44489e-25): result may not be accurate.

Model Number: 1147 with model SeasonalityMotif in generation 12 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1148 with model DatepartRegression in generation 12 of 25
Template Eval Error: IndexError('tuple index out of range') in model 1148 in generation 12: DatepartRegression
Model Number: 1149 with model FFT in generation 12 of 25
Model Number: 1150 with model FFT in generation 12 of 25
Model Number: 1151 with model GLS in generation 12 of 25
Model Number: 1152 with model ETS in generation 12 of 25
Model Number: 1153 with model AverageValueNaive in generation 12 of 25
Model Number: 1154 with model FBProphet in generation 12 of 25
Model Number: 1155 with model GLM in generation 12 of 25
Model Number: 1156 with model BasicLinearModel in generation 12 of 25
Model Number: 1157 with model BasicLinearModel in generation 12 of 25
Model Number: 1158 with model BasicLinearModel in generation 12 of 25
Model Number: 1159 with model ETS in generation 12 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params fake_date {'0': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 1}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {'rows': 1, 'lag': 7, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': None, 'threshold_method': 'max'}} with error ValueError('BTCD only works on multivarate series')") in model 1159 in generation 12: ETS
Model Number: 1160 with model DatepartRegression in generation 12 of 25
Model Number: 1161 with model SeasonalNaive in generation 12 of 25
Model Number: 1162 with model BasicLinearModel in generation 12 of 25
Model Number: 1163 with model SeasonalNaive in generation 12 of 25
Model Number: 1164 with model Cassandra in generation 12 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1165 with model Cassandra in generation 12 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 1165 in generation 12: Cassandra
Model Number: 1166 with model BasicLinearModel in generation 12 of 25
Model Number: 1167 with model SeasonalNaive in generation 12 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params zero {'0': {}, '1': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gbtree', 'max_depth': 6, 'eta': 0.03, 'min_child_weight': 0.5, 'subsample': 0.7, 'colsample_bylevel': 0.5, 'reg_alpha': 0.001, 'reg_lambda': 0.2, 'n_estimators': 100, 'grow_policy': 'lossguide'}, 'datepart_method': 'expanded_binarized'}, 'fillna': 'pchip'}, '2': {'rows': 84, 'lag': 84, 'method': 'additive', 'strength': 0.5, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}, '3': {'lag': 7, 'fill': 'bfill'}, '4': {'rows': 7, 'lag': 7, 'method': 'additive', 'strength': 0.2, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 1167 in generation 12: SeasonalNaive
Model Number: 1168 with model Cassandra in generation 12 of 25
Model Number: 1169 with model GLS in generation 12 of 25
Model Number: 1170 with model AverageValueNaive in generation 12 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1171 with model Cassandra in generation 12 of 25
Model Number: 1172 with model FFT in generation 12 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1173 with model ARDL in generation 12 of 25
Model Number: 1174 with model GLS in generation 12 of 25
Model Number: 1175 with model Cassandra in generation 12 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params fake_date {'0': {}, '1': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 1}, '2': {}, '3': {'numtaps': 4, 'cutoff_hz': 50, 'window': ['exponential', None, 3.0], 'sampling_frequency': 2, 'on_transform': False, 'on_inverse': True, 'bounds_only': False}} with error ValueError('BTCD only works on multivarate series')") in model 1175 in generation 12: Cassandra
Model Number: 1176 with model GLS in generation 12 of 25
Model Number: 1177 with model AverageValueNaive in generation 12 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1178 with model FFT in generation 12 of 25
Model Number: 1179 with model DatepartRegression in generation 12 of 25
Model Number: 1180 with model AverageValueNaive in generation 12 of 25
Model Number: 1181 with model ARDL in generation 12 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 1182 with model ETS in generation 12 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1183 with model Cassandra in generation 12 of 25
Model Number: 1184 with model AverageValueNaive in generation 12 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1185 with model DatepartRegression in generation 12 of 25
Model Number: 1186 with model FFT in generation 12 of 25
New Generation: 13 of 25
Model Number: 1187 with model ETS in generation 13 of 25
Model Number: 1188 with model ETS in generation 13 of 25
Model Number: 1189 with model SeasonalityMotif in generation 13 of 25
Template Eval Error: Exception("Transformer RobustScaler failed on fit from params ffill {'0': {'low': 6, 'high': 364, 'K': 1, 'lanczos_factor': False, 'return_diff': False, 'on_transform': True, 'on_inverse': False}, '1': {'part': 'trend', 'lamb': 4}, '2': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 3, 'threshold_method': 'max'}, '3': {'lag_1': 2, 'method': 'LastValue'}, '4': {}} with error ValueError('Shape of passed values is (736, 1), indices imply (738, 1)')") in model 1189 in generation 13: SeasonalityMotif
Model Number: 1190 with model BasicLinearModel in generation 13 of 25
Template Eval Error: LinAlgError('SVD did not converge') in model 1190 in generation 13: BasicLinearModel
Model Number: 1191 with model GLS in generation 13 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1192 with model ARDL in generation 13 of 25
Model Number: 1193 with model FFT in generation 13 of 25
Model Number: 1194 with model GLS in generation 13 of 25
Model Number: 1195 with model BasicLinearModel in generation 13 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1195 in generation 13: BasicLinearModel
Model Number: 1196 with model AverageValueNaive in generation 13 of 25
Model Number: 1197 with model ETS in generation 13 of 25
Model Number: 1198 with model ETS in generation 13 of 25
Model Number: 1199 with model GLM in generation 13 of 25
Model Number: 1200 with model SeasonalNaive in generation 13 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 1201 with model AverageValueNaive in generation 13 of 25
Model Number: 1202 with model ETS in generation 13 of 25
Model Number: 1203 with model ETS in generation 13 of 25
Model Number: 1204 with model ARDL in generation 13 of 25
Model Number: 1205 with model SeasonalNaive in generation 13 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.400e+10, tolerance: 5.124e+07

Model Number: 1206 with model FFT in generation 13 of 25
Model Number: 1207 with model ARDL in generation 13 of 25
Model Number: 1208 with model SeasonalNaive in generation 13 of 25
Model Number: 1209 with model GLS in generation 13 of 25
Model Number: 1210 with model AverageValueNaive in generation 13 of 25
Model Number: 1211 with model SeasonalNaive in generation 13 of 25
Model Number: 1212 with model ARDL in generation 13 of 25
Model Number: 1213 with model Cassandra in generation 13 of 25
Model Number: 1214 with model AverageValueNaive in generation 13 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1215 with model Cassandra in generation 13 of 25
Model Number: 1216 with model FFT in generation 13 of 25
Model Number: 1217 with model AverageValueNaive in generation 13 of 25
Model Number: 1218 with model SeasonalityMotif in generation 13 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1219 with model SeasonalNaive in generation 13 of 25
Model Number: 1220 with model UnivariateMotif in generation 13 of 25
Model Number: 1221 with model AverageValueNaive in generation 13 of 25
Model Number: 1222 with model DatepartRegression in generation 13 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1222 in generation 13: DatepartRegression
Model Number: 1223 with model SectionalMotif in generation 13 of 25
Model Number: 1224 with model Cassandra in generation 13 of 25
Model Number: 1225 with model AverageValueNaive in generation 13 of 25
Model Number: 1226 with model ARDL in generation 13 of 25
Model Number: 1227 with model FFT in generation 13 of 25
Model Number: 1228 with model ARDL in generation 13 of 25
Model Number: 1229 with model Cassandra in generation 13 of 25
Model Number: 1230 with model SeasonalityMotif in generation 13 of 25
Model Number: 1231 with model FFT in generation 13 of 25
Model Number: 1232 with model Cassandra in generation 13 of 25
Model Number: 1233 with model SeasonalNaive in generation 13 of 25
Model Number: 1234 with model ARDL in generation 13 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1235 with model Cassandra in generation 13 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.44489e-25): result may not be accurate.

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 1236 with model AverageValueNaive in generation 13 of 25
Model Number: 1237 with model SeasonalNaive in generation 13 of 25
Model Number: 1238 with model FBProphet in generation 13 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1238 in generation 13: FBProphet
Model Number: 1239 with model FFT in generation 13 of 25
Model Number: 1240 with model DatepartRegression in generation 13 of 25
Model Number: 1241 with model Cassandra in generation 13 of 25
Model Number: 1242 with model GLS in generation 13 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1243 with model ARDL in generation 13 of 25
Model Number: 1244 with model BasicLinearModel in generation 13 of 25
Model Number: 1245 with model SeasonalNaive in generation 13 of 25
Model Number: 1246 with model ARDL in generation 13 of 25
Model Number: 1247 with model FFT in generation 13 of 25
Model Number: 1248 with model FFT in generation 13 of 25
Model Number: 1249 with model AverageValueNaive in generation 13 of 25
New Generation: 14 of 25
Model Number: 1250 with model FBProphet in generation 14 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params ffill {'0': {}, '1': {}, '2': {}, '3': {'rows': 168, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '4': {'det_order': -1, 'k_ar_diff': 0}} with error ValueError('Coint only works on multivarate series')") in model 1250 in generation 14: FBProphet
Model Number: 1251 with model GLM in generation 14 of 25
Template Eval Error: ValueError('The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.') in model 1251 in generation 14: GLM
Model Number: 1252 with model ARDL in generation 14 of 25
Model Number: 1253 with model FBProphet in generation 14 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

invalid value encountered in log

Model Number: 1254 with model UnivariateMotif in generation 14 of 25
Model Number: 1255 with model SeasonalNaive in generation 14 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.400e+10, tolerance: 5.124e+07

Model Number: 1256 with model ARDL in generation 14 of 25
Model Number: 1257 with model GLM in generation 14 of 25
Template Eval Error: ValueError('regression_type=user and no future_regressor passed') in model 1257 in generation 14: GLM
Model Number: 1258 with model GLS in generation 14 of 25
Model Number: 1259 with model AverageValueNaive in generation 14 of 25
Model Number: 1260 with model AverageValueNaive in generation 14 of 25
Model Number: 1261 with model GLS in generation 14 of 25
Model Number: 1262 with model BasicLinearModel in generation 14 of 25
Model Number: 1263 with model SeasonalNaive in generation 14 of 25
Model Number: 1264 with model FFT in generation 14 of 25
Model Number: 1265 with model FFT in generation 14 of 25
Model Number: 1266 with model FFT in generation 14 of 25
Model Number: 1267 with model SeasonalityMotif in generation 14 of 25
Model Number: 1268 with model DatepartRegression in generation 14 of 25
Model Number: 1269 with model Cassandra in generation 14 of 25
Model Number: 1270 with model ARDL in generation 14 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 1271 with model DatepartRegression in generation 14 of 25
Template Eval Error: IndexError('tuple index out of range') in model 1271 in generation 14: DatepartRegression
Model Number: 1272 with model ETS in generation 14 of 25
Model Number: 1273 with model ARDL in generation 14 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 1274 with model Cassandra in generation 14 of 25
Model Number: 1275 with model ETS in generation 14 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1276 with model ETS in generation 14 of 25
Model Number: 1277 with model BasicLinearModel in generation 14 of 25
Model Number: 1278 with model Cassandra in generation 14 of 25
Model Number: 1279 with model SeasonalityMotif in generation 14 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1280 with model SeasonalNaive in generation 14 of 25
Model Number: 1281 with model AverageValueNaive in generation 14 of 25
Model Number: 1282 with model FBProphet in generation 14 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/thresholding.py:204: RuntimeWarning:

overflow encountered in scalar power

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 1283 with model GLS in generation 14 of 25
Model Number: 1284 with model UnivariateMotif in generation 14 of 25
Model Number: 1285 with model FFT in generation 14 of 25
Model Number: 1286 with model UnivariateMotif in generation 14 of 25
Model Number: 1287 with model Cassandra in generation 14 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1288 with model FBProphet in generation 14 of 25
Model Number: 1289 with model ARDL in generation 14 of 25
Model Number: 1290 with model DatepartRegression in generation 14 of 25
Model Number: 1291 with model GLM in generation 14 of 25
Model Number: 1292 with model DatepartRegression in generation 14 of 25
Model Number: 1293 with model GLS in generation 14 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

Model Number: 1294 with model BasicLinearModel in generation 14 of 25
Model Number: 1295 with model FFT in generation 14 of 25
Model Number: 1296 with model Cassandra in generation 14 of 25
Template Eval Error: ValueError('Only gave one variable to VAR') in model 1296 in generation 14: Cassandra
Model Number: 1297 with model GLS in generation 14 of 25
Model Number: 1298 with model SeasonalNaive in generation 14 of 25
Model Number: 1299 with model AverageValueNaive in generation 14 of 25
Model Number: 1300 with model SeasonalNaive in generation 14 of 25
Model Number: 1301 with model SeasonalNaive in generation 14 of 25
Model Number: 1302 with model FFT in generation 14 of 25
Model Number: 1303 with model BasicLinearModel in generation 14 of 25
Template Eval Error: Exception("Transformer Detrend failed on fit from params ffill {'0': {'window_size': 30, 'alpha': 4.0, 'grouping_forward_limit': 4, 'max_level_shifts': 3, 'alignment': 'average'}, '1': {'algorithm': 'deflation', 'fun': 'logcosh', 'max_iter': 500, 'whiten': 'arbitrary-variance'}, '2': {'rows': 1, 'lag': 2, 'method': 'additive', 'strength': 1.0, 'first_value_only': True, 'threshold': None, 'threshold_method': 'mean'}, '3': {'model': 'Tweedie', 'phi': 0.999, 'window': 90, 'transform_dict': {'fillna': None, 'transformations': {'0': 'EWMAFilter'}, 'transformation_params': {'0': {'span': 2}}}}} with error ValueError('Found input variables with inconsistent numbers of samples: [90, 738]')") in model 1303 in generation 14: BasicLinearModel
Model Number: 1304 with model FFT in generation 14 of 25
Model Number: 1305 with model ARDL in generation 14 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params fake_date {'0': {'method': 'rolling_zscore', 'method_params': {'distribution': 'laplace', 'alpha': 0.1, 'rolling_periods': 90, 'center': True}, 'fillna': 'rolling_mean_24', 'transform_dict': {'transformations': {'0': 'DatepartRegression'}, 'transformation_params': {'0': {'datepart_method': 'simple_3', 'regression_model': {'model': 'DecisionTree', 'model_params': {'max_depth': None, 'min_samples_split': 0.1}}}}}, 'isolated_only': False, 'on_inverse': False}, '1': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 2}, '2': {'discretization': 'sklearn-quantile', 'n_bins': 10}, '3': {}} with error ValueError('BTCD only works on multivarate series')") in model 1305 in generation 14: ARDL
Model Number: 1306 with model RRVAR in generation 14 of 25
Model Number: 1307 with model FBProphet in generation 14 of 25
Model Number: 1308 with model BasicLinearModel in generation 14 of 25
Model Number: 1309 with model AverageValueNaive in generation 14 of 25
Model Number: 1310 with model SectionalMotif in generation 14 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.577e+11, tolerance: 3.919e+08

Model Number: 1311 with model SeasonalNaive in generation 14 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.400e+10, tolerance: 5.124e+07

Model Number: 1312 with model Cassandra in generation 14 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

New Generation: 15 of 25
Model Number: 1313 with model ETS in generation 15 of 25
Model Number: 1314 with model GLS in generation 15 of 25
Model Number: 1315 with model SeasonalNaive in generation 15 of 25
Model Number: 1316 with model AverageValueNaive in generation 15 of 25
Model Number: 1317 with model SeasonalNaive in generation 15 of 25
Model Number: 1318 with model Cassandra in generation 15 of 25

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1319 with model ETS in generation 15 of 25
Model Number: 1320 with model FFT in generation 15 of 25
Model Number: 1321 with model GLS in generation 15 of 25
Model Number: 1322 with model ETS in generation 15 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1323 with model ARDL in generation 15 of 25
Model Number: 1324 with model ARDL in generation 15 of 25
Model Number: 1325 with model AverageValueNaive in generation 15 of 25
Model Number: 1326 with model DatepartRegression in generation 15 of 25
Template Eval Error: InvalidParameterError("The 'alpha' parameter of MLPRegressor must be a float in the range [0.0, inf). Got None instead.") in model 1326 in generation 15: DatepartRegression
Model Number: 1327 with model BasicLinearModel in generation 15 of 25
Template Eval Error: ValueError('matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 738 is different from 2003)') in model 1327 in generation 15: BasicLinearModel
Model Number: 1328 with model UnivariateMotif in generation 15 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Template Eval Error: Exception('Transformer HolidayTransformer failed on fit from params ffill_mean_biased {\'0\': {\'method\': \'savgol_filter\', \'method_args\': {\'window_length\': 7, \'polyorder\': 4, \'deriv\': 0, \'mode\': \'mirror\'}}, \'1\': {\'n_harmonics\': 10, \'detrend\': \'linear\'}, \'2\': {}, \'3\': {\'threshold\': 0.7, \'splash_threshold\': None, \'use_dayofmonth_holidays\': True, \'use_wkdom_holidays\': True, \'use_wkdeom_holidays\': False, \'use_lunar_holidays\': False, \'use_lunar_weekday\': False, \'use_islamic_holidays\': False, \'use_hebrew_holidays\': True, \'use_hindu_holidays\': False, \'anomaly_detector_params\': {\'method\': \'rolling_zscore\', \'method_params\': {\'distribution\': \'uniform\', \'alpha\': 0.05, \'rolling_periods\': 90, \'center\': False}, \'fillna\': \'ffill\', \'transform_dict\': None, \'isolated_only\': False, \'on_inverse\': False}, \'remove_excess_anomalies\': True, \'impact\': \'datepart_regression\', \'regression_params\': {\'regression_model\': {\'model\': \'MLP\', \'model_params\': {\'hidden_layer_sizes\': [25, 15, 25], \'max_iter\': 250, \'activation\': \'tanh\', \'solver\': \'adam\', \'early_stopping\': False, \'learning_rate_init\': 0.001, \'alpha\': None}}, \'datepart_method\': [52, \'quarter\'], \'polynomial_degree\': None, \'transform_dict\': None, \'holiday_countries_used\': False, \'lags\': 1, \'forward_lags\': None}}} with error InvalidParameterError("The \'alpha\' parameter of MLPRegressor must be a float in the range [0.0, inf). Got None instead.")') in model 1328 in generation 15: UnivariateMotif
Model Number: 1329 with model SeasonalNaive in generation 15 of 25
Model Number: 1330 with model Cassandra in generation 15 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 1330 in generation 15: Cassandra
Model Number: 1331 with model BasicLinearModel in generation 15 of 25
Model Number: 1332 with model ARDL in generation 15 of 25

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning:

invalid value encountered in divide

Model Number: 1333 with model ETS in generation 15 of 25
Model Number: 1334 with model GLM in generation 15 of 25
Model Number: 1335 with model BasicLinearModel in generation 15 of 25
Model Number: 1336 with model Cassandra in generation 15 of 25
Model Number: 1337 with model FFT in generation 15 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1338 with model AverageValueNaive in generation 15 of 25
Model Number: 1339 with model ARDL in generation 15 of 25
Model Number: 1340 with model Cassandra in generation 15 of 25

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.44489e-25): result may not be accurate.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.54984e-25): result may not be accurate.

Model Number: 1341 with model Cassandra in generation 15 of 25

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1342 with model GLM in generation 15 of 25
Model Number: 1343 with model FFT in generation 15 of 25
Model Number: 1344 with model SeasonalityMotif in generation 15 of 25
Model Number: 1345 with model GLS in generation 15 of 25
Model Number: 1346 with model DatepartRegression in generation 15 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1347 with model SeasonalityMotif in generation 15 of 25
Model Number: 1348 with model FFT in generation 15 of 25
Model Number: 1349 with model BasicLinearModel in generation 15 of 25
Model Number: 1350 with model FFT in generation 15 of 25
Model Number: 1351 with model AverageValueNaive in generation 15 of 25
Model Number: 1352 with model FBProphet in generation 15 of 25
Model Number: 1353 with model SectionalMotif in generation 15 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1353 in generation 15: SectionalMotif
Model Number: 1354 with model SeasonalNaive in generation 15 of 25
Model Number: 1355 with model Cassandra in generation 15 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1356 with model SeasonalNaive in generation 15 of 25
Model Number: 1357 with model BasicLinearModel in generation 15 of 25
Model Number: 1358 with model Cassandra in generation 15 of 25
Model Number: 1359 with model FFT in generation 15 of 25
Model Number: 1360 with model DatepartRegression in generation 15 of 25
Model Number: 1361 with model DatepartRegression in generation 15 of 25
Model Number: 1362 with model DatepartRegression in generation 15 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1362 in generation 15: DatepartRegression
Model Number: 1363 with model FBProphet in generation 15 of 25
Model Number: 1364 with model FFT in generation 15 of 25
Model Number: 1365 with model ARDL in generation 15 of 25
Model Number: 1366 with model Cassandra in generation 15 of 25
Model Number: 1367 with model FFT in generation 15 of 25
Model Number: 1368 with model AverageValueNaive in generation 15 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1369 with model UnivariateMotif in generation 15 of 25
Model Number: 1370 with model SeasonalNaive in generation 15 of 25
Model Number: 1371 with model SeasonalNaive in generation 15 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.400e+10, tolerance: 5.124e+07

Model Number: 1372 with model Cassandra in generation 15 of 25
Model Number: 1373 with model FBProphet in generation 15 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1373 in generation 15: FBProphet
Model Number: 1374 with model AverageValueNaive in generation 15 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1375 with model SeasonalNaive in generation 15 of 25
New Generation: 16 of 25
Model Number: 1376 with model SeasonalNaive in generation 16 of 25
Model Number: 1377 with model GLM in generation 16 of 25
Template Eval Error: ValueError('The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.') in model 1377 in generation 16: GLM
Model Number: 1378 with model AverageValueNaive in generation 16 of 25
Model Number: 1379 with model BasicLinearModel in generation 16 of 25
Model Number: 1380 with model GLS in generation 16 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1406: RuntimeWarning:

invalid value encountered in log

Model Number: 1381 with model ETS in generation 16 of 25
Model Number: 1382 with model UnivariateMotif in generation 16 of 25
Model Number: 1383 with model SeasonalNaive in generation 16 of 25
Model Number: 1384 with model FFT in generation 16 of 25
Model Number: 1385 with model AverageValueNaive in generation 16 of 25
Model Number: 1386 with model AverageValueNaive in generation 16 of 25
Model Number: 1387 with model SeasonalNaive in generation 16 of 25
Model Number: 1388 with model SeasonalityMotif in generation 16 of 25
Model Number: 1389 with model UnivariateMotif in generation 16 of 25
Model Number: 1390 with model SeasonalNaive in generation 16 of 25
Model Number: 1391 with model Cassandra in generation 16 of 25
Model Number: 1392 with model ARDL in generation 16 of 25
Model Number: 1393 with model ARDL in generation 16 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1394 with model ARDL in generation 16 of 25
Template Eval Error: Exception("Transformer RobustScaler failed on fit from params rolling_mean {'0': {'method': 'IsolationForest', 'method_params': {'contamination': 0.05, 'n_estimators': 50, 'max_features': 1.0, 'bootstrap': False}, 'fillna': 'fake_date', 'transform_dict': None, 'isolated_only': False, 'on_inverse': False}, '1': {}, '2': {'cutoff': 0.2, 'reverse': False, 'on_transform': False, 'on_inverse': True}, '3': {'method': 'butter', 'method_args': {'N': 4, 'btype': 'highpass', 'analog': False, 'output': 'sos', 'Wn': 0.03571428571428571}}} with error ValueError('Shape of passed values is (701, 1), indices imply (738, 1)')") in model 1394 in generation 16: ARDL
Model Number: 1395 with model Cassandra in generation 16 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1396 with model Cassandra in generation 16 of 25
Model Number: 1397 with model ARDL in generation 16 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1398 with model GLS in generation 16 of 25
Model Number: 1399 with model Cassandra in generation 16 of 25
Model Number: 1400 with model Cassandra in generation 16 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1401 with model FBProphet in generation 16 of 25
Model Number: 1402 with model FFT in generation 16 of 25
Model Number: 1403 with model SeasonalNaive in generation 16 of 25
Model Number: 1404 with model DatepartRegression in generation 16 of 25
Epoch 1/50

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

93/93 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 22015.9219
Epoch 2/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 21933.7754
Epoch 3/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21522.2031
Epoch 4/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20496.8086
Epoch 5/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20231.2578
Epoch 6/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20228.5625
Epoch 7/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20231.7969
Epoch 8/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20229.2852
Epoch 9/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20232.2500
Epoch 10/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20230.1387
Epoch 11/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20229.2461
Epoch 12/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20229.0234
Epoch 13/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20229.2383
Epoch 14/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20228.5254
Epoch 15/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20228.8340
Epoch 16/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 20229.7949
Epoch 17/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 20230.5840
Epoch 18/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 20228.6953
Epoch 19/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20229.3574
Epoch 20/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20230.4688
Epoch 21/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20232.7988
Epoch 22/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20231.0957
Epoch 23/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20232.2305
Epoch 24/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20230.6816
Epoch 25/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20231.1055
Epoch 26/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20232.4102
Epoch 27/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20230.6582
Epoch 28/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20231.1465
Epoch 29/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20232.0488
Epoch 30/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20231.4473
Epoch 31/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20231.3359
Epoch 32/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20232.1680
Epoch 33/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20229.1367
Epoch 34/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20230.0547
Epoch 35/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20230.0664
Epoch 36/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20232.0469
Epoch 37/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20232.9121
Epoch 38/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20231.4219
Epoch 39/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 20231.7949
Epoch 40/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 20231.8105
Epoch 41/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 20231.5156
Epoch 42/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 20231.9844
Epoch 43/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 20230.4258
Epoch 44/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20230.9941
Epoch 45/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20230.0098
Epoch 46/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20230.2168
Epoch 47/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20230.7734
Epoch 48/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20231.9434
Epoch 49/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20230.2871
Epoch 50/50
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20231.2637
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step
Model Number: 1405 with model GLM in generation 16 of 25
Model Number: 1406 with model SeasonalityMotif in generation 16 of 25
Model Number: 1407 with model GLS in generation 16 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 1408 with model AverageValueNaive in generation 16 of 25
Model Number: 1409 with model SeasonalityMotif in generation 16 of 25
Model Number: 1410 with model ETS in generation 16 of 25
Model Number: 1411 with model FFT in generation 16 of 25
Model Number: 1412 with model BasicLinearModel in generation 16 of 25
Model Number: 1413 with model GLS in generation 16 of 25
Model Number: 1414 with model FBProphet in generation 16 of 25
Model Number: 1415 with model SeasonalNaive in generation 16 of 25
Model Number: 1416 with model GLS in generation 16 of 25
Model Number: 1417 with model SeasonalNaive in generation 16 of 25
Model Number: 1418 with model ARDL in generation 16 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1419 with model SeasonalNaive in generation 16 of 25
Model Number: 1420 with model GLM in generation 16 of 25
Model Number: 1421 with model FFT in generation 16 of 25
Model Number: 1422 with model ARDL in generation 16 of 25
Model Number: 1423 with model Cassandra in generation 16 of 25
Model Number: 1424 with model FBProphet in generation 16 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1425 with model FFT in generation 16 of 25
Model Number: 1426 with model ARDL in generation 16 of 25
Model Number: 1427 with model AverageValueNaive in generation 16 of 25
Model Number: 1428 with model ARDL in generation 16 of 25
Model Number: 1429 with model DatepartRegression in generation 16 of 25
Template Eval Error: ValueError('Input X contains NaN.\nElasticNet does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values') in model 1429 in generation 16: DatepartRegression
Model Number: 1430 with model AverageValueNaive in generation 16 of 25
Model Number: 1431 with model SeasonalityMotif in generation 16 of 25
Model Number: 1432 with model SectionalMotif in generation 16 of 25
Model Number: 1433 with model Cassandra in generation 16 of 25
Model Number: 1434 with model SeasonalNaive in generation 16 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1435 with model ARDL in generation 16 of 25
Model Number: 1436 with model AverageValueNaive in generation 16 of 25
Model Number: 1437 with model FFT in generation 16 of 25
Model Number: 1438 with model SeasonalityMotif in generation 16 of 25
Template Eval Error: ValueError('Model SeasonalityMotif returned NaN for one or more series. fail_on_forecast_nan=True') in model 1438 in generation 16: SeasonalityMotif
New Generation: 17 of 25

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning:

Mean of empty slice.

/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:130: RuntimeWarning:

invalid value encountered in divide

Model Number: 1439 with model Cassandra in generation 17 of 25
Model Number: 1440 with model SeasonalNaive in generation 17 of 25
Model Number: 1441 with model SeasonalNaive in generation 17 of 25
Model Number: 1442 with model SeasonalityMotif in generation 17 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1443 with model FFT in generation 17 of 25
Model Number: 1444 with model RRVAR in generation 17 of 25
Model Number: 1445 with model SeasonalityMotif in generation 17 of 25
Model Number: 1446 with model SeasonalityMotif in generation 17 of 25
Model Number: 1447 with model AverageValueNaive in generation 17 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params akima {'0': {'det_order': 0, 'k_ar_diff': 0}, '1': {'discretization': 'lower', 'n_bins': 20}} with error ValueError('Coint only works on multivarate series')") in model 1447 in generation 17: AverageValueNaive
Model Number: 1448 with model BasicLinearModel in generation 17 of 25
Model Number: 1449 with model FBProphet in generation 17 of 25
Model Number: 1450 with model GLS in generation 17 of 25
Template Eval Error: Exception("Transformer Detrend failed on fit from params ffill {'0': {'model': 'Poisson', 'phi': 1, 'window': 90, 'transform_dict': None}, '1': {}} with error ValueError('Found input variables with inconsistent numbers of samples: [90, 738]')") in model 1450 in generation 17: GLS
Model Number: 1451 with model Cassandra in generation 17 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1452 with model FBProphet in generation 17 of 25
Model Number: 1453 with model SeasonalNaive in generation 17 of 25
Model Number: 1454 with model ARDL in generation 17 of 25
Template Eval Error: Exception("Transformer RegressionFilter failed on fit from params ffill {'0': {'sigma': 1.5, 'rolling_window': 90, 'run_order': 'season_first', 'regression_params': {'regression_model': {'model': 'DecisionTree', 'model_params': {'max_depth': 9, 'min_samples_split': 1.0}}, 'datepart_method': 'simple_binarized', 'polynomial_degree': None, 'transform_dict': None, 'holiday_countries_used': True, 'lags': None, 'forward_lags': 3}, 'holiday_params': {'threshold': 0.7, 'splash_threshold': None, 'use_dayofmonth_holidays': True, 'use_wkdom_holidays': True, 'use_wkdeom_holidays': False, 'use_lunar_holidays': False, 'use_lunar_weekday': False, 'use_islamic_holidays': False, 'use_hebrew_holidays': False, 'use_hindu_holidays': False, 'anomaly_detector_params': {'method': 'med_diff', 'method_params': {'distribution': 'uniform', 'alpha': 0.2}, 'fillna': 'rolling_mean_24', 'transform_dict': {'fillna': None, 'transformations': {'0': 'ClipOutliers'}, 'transformation_params': {'0': {'method': 'clip', 'std_threshold': 6}}}, 'isolated_only': True, 'on_inverse': False}, 'remove_excess_anomalies': True, 'impact': 'datepart_regression', 'regression_params': {'regression_model': {'model': 'DecisionTree', 'model_params': {'max_depth': 9, 'min_samples_split': 1.0}}, 'datepart_method': 'simple_binarized', 'polynomial_degree': None, 'transform_dict': None, 'holiday_countries_used': True, 'lags': None, 'forward_lags': 3}}, 'trend_method': 'local_linear'}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {}, '3': {'lag_1': 28, 'method': 'LastValue'}} with error ValueError('Number of labels=738 does not match number of samples=2003')") in model 1454 in generation 17: ARDL
Model Number: 1455 with model FFT in generation 17 of 25
Model Number: 1456 with model FFT in generation 17 of 25
Model Number: 1457 with model SeasonalityMotif in generation 17 of 25
Model Number: 1458 with model GLS in generation 17 of 25
Model Number: 1459 with model Cassandra in generation 17 of 25
Model Number: 1460 with model UnivariateMotif in generation 17 of 25
Model Number: 1461 with model AverageValueNaive in generation 17 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1462 with model FFT in generation 17 of 25
Model Number: 1463 with model FFT in generation 17 of 25
Model Number: 1464 with model SeasonalNaive in generation 17 of 25
Model Number: 1465 with model ARDL in generation 17 of 25
Model Number: 1466 with model FBProphet in generation 17 of 25
2025-07-30 00:00:00
2025-07-30 00:00:00
2025-07-30 00:00:00
Template Eval Error: ValueError('Model FBProphet returned improper forecast_length. Returned: 29 and requested: 30') in model 1466 in generation 17: FBProphet
Model Number: 1467 with model BasicLinearModel in generation 17 of 25
Template Eval Error: ValueError("regression_type=='User' but no future_regressor supplied") in model 1467 in generation 17: BasicLinearModel
Model Number: 1468 with model FFT in generation 17 of 25
Model Number: 1469 with model SeasonalityMotif in generation 17 of 25
Model Number: 1470 with model AverageValueNaive in generation 17 of 25
Model Number: 1471 with model SeasonalityMotif in generation 17 of 25
Model Number: 1472 with model SectionalMotif in generation 17 of 25
Model Number: 1473 with model ETS in generation 17 of 25
Model Number: 1474 with model Cassandra in generation 17 of 25
Model Number: 1475 with model SeasonalityMotif in generation 17 of 25
Model Number: 1476 with model AverageValueNaive in generation 17 of 25
Model Number: 1477 with model ARDL in generation 17 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1478 with model SeasonalityMotif in generation 17 of 25
2025-07-30 00:00:00
Template Eval Error: Exception("Transformer MaxAbsScaler failed on inverse from params mean {'0': {}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {'mode': 'downscale', 'factor': 2, 'down_method': 'mean', 'fill_method': 'pchip'}, '3': {'lag_1': 28, 'method': 'LastValue'}} with ValueError('Shape of passed values is (28, 1), indices imply (30, 1)')") in model 1478 in generation 17: SeasonalityMotif
Model Number: 1479 with model BasicLinearModel in generation 17 of 25
Model Number: 1480 with model BasicLinearModel in generation 17 of 25
Model Number: 1481 with model ETS in generation 17 of 25
Model Number: 1482 with model GLS in generation 17 of 25
Model Number: 1483 with model DatepartRegression in generation 17 of 25
Model Number: 1484 with model DatepartRegression in generation 17 of 25
Template Eval Error: ValueError('Input X contains NaN.\nElasticNet does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values') in model 1484 in generation 17: DatepartRegression
Model Number: 1485 with model SeasonalityMotif in generation 17 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:2637: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations. Duality gap: 29839630336.0, tolerance: 52324136.0

Model Number: 1486 with model AverageValueNaive in generation 17 of 25
Model Number: 1487 with model ARDL in generation 17 of 25
Template Eval Error: Exception("Transformer RegressionFilter failed on fit from params ffill {'0': {'sigma': 1.5, 'rolling_window': 90, 'run_order': 'season_first', 'regression_params': {'regression_model': {'model': 'DecisionTree', 'model_params': {'max_depth': 9, 'min_samples_split': 1.0}}, 'datepart_method': 'simple_binarized', 'polynomial_degree': None, 'transform_dict': None, 'holiday_countries_used': True, 'lags': None, 'forward_lags': 3}, 'holiday_params': {'threshold': 0.7, 'splash_threshold': None, 'use_dayofmonth_holidays': True, 'use_wkdom_holidays': True, 'use_wkdeom_holidays': False, 'use_lunar_holidays': False, 'use_lunar_weekday': False, 'use_islamic_holidays': False, 'use_hebrew_holidays': False, 'use_hindu_holidays': False, 'anomaly_detector_params': {'method': 'med_diff', 'method_params': {'distribution': 'uniform', 'alpha': 0.2}, 'fillna': 'rolling_mean_24', 'transform_dict': {'fillna': None, 'transformations': {'0': 'ClipOutliers'}, 'transformation_params': {'0': {'method': 'clip', 'std_threshold': 6}}}, 'isolated_only': True, 'on_inverse': False}, 'remove_excess_anomalies': True, 'impact': 'datepart_regression', 'regression_params': {'regression_model': {'model': 'DecisionTree', 'model_params': {'max_depth': 9, 'min_samples_split': 1.0}}, 'datepart_method': 'simple_binarized', 'polynomial_degree': None, 'transform_dict': None, 'holiday_countries_used': True, 'lags': None, 'forward_lags': 3}}, 'trend_method': 'local_linear'}, '1': {'lag': 1, 'fill': 'bfill'}} with error ValueError('Number of labels=738 does not match number of samples=2003')") in model 1487 in generation 17: ARDL
Model Number: 1488 with model FFT in generation 17 of 25
Model Number: 1489 with model Cassandra in generation 17 of 25
Model Number: 1490 with model FFT in generation 17 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1491 with model ETS in generation 17 of 25
Model Number: 1492 with model AverageValueNaive in generation 17 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params mean {'0': {'det_order': 0, 'k_ar_diff': 0}, '1': {'discretization': 'lower', 'n_bins': 20}, '2': {'lag_1': 28, 'method': 'LastValue'}} with error ValueError('Coint only works on multivarate series')") in model 1492 in generation 17: AverageValueNaive
Model Number: 1493 with model AverageValueNaive in generation 17 of 25
Model Number: 1494 with model BasicLinearModel in generation 17 of 25
Model Number: 1495 with model ARDL in generation 17 of 25
Model Number: 1496 with model SeasonalityMotif in generation 17 of 25
Model Number: 1497 with model SeasonalNaive in generation 17 of 25
Model Number: 1498 with model ARDL in generation 17 of 25
Model Number: 1499 with model Cassandra in generation 17 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1500 with model DatepartRegression in generation 17 of 25
Model Number: 1501 with model Cassandra in generation 17 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

New Generation: 18 of 25
Model Number: 1502 with model ETS in generation 18 of 25
Model Number: 1503 with model Cassandra in generation 18 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 1503 in generation 18: Cassandra
Model Number: 1504 with model SeasonalNaive in generation 18 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1505 with model AverageValueNaive in generation 18 of 25
Model Number: 1506 with model FBProphet in generation 18 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1506 in generation 18: FBProphet
Model Number: 1507 with model FFT in generation 18 of 25
Model Number: 1508 with model SeasonalityMotif in generation 18 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1509 with model FFT in generation 18 of 25
Model Number: 1510 with model DatepartRegression in generation 18 of 25
Model Number: 1511 with model FFT in generation 18 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params zero {'0': {'n_harmonics': 20, 'detrend': 'linear'}, '1': {'det_order': 0, 'k_ar_diff': 1}, '2': {'method': 'clip', 'std_threshold': 4, 'fillna': None}, '3': {'lag_1': 7, 'method': 'Mean'}} with error ValueError('Coint only works on multivarate series')") in model 1511 in generation 18: FFT
Model Number: 1512 with model DatepartRegression in generation 18 of 25
Template Eval Error: IndexError('tuple index out of range') in model 1512 in generation 18: DatepartRegression
Model Number: 1513 with model Cassandra in generation 18 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 1513 in generation 18: Cassandra
Model Number: 1514 with model Cassandra in generation 18 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/decomposition/_fastica.py:592: UserWarning:

Ignoring n_components with whiten=False.

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.44489e-25): result may not be accurate.

Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 1514 in generation 18: Cassandra
Model Number: 1515 with model ETS in generation 18 of 25
Model Number: 1516 with model DatepartRegression in generation 18 of 25
Template Eval Error: ValueError('Input X contains NaN.\nElasticNet does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values') in model 1516 in generation 18: DatepartRegression
Model Number: 1517 with model SeasonalNaive in generation 18 of 25
Model Number: 1518 with model AverageValueNaive in generation 18 of 25
Model Number: 1519 with model FFT in generation 18 of 25
Model Number: 1520 with model SeasonalNaive in generation 18 of 25
Model Number: 1521 with model BasicLinearModel in generation 18 of 25
Model Number: 1522 with model ARDL in generation 18 of 25
Model Number: 1523 with model SeasonalityMotif in generation 18 of 25
Model Number: 1524 with model Cassandra in generation 18 of 25
Model Number: 1525 with model FFT in generation 18 of 25
Model Number: 1526 with model SeasonalityMotif in generation 18 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1527 with model DatepartRegression in generation 18 of 25
Model Number: 1528 with model ARDL in generation 18 of 25
Model Number: 1529 with model GLS in generation 18 of 25
Model Number: 1530 with model ARDL in generation 18 of 25
Model Number: 1531 with model BasicLinearModel in generation 18 of 25
Model Number: 1532 with model ETS in generation 18 of 25
Model Number: 1533 with model ETS in generation 18 of 25
Model Number: 1534 with model AverageValueNaive in generation 18 of 25
Model Number: 1535 with model BasicLinearModel in generation 18 of 25
Model Number: 1536 with model ARDL in generation 18 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 1536 in generation 18: ARDL
Model Number: 1537 with model SeasonalityMotif in generation 18 of 25
Model Number: 1538 with model BasicLinearModel in generation 18 of 25
Model Number: 1539 with model AverageValueNaive in generation 18 of 25
Model Number: 1540 with model BasicLinearModel in generation 18 of 25
Model Number: 1541 with model GLM in generation 18 of 25
Model Number: 1542 with model GLS in generation 18 of 25
Model Number: 1543 with model AverageValueNaive in generation 18 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 1544 with model DatepartRegression in generation 18 of 25
Model Number: 1545 with model Cassandra in generation 18 of 25
Model Number: 1546 with model AverageValueNaive in generation 18 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1547 with model Cassandra in generation 18 of 25
Model Number: 1548 with model ETS in generation 18 of 25
Model Number: 1549 with model GLM in generation 18 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:308: DomainWarning:

The InversePower link function does not respect the domain of the Gamma family.

Model Number: 1550 with model DatepartRegression in generation 18 of 25
Model Number: 1551 with model Cassandra in generation 18 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

Model Number: 1552 with model SeasonalNaive in generation 18 of 25
Model Number: 1553 with model SeasonalityMotif in generation 18 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1554 with model FFT in generation 18 of 25
Model Number: 1555 with model UnivariateMotif in generation 18 of 25
Model Number: 1556 with model Cassandra in generation 18 of 25
Model Number: 1557 with model SeasonalNaive in generation 18 of 25
Model Number: 1558 with model BasicLinearModel in generation 18 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1559 with model SeasonalNaive in generation 18 of 25
Model Number: 1560 with model SeasonalityMotif in generation 18 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params mean {'0': {'det_order': 1, 'k_ar_diff': 0}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {}, '3': {'lag': 1, 'fill': 'zero'}, '4': {'window': None}, '5': {'method': 'zscore', 'method_params': {'distribution': 'norm', 'alpha': 0.1}, 'fillna': 'rolling_mean_24', 'transform_dict': {'fillna': 'fake_date', 'transformations': {'0': 'DifferencedTransformer', '1': 'MinMaxScaler'}, 'transformation_params': {'0': {'lag': 7, 'fill': 'one'}, '1': {}}}, 'isolated_only': True, 'on_inverse': False}} with error ValueError('Coint only works on multivarate series')") in model 1560 in generation 18: SeasonalityMotif
Model Number: 1561 with model FBProphet in generation 18 of 25
Model Number: 1562 with model FBProphet in generation 18 of 25
Model Number: 1563 with model RRVAR in generation 18 of 25
Model Number: 1564 with model SeasonalNaive in generation 18 of 25
New Generation: 19 of 25
Model Number: 1565 with model AverageValueNaive in generation 19 of 25
Model Number: 1566 with model SeasonalityMotif in generation 19 of 25
Model Number: 1567 with model AverageValueNaive in generation 19 of 25
Model Number: 1568 with model BasicLinearModel in generation 19 of 25
Model Number: 1569 with model Cassandra in generation 19 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1570 with model GLM in generation 19 of 25
Model Number: 1571 with model SeasonalityMotif in generation 19 of 25
Model Number: 1572 with model BasicLinearModel in generation 19 of 25
Model Number: 1573 with model FBProphet in generation 19 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params fake_date {'0': {}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {}, '3': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gbtree', 'max_depth': 6, 'eta': 0.01, 'min_child_weight': 5, 'subsample': 1, 'colsample_bylevel': 0.5, 'reg_alpha': 0, 'reg_lambda': 1, 'n_estimators': 100, 'quantile_alpha': 0.5, 'tree_method': 'hist'}, 'datepart_method': [52, 'month', 'day']}, 'fillna': 'pchip'}, '4': {}, '5': {}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 1573 in generation 19: FBProphet
Model Number: 1574 with model BasicLinearModel in generation 19 of 25
Template Eval Error: ValueError('Model BasicLinearModel returned improper forecast_length. Returned: 28 and requested: 30') in model 1574 in generation 19: BasicLinearModel
Model Number: 1575 with model SeasonalNaive in generation 19 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.400e+10, tolerance: 5.124e+07

Model Number: 1576 with model ETS in generation 19 of 25
Model Number: 1577 with model Cassandra in generation 19 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1578 with model Cassandra in generation 19 of 25
Model Number: 1579 with model SeasonalityMotif in generation 19 of 25
Model Number: 1580 with model SeasonalityMotif in generation 19 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1581 with model SeasonalNaive in generation 19 of 25
Model Number: 1582 with model SeasonalityMotif in generation 19 of 25
Model Number: 1583 with model GLM in generation 19 of 25
Model Number: 1584 with model ARDL in generation 19 of 25
Model Number: 1585 with model Cassandra in generation 19 of 25
Model Number: 1586 with model AverageValueNaive in generation 19 of 25
Model Number: 1587 with model SeasonalNaive in generation 19 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1588 with model UnivariateMotif in generation 19 of 25
Model Number: 1589 with model Cassandra in generation 19 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params mean {'0': {}, '1': {'low': 6, 'high': 32, 'K': 25, 'lanczos_factor': False, 'return_diff': True, 'on_transform': True, 'on_inverse': False}, '2': {}, '3': {'threshold': 1.0, 'splash_threshold': None, 'use_dayofmonth_holidays': True, 'use_wkdom_holidays': True, 'use_wkdeom_holidays': False, 'use_lunar_holidays': False, 'use_lunar_weekday': False, 'use_islamic_holidays': False, 'use_hebrew_holidays': False, 'use_hindu_holidays': False, 'anomaly_detector_params': {'method': 'minmax', 'method_params': {'alpha': 0.03}, 'fillna': 'ffill', 'transform_dict': None, 'isolated_only': False, 'on_inverse': False}, 'remove_excess_anomalies': True, 'impact': 'anomaly_score', 'regression_params': {}}, '4': {'output_distribution': 'uniform', 'n_quantiles': 246}, '5': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 1}} with error ValueError('BTCD only works on multivarate series')") in model 1589 in generation 19: Cassandra
Model Number: 1590 with model FFT in generation 19 of 25
Model Number: 1591 with model ARDL in generation 19 of 25
Model Number: 1592 with model FBProphet in generation 19 of 25
Model Number: 1593 with model FFT in generation 19 of 25
Model Number: 1594 with model DatepartRegression in generation 19 of 25
Model Number: 1595 with model AverageValueNaive in generation 19 of 25
Model Number: 1596 with model DatepartRegression in generation 19 of 25
Model Number: 1597 with model FFT in generation 19 of 25
Model Number: 1598 with model BasicLinearModel in generation 19 of 25
Model Number: 1599 with model SeasonalityMotif in generation 19 of 25
Model Number: 1600 with model ARDL in generation 19 of 25
Model Number: 1601 with model SeasonalNaive in generation 19 of 25
Model Number: 1602 with model FBProphet in generation 19 of 25
Model Number: 1603 with model FBProphet in generation 19 of 25
Model Number: 1604 with model ETS in generation 19 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params mean {'0': {'lag': 1, 'fill': 'bfill'}, '1': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gbtree', 'max_depth': 2, 'eta': 0.3, 'min_child_weight': 1, 'subsample': 1, 'colsample_bylevel': 0.7, 'reg_alpha': 0.001, 'reg_lambda': 0.03}, 'datepart_method': ['recurring']}, 'fillna': None}, '2': {'method': 0.3}, '3': {}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 1604 in generation 19: ETS
Model Number: 1605 with model ETS in generation 19 of 25
Model Number: 1606 with model DatepartRegression in generation 19 of 25
Template Eval Error: IndexError('tuple index out of range') in model 1606 in generation 19: DatepartRegression
Model Number: 1607 with model BasicLinearModel in generation 19 of 25
2025-07-30 00:00:00
Template Eval Error: Exception("Transformer MaxAbsScaler failed on inverse from params fake_date {'0': {}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {'lag_1': 12, 'method': 'Mean'}, '3': {'lag_1': 28, 'method': 'LastValue'}, '4': {'mode': 'downscale', 'factor': 1, 'down_method': 'decimate', 'fill_method': 'linear'}} with ValueError('Shape of passed values is (29, 1), indices imply (30, 1)')") in model 1607 in generation 19: BasicLinearModel
Model Number: 1608 with model FFT in generation 19 of 25
Model Number: 1609 with model ETS in generation 19 of 25
Model Number: 1610 with model FBProphet in generation 19 of 25
Model Number: 1611 with model GLS in generation 19 of 25
Model Number: 1612 with model BasicLinearModel in generation 19 of 25
Model Number: 1613 with model FFT in generation 19 of 25
Model Number: 1614 with model FFT in generation 19 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params rolling_mean {'0': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gblinear', 'max_depth': 2, 'eta': 0.003, 'min_child_weight': 1, 'subsample': 1, 'colsample_bylevel': 0.9, 'reg_alpha': 0, 'reg_lambda': 0.03}, 'datepart_method': 'simple_binarized'}, 'fillna': 'linear'}, '1': {'model': 'Linear', 'phi': 1, 'window': None, 'transform_dict': {'fillna': None, 'transformations': {'0': 'ScipyFilter'}, 'transformation_params': {'0': {'method': 'savgol_filter', 'method_args': {'window_length': 31, 'polyorder': 3, 'deriv': 0, 'mode': 'interp'}}}}}, '2': {'output_distribution': 'uniform', 'n_quantiles': 1000}, '3': {'lag_1': 28, 'method': 'LastValue'}, '4': {}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 1614 in generation 19: FFT
Model Number: 1615 with model ARDL in generation 19 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.169e+10, tolerance: 7.050e+06

Model Number: 1616 with model GLS in generation 19 of 25
Model Number: 1617 with model DatepartRegression in generation 19 of 25
interpolating
Template Eval Error: ValueError('Model DatepartRegression returned NaN for one or more series. fail_on_forecast_nan=True') in model 1617 in generation 19: DatepartRegression
Model Number: 1618 with model ARDL in generation 19 of 25
Model Number: 1619 with model SeasonalityMotif in generation 19 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_regression.py:508: UserWarning:

One or more samples have no neighbors within specified radius; predicting NaN.

Model Number: 1620 with model BasicLinearModel in generation 19 of 25
Model Number: 1621 with model Cassandra in generation 19 of 25
Model Number: 1622 with model SeasonalNaive in generation 19 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1623 with model GLS in generation 19 of 25
Model Number: 1624 with model AverageValueNaive in generation 19 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params cubic {'0': {'fixed': True, 'window': 24, 'macro_micro': False, 'center': True}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {'rows': 7}, '3': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 2}} with error ValueError('BTCD only works on multivarate series')") in model 1624 in generation 19: AverageValueNaive
Model Number: 1625 with model DatepartRegression in generation 19 of 25
Model Number: 1626 with model BasicLinearModel in generation 19 of 25
Model Number: 1627 with model Cassandra in generation 19 of 25
New Generation: 20 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1628 with model SeasonalityMotif in generation 20 of 25
Model Number: 1629 with model SeasonalityMotif in generation 20 of 25
Model Number: 1630 with model ARDL in generation 20 of 25
Template Eval Error: ValueError("ARDL series Close failed with error IndexError('tuple index out of range') exog train None and predict None") in model 1630 in generation 20: ARDL
Model Number: 1631 with model SeasonalNaive in generation 20 of 25
Model Number: 1632 with model SeasonalNaive in generation 20 of 25
Model Number: 1633 with model AverageValueNaive in generation 20 of 25
Model Number: 1634 with model Cassandra in generation 20 of 25
Model Number: 1635 with model SeasonalNaive in generation 20 of 25
Model Number: 1636 with model ARDL in generation 20 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1637 with model SeasonalityMotif in generation 20 of 25
Model Number: 1638 with model DatepartRegression in generation 20 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1638 in generation 20: DatepartRegression
Model Number: 1639 with model DatepartRegression in generation 20 of 25
Model Number: 1640 with model DatepartRegression in generation 20 of 25
Template Eval Error: IndexError('tuple index out of range') in model 1640 in generation 20: DatepartRegression
Model Number: 1641 with model AverageValueNaive in generation 20 of 25
Model Number: 1642 with model AverageValueNaive in generation 20 of 25
Model Number: 1643 with model AverageValueNaive in generation 20 of 25
Model Number: 1644 with model Cassandra in generation 20 of 25
Model Number: 1645 with model SeasonalityMotif in generation 20 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params mean {'0': {}, '1': {'lag_1': 24, 'method': 'LastValue'}, '2': {}, '3': {}, '4': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 1}, '5': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': None, 'threshold_method': 'max'}} with error ValueError('BTCD only works on multivarate series')") in model 1645 in generation 20: SeasonalityMotif
Model Number: 1646 with model FFT in generation 20 of 25
Model Number: 1647 with model ARDL in generation 20 of 25
Model Number: 1648 with model FBProphet in generation 20 of 25
Model Number: 1649 with model BasicLinearModel in generation 20 of 25
Model Number: 1650 with model SeasonalityMotif in generation 20 of 25
Model Number: 1651 with model Cassandra in generation 20 of 25
Model Number: 1652 with model FBProphet in generation 20 of 25
Model Number: 1653 with model ARDL in generation 20 of 25
Model Number: 1654 with model FBProphet in generation 20 of 25
Model Number: 1655 with model FFT in generation 20 of 25
Model Number: 1656 with model FFT in generation 20 of 25
Model Number: 1657 with model DatepartRegression in generation 20 of 25
Model Number: 1658 with model SeasonalityMotif in generation 20 of 25
Model Number: 1659 with model SeasonalNaive in generation 20 of 25
Model Number: 1660 with model FFT in generation 20 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params mean {'0': {'output_distribution': 'uniform', 'n_quantiles': 246}, '1': {}, '2': {}, '3': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 2}} with error ValueError('BTCD only works on multivarate series')") in model 1660 in generation 20: FFT
Model Number: 1661 with model FBProphet in generation 20 of 25
Model Number: 1662 with model SeasonalityMotif in generation 20 of 25
Model Number: 1663 with model AverageValueNaive in generation 20 of 25
Model Number: 1664 with model FFT in generation 20 of 25
Model Number: 1665 with model SeasonalityMotif in generation 20 of 25
Model Number: 1666 with model Cassandra in generation 20 of 25

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1667 with model AverageValueNaive in generation 20 of 25
Model Number: 1668 with model SeasonalityMotif in generation 20 of 25
Template Eval Error: ValueError('Model SeasonalityMotif returned NaN for one or more series. fail_on_forecast_nan=True') in model 1668 in generation 20: SeasonalityMotif
Model Number: 1669 with model FFT in generation 20 of 25
New Generation: 21 of 25

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning:

Mean of empty slice.

/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:130: RuntimeWarning:

invalid value encountered in divide

Model Number: 1670 with model AverageValueNaive in generation 21 of 25
Model Number: 1671 with model AverageValueNaive in generation 21 of 25
Model Number: 1672 with model SeasonalNaive in generation 21 of 25
Model Number: 1673 with model SeasonalityMotif in generation 21 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params mean {'0': {'rows': 1, 'lag': 28, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': None, 'threshold_method': 'mean'}, '1': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 1}, '2': {}} with error ValueError('BTCD only works on multivarate series')") in model 1673 in generation 21: SeasonalityMotif
Model Number: 1674 with model SeasonalityMotif in generation 21 of 25
Model Number: 1675 with model SeasonalNaive in generation 21 of 25
Model Number: 1676 with model SeasonalityMotif in generation 21 of 25
Model Number: 1677 with model DatepartRegression in generation 21 of 25
Model Number: 1678 with model FFT in generation 21 of 25
Model Number: 1679 with model ARDL in generation 21 of 25
Model Number: 1680 with model ARDL in generation 21 of 25
Model Number: 1681 with model FFT in generation 21 of 25
Model Number: 1682 with model SeasonalityMotif in generation 21 of 25
Model Number: 1683 with model SeasonalityMotif in generation 21 of 25
Model Number: 1684 with model SeasonalityMotif in generation 21 of 25
Model Number: 1685 with model Cassandra in generation 21 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1686 with model BasicLinearModel in generation 21 of 25
Model Number: 1687 with model FFT in generation 21 of 25
Model Number: 1688 with model SeasonalityMotif in generation 21 of 25
Model Number: 1689 with model Cassandra in generation 21 of 25
Model Number: 1690 with model FFT in generation 21 of 25
Model Number: 1691 with model AverageValueNaive in generation 21 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1692 with model Cassandra in generation 21 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1693 with model FBProphet in generation 21 of 25
Model Number: 1694 with model Cassandra in generation 21 of 25
Model Number: 1695 with model AverageValueNaive in generation 21 of 25
Model Number: 1696 with model SeasonalityMotif in generation 21 of 25
Template Eval Error: Exception("Transformer ReplaceConstant failed on fit from params akima {'0': {'numtaps': 12, 'cutoff_hz': 0.5, 'window': 'tukey', 'sampling_frequency': 28, 'on_transform': True, 'on_inverse': False, 'bounds_only': False}, '1': {'center': 'mean'}, '2': {'constant': 0, 'reintroduction_model': {'model': 'xgboost', 'model_params': {'booster': 'gbtree', 'colsample_bylevel': 0.54, 'learning_rate': 0.0125, 'max_depth': 11, 'min_child_weight': 0.0127203, 'n_estimators': 319}, 'datepart_method': ['dayofweek', 365.25]}, 'fillna': 'ffill'}} with error ValueError('Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]')") in model 1696 in generation 21: SeasonalityMotif
Model Number: 1697 with model AverageValueNaive in generation 21 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1698 with model FFT in generation 21 of 25
Model Number: 1699 with model FBProphet in generation 21 of 25
No anomalies detected.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 1700 with model Cassandra in generation 21 of 25
Model Number: 1701 with model DatepartRegression in generation 21 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1701 in generation 21: DatepartRegression
Model Number: 1702 with model FBProphet in generation 21 of 25
Model Number: 1703 with model SeasonalityMotif in generation 21 of 25
Model Number: 1704 with model ARDL in generation 21 of 25
Model Number: 1705 with model SeasonalNaive in generation 21 of 25
Model Number: 1706 with model AverageValueNaive in generation 21 of 25
Model Number: 1707 with model AverageValueNaive in generation 21 of 25
Model Number: 1708 with model AverageValueNaive in generation 21 of 25
Model Number: 1709 with model Cassandra in generation 21 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

Cassandra transformed data is all -0.0! Adding noise...

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1710 with model Cassandra in generation 21 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.44489e-25): result may not be accurate.

Model Number: 1711 with model Cassandra in generation 21 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

New Generation: 22 of 25
Model Number: 1712 with model AverageValueNaive in generation 22 of 25
Model Number: 1713 with model DatepartRegression in generation 22 of 25
Model Number: 1714 with model BasicLinearModel in generation 22 of 25
Model Number: 1715 with model Cassandra in generation 22 of 25
Template Eval Error: ValueError("regression_type='User' but future_regressor not supplied") in model 1715 in generation 22: Cassandra
Model Number: 1716 with model AverageValueNaive in generation 22 of 25
Model Number: 1717 with model SeasonalityMotif in generation 22 of 25
Model Number: 1718 with model AverageValueNaive in generation 22 of 25
Model Number: 1719 with model FFT in generation 22 of 25
Model Number: 1720 with model Cassandra in generation 22 of 25
Model Number: 1721 with model SeasonalityMotif in generation 22 of 25
Model Number: 1722 with model SeasonalityMotif in generation 22 of 25
Model Number: 1723 with model AverageValueNaive in generation 22 of 25
Model Number: 1724 with model SeasonalityMotif in generation 22 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1725 with model SeasonalityMotif in generation 22 of 25
Model Number: 1726 with model Cassandra in generation 22 of 25
Model Number: 1727 with model SeasonalityMotif in generation 22 of 25
Model Number: 1728 with model FFT in generation 22 of 25
Model Number: 1729 with model AverageValueNaive in generation 22 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1730 with model UnivariateMotif in generation 22 of 25
Model Number: 1731 with model DatepartRegression in generation 22 of 25
Model Number: 1732 with model AverageValueNaive in generation 22 of 25
Model Number: 1733 with model AverageValueNaive in generation 22 of 25
Model Number: 1734 with model FBProphet in generation 22 of 25
Model Number: 1735 with model FFT in generation 22 of 25
Model Number: 1736 with model DatepartRegression in generation 22 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1736 in generation 22: DatepartRegression
Model Number: 1737 with model SeasonalNaive in generation 22 of 25
Model Number: 1738 with model SeasonalNaive in generation 22 of 25
Model Number: 1739 with model SeasonalityMotif in generation 22 of 25
Model Number: 1740 with model Cassandra in generation 22 of 25
Model Number: 1741 with model SeasonalityMotif in generation 22 of 25
Model Number: 1742 with model FFT in generation 22 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1743 with model Cassandra in generation 22 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1744 with model AverageValueNaive in generation 22 of 25
Model Number: 1745 with model SeasonalityMotif in generation 22 of 25
Model Number: 1746 with model FFT in generation 22 of 25
Model Number: 1747 with model SeasonalityMotif in generation 22 of 25
Model Number: 1748 with model DatepartRegression in generation 22 of 25
Template Eval Error: IndexError('tuple index out of range') in model 1748 in generation 22: DatepartRegression
Model Number: 1749 with model AverageValueNaive in generation 22 of 25
2025-07-30 00:00:00
2025-07-30 00:00:00
2025-07-30 00:00:00
Template Eval Error: ValueError('Model AverageValueNaive returned improper forecast_length. Returned: 28 and requested: 30') in model 1749 in generation 22: AverageValueNaive
Model Number: 1750 with model AverageValueNaive in generation 22 of 25
Model Number: 1751 with model Cassandra in generation 22 of 25
Model Number: 1752 with model FBProphet in generation 22 of 25
No anomalies detected.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 1753 with model SeasonalityMotif in generation 22 of 25
New Generation: 23 of 25
Model Number: 1754 with model Cassandra in generation 23 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 1755 with model AverageValueNaive in generation 23 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1756 with model FFT in generation 23 of 25
Model Number: 1757 with model SeasonalityMotif in generation 23 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params ffill {'0': {}, '1': {}, '2': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 1}} with error ValueError('BTCD only works on multivarate series')") in model 1757 in generation 23: SeasonalityMotif
Model Number: 1758 with model Cassandra in generation 23 of 25
Model Number: 1759 with model FFT in generation 23 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1760 with model AverageValueNaive in generation 23 of 25
Model Number: 1761 with model SeasonalityMotif in generation 23 of 25
Model Number: 1762 with model Cassandra in generation 23 of 25

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.44489e-25): result may not be accurate.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1763 with model SeasonalNaive in generation 23 of 25
Model Number: 1764 with model AverageValueNaive in generation 23 of 25
Model Number: 1765 with model DatepartRegression in generation 23 of 25
Template Eval Error: ValueError('Input X contains NaN.\nAdaBoostRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values') in model 1765 in generation 23: DatepartRegression
Model Number: 1766 with model FFT in generation 23 of 25
Model Number: 1767 with model AverageValueNaive in generation 23 of 25
Model Number: 1768 with model Cassandra in generation 23 of 25
Model Number: 1769 with model BasicLinearModel in generation 23 of 25
Model Number: 1770 with model AverageValueNaive in generation 23 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1771 with model FBProphet in generation 23 of 25
Model Number: 1772 with model Cassandra in generation 23 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1773 with model FBProphet in generation 23 of 25
Model Number: 1774 with model AverageValueNaive in generation 23 of 25
Model Number: 1775 with model AverageValueNaive in generation 23 of 25
Model Number: 1776 with model DatepartRegression in generation 23 of 25
2025-07-30 00:00:00
2025-07-30 00:00:00
2025-07-30 00:00:00
Template Eval Error: ValueError('Model DatepartRegression returned improper forecast_length. Returned: 29 and requested: 30') in model 1776 in generation 23: DatepartRegression
Model Number: 1777 with model Cassandra in generation 23 of 25
Model Number: 1778 with model DatepartRegression in generation 23 of 25
Template Eval Error: IndexError('tuple index out of range') in model 1778 in generation 23: DatepartRegression
Model Number: 1779 with model FFT in generation 23 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1780 with model SeasonalityMotif in generation 23 of 25
Model Number: 1781 with model SeasonalityMotif in generation 23 of 25
Model Number: 1782 with model AverageValueNaive in generation 23 of 25
Model Number: 1783 with model FFT in generation 23 of 25
Model Number: 1784 with model SeasonalNaive in generation 23 of 25
Model Number: 1785 with model SeasonalityMotif in generation 23 of 25
Model Number: 1786 with model AverageValueNaive in generation 23 of 25
Model Number: 1787 with model SeasonalityMotif in generation 23 of 25
Model Number: 1788 with model SeasonalNaive in generation 23 of 25
Model Number: 1789 with model DatepartRegression in generation 23 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1789 in generation 23: DatepartRegression
Model Number: 1790 with model ARDL in generation 23 of 25
Model Number: 1791 with model Cassandra in generation 23 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1792 with model FBProphet in generation 23 of 25

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

Model Number: 1793 with model AverageValueNaive in generation 23 of 25

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

Model Number: 1794 with model FBProphet in generation 23 of 25
Model Number: 1795 with model AverageValueNaive in generation 23 of 25
New Generation: 24 of 25
Model Number: 1796 with model SeasonalityMotif in generation 24 of 25
Model Number: 1797 with model AverageValueNaive in generation 24 of 25
Model Number: 1798 with model AverageValueNaive in generation 24 of 25
Model Number: 1799 with model SeasonalityMotif in generation 24 of 25
Model Number: 1800 with model SeasonalityMotif in generation 24 of 25
Model Number: 1801 with model Cassandra in generation 24 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1802 with model Cassandra in generation 24 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1803 with model AverageValueNaive in generation 24 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params time {'0': {}, '1': {'fixed': True, 'window': 52, 'macro_micro': False, 'center': False}, '2': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 0.2, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'max'}, '3': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': None, 'threshold_method': 'max'}, '4': {'regression_model': {'model': 'LinearRegression', 'model_params': {}}, 'max_lags': 2}} with error ValueError('BTCD only works on multivarate series')") in model 1803 in generation 24: AverageValueNaive
Model Number: 1804 with model DatepartRegression in generation 24 of 25
Model Number: 1805 with model SeasonalityMotif in generation 24 of 25
Model Number: 1806 with model FFT in generation 24 of 25
Model Number: 1807 with model Cassandra in generation 24 of 25
Model Number: 1808 with model SeasonalNaive in generation 24 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1809 with model SeasonalityMotif in generation 24 of 25
Model Number: 1810 with model FBProphet in generation 24 of 25
Model Number: 1811 with model FFT in generation 24 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params ffill_mean_biased {'0': {}, '1': {'n_harmonics': 10, 'detrend': 'linear'}, '2': {'rows': 1, 'lag': 2, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'mean'}, '3': {'det_order': 0, 'k_ar_diff': 2}, '4': {'rows': 1, 'lag': 2, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}, '5': {'lag': 7, 'fill': 'bfill'}} with error ValueError('Coint only works on multivarate series')") in model 1811 in generation 24: FFT
Model Number: 1812 with model Cassandra in generation 24 of 25
Template Eval Error: ValueError('The covariance matrix of the support data is equal to 0, try to increase support_fraction') in model 1812 in generation 24: Cassandra
Model Number: 1813 with model SeasonalNaive in generation 24 of 25
Template Eval Error: Exception("Transformer BTCD failed on fit from params pchip {'0': {'method': 'clip', 'std_threshold': 5, 'fillna': None}, '1': {'numtaps': 256, 'cutoff_hz': 0.5, 'window': 'kaiser', 'sampling_frequency': 364, 'on_transform': True, 'on_inverse': False, 'bounds_only': False}, '2': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': None, 'threshold_method': 'max'}, '3': {'lag_1': 28, 'method': 'LastValue'}, '4': {'method': 0.5}, '5': {'regression_model': {'model': 'FastRidge', 'model_params': {}}, 'max_lags': 1}} with error ValueError('BTCD only works on multivarate series')") in model 1813 in generation 24: SeasonalNaive
Model Number: 1814 with model AverageValueNaive in generation 24 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/covariance/_robust_covariance.py:749: UserWarning:

The covariance matrix associated to your dataset is not full rank

Model Number: 1815 with model FFT in generation 24 of 25
Model Number: 1816 with model DatepartRegression in generation 24 of 25
Model Number: 1817 with model Cassandra in generation 24 of 25
Model Number: 1818 with model AverageValueNaive in generation 24 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1819 with model BasicLinearModel in generation 24 of 25
Model Number: 1820 with model DatepartRegression in generation 24 of 25
Model Number: 1821 with model ARDL in generation 24 of 25
Model Number: 1822 with model FBProphet in generation 24 of 25
Template Eval Error: Exception("Transformer Cointegration failed on fit from params akima {'0': {'rows': 1, 'lag': 7, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 1, 'threshold_method': 'max'}, '1': {'det_order': 1, 'k_ar_diff': 2}, '2': {}} with error ValueError('Coint only works on multivarate series')") in model 1822 in generation 24: FBProphet
Model Number: 1823 with model FFT in generation 24 of 25
Model Number: 1824 with model SeasonalityMotif in generation 24 of 25
Model Number: 1825 with model BasicLinearModel in generation 24 of 25
Model Number: 1826 with model AverageValueNaive in generation 24 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_glm/glm.py:285: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

Model Number: 1827 with model SeasonalNaive in generation 24 of 25
Model Number: 1828 with model SeasonalityMotif in generation 24 of 25
Model Number: 1829 with model SeasonalityMotif in generation 24 of 25
Model Number: 1830 with model ARDL in generation 24 of 25
Model Number: 1831 with model FBProphet in generation 24 of 25
Model Number: 1832 with model AverageValueNaive in generation 24 of 25
Model Number: 1833 with model SeasonalityMotif in generation 24 of 25
Model Number: 1834 with model AverageValueNaive in generation 24 of 25
Model Number: 1835 with model AverageValueNaive in generation 24 of 25
Model Number: 1836 with model FBProphet in generation 24 of 25
Model Number: 1837 with model AverageValueNaive in generation 24 of 25
New Generation: 25 of 25
Model Number: 1838 with model SeasonalityMotif in generation 25 of 25
Model Number: 1839 with model SeasonalNaive in generation 25 of 25
Model Number: 1840 with model DatepartRegression in generation 25 of 25
Model Number: 1841 with model Cassandra in generation 25 of 25
Model Number: 1842 with model FFT in generation 25 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1843 with model FFT in generation 25 of 25
Model Number: 1844 with model AverageValueNaive in generation 25 of 25
Model Number: 1845 with model FFT in generation 25 of 25

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1266: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1294: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

/usr/local/lib/python3.12/dist-packages/autots/tools/anomaly_utils.py:1262: FutureWarning:

The behavior of Index.insert with object-dtype is deprecated, in a future version this will return an object-dtype Index instead of inferring a non-object dtype. To retain the old behavior, do `idx.insert(loc, item).infer_objects(copy=False)`

Model Number: 1846 with model AverageValueNaive in generation 25 of 25
Model Number: 1847 with model SeasonalityMotif in generation 25 of 25
Model Number: 1848 with model AverageValueNaive in generation 25 of 25
Model Number: 1849 with model FBProphet in generation 25 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1849 in generation 25: FBProphet
Model Number: 1850 with model SeasonalityMotif in generation 25 of 25
Model Number: 1851 with model SeasonalityMotif in generation 25 of 25
Model Number: 1852 with model FFT in generation 25 of 25
Model Number: 1853 with model SeasonalityMotif in generation 25 of 25
Model Number: 1854 with model SeasonalNaive in generation 25 of 25
Model Number: 1855 with model DatepartRegression in generation 25 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1855 in generation 25: DatepartRegression
Model Number: 1856 with model SeasonalityMotif in generation 25 of 25
Model Number: 1857 with model FFT in generation 25 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

Model Number: 1858 with model SeasonalNaive in generation 25 of 25
Model Number: 1859 with model SeasonalNaive in generation 25 of 25
Model Number: 1860 with model AverageValueNaive in generation 25 of 25
Model Number: 1861 with model Cassandra in generation 25 of 25
Model Number: 1862 with model DatepartRegression in generation 25 of 25
Template Eval Error: ValueError("regression_type='User' but no future_regressor passed") in model 1862 in generation 25: DatepartRegression
Model Number: 1863 with model SeasonalNaive in generation 25 of 25
Model Number: 1864 with model AverageValueNaive in generation 25 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1865 with model SeasonalityMotif in generation 25 of 25
Model Number: 1866 with model ARDL in generation 25 of 25
Model Number: 1867 with model FFT in generation 25 of 25
Model Number: 1868 with model FBProphet in generation 25 of 25
Model Number: 1869 with model FBProphet in generation 25 of 25
Model Number: 1870 with model BasicLinearModel in generation 25 of 25
Model Number: 1871 with model FFT in generation 25 of 25
Model Number: 1872 with model Cassandra in generation 25 of 25
Model Number: 1873 with model AverageValueNaive in generation 25 of 25

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 1874 with model FBProphet in generation 25 of 25
Model Number: 1875 with model AverageValueNaive in generation 25 of 25
Model Number: 1876 with model AverageValueNaive in generation 25 of 25
Model Number: 1877 with model FFT in generation 25 of 25
Model Number: 1878 with model BasicLinearModel in generation 25 of 25
Model Number: 1879 with model FFT in generation 25 of 25
Template Eval Error: Exception('Transformer ChangepointDetrend failed on fit from params ffill_mean_biased {\'0\': {\'n_harmonics\': 20, \'detrend\': \'linear\'}, \'1\': {\'model\': \'Poisson\', \'changepoint_spacing\': 5040, \'changepoint_distance_end\': 28, \'datepart_method\': None}, \'2\': {\'method\': \'clip\', \'std_threshold\': 4, \'fillna\': None}, \'3\': {}, \'4\': {\'lag_1\': 4, \'method\': \'Mean\'}} with error ValueError("Some value(s) of y are out of the valid range of the loss \'HalfPoissonLoss\'.")') in model 1879 in generation 25: FFT
Ensembling Error: AttributeError("'AutoTS' object has no attribute 'ensemble_templates'"): Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/autots/evaluator/auto_ts.py", line 1455, in fit
    self.ensemble_templates,
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AutoTS' object has no attribute 'ensemble_templates'

Validation Round: 1
Model Number: 1 of 275 with model FFT for Validation 1
📈 1 - FFT with avg smape 5.94:
Model Number: 2 of 275 with model Cassandra for Validation 1

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

📈 2 - Cassandra with avg smape 4.84:
Model Number: 3 of 275 with model FFT for Validation 1
3 - FFT with avg smape 5.93:
Model Number: 4 of 275 with model FFT for Validation 1
4 - FFT with avg smape 5.93:
Model Number: 5 of 275 with model FFT for Validation 1
5 - FFT with avg smape 5.96:
Model Number: 6 of 275 with model SeasonalityMotif for Validation 1
6 - SeasonalityMotif with avg smape 5.54:
Model Number: 7 of 275 with model SeasonalityMotif for Validation 1
7 - SeasonalityMotif with avg smape 5.54:
Model Number: 8 of 275 with model SeasonalityMotif for Validation 1
8 - SeasonalityMotif with avg smape 5.54:
Model Number: 9 of 275 with model SeasonalityMotif for Validation 1
9 - SeasonalityMotif with avg smape 5.53:
Model Number: 10 of 275 with model SeasonalityMotif for Validation 1
10 - SeasonalityMotif with avg smape 5.53:
Model Number: 11 of 275 with model SeasonalityMotif for Validation 1
11 - SeasonalityMotif with avg smape 5.84:
Model Number: 12 of 275 with model SeasonalityMotif for Validation 1
12 - SeasonalityMotif with avg smape 5.74:
Model Number: 13 of 275 with model SeasonalityMotif for Validation 1
13 - SeasonalityMotif with avg smape 5.5:
Model Number: 14 of 275 with model SeasonalityMotif for Validation 1
14 - SeasonalityMotif with avg smape 5.47:
Model Number: 15 of 275 with model AverageValueNaive for Validation 1
15 - AverageValueNaive with avg smape 6.07:
Model Number: 16 of 275 with model AverageValueNaive for Validation 1
16 - AverageValueNaive with avg smape 6.07:
Model Number: 17 of 275 with model AverageValueNaive for Validation 1
17 - AverageValueNaive with avg smape 6.06:
Model Number: 18 of 275 with model AverageValueNaive for Validation 1
18 - AverageValueNaive with avg smape 6.06:
Model Number: 19 of 275 with model AverageValueNaive for Validation 1
19 - AverageValueNaive with avg smape 6.06:
Model Number: 20 of 275 with model AverageValueNaive for Validation 1
20 - AverageValueNaive with avg smape 6.07:
Model Number: 21 of 275 with model AverageValueNaive for Validation 1
21 - AverageValueNaive with avg smape 6.07:
Model Number: 22 of 275 with model AverageValueNaive for Validation 1
22 - AverageValueNaive with avg smape 6.07:
Model Number: 23 of 275 with model AverageValueNaive for Validation 1
23 - AverageValueNaive with avg smape 6.05:
Model Number: 24 of 275 with model AverageValueNaive for Validation 1
24 - AverageValueNaive with avg smape 6.06:
Model Number: 25 of 275 with model AverageValueNaive for Validation 1
25 - AverageValueNaive with avg smape 6.06:
Model Number: 26 of 275 with model SeasonalNaive for Validation 1
26 - SeasonalNaive with avg smape 4.89:
Model Number: 27 of 275 with model AverageValueNaive for Validation 1
27 - AverageValueNaive with avg smape 6.07:
Model Number: 28 of 275 with model AverageValueNaive for Validation 1
28 - AverageValueNaive with avg smape 6.07:
Model Number: 29 of 275 with model AverageValueNaive for Validation 1
29 - AverageValueNaive with avg smape 6.07:
Model Number: 30 of 275 with model Cassandra for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

📈 30 - Cassandra with avg smape 4.77:
Model Number: 31 of 275 with model DatepartRegression for Validation 1
31 - DatepartRegression with avg smape 5.71:
Model Number: 32 of 275 with model AverageValueNaive for Validation 1
32 - AverageValueNaive with avg smape 6.09:
Model Number: 33 of 275 with model SeasonalityMotif for Validation 1
33 - SeasonalityMotif with avg smape 5.22:
Model Number: 34 of 275 with model FFT for Validation 1
34 - FFT with avg smape 5.15:
Model Number: 35 of 275 with model SeasonalityMotif for Validation 1
35 - SeasonalityMotif with avg smape 5.1:
Model Number: 36 of 275 with model SeasonalityMotif for Validation 1
36 - SeasonalityMotif with avg smape 5.48:
Model Number: 37 of 275 with model FBProphet for Validation 1
37 - FBProphet with avg smape 5.97:
Model Number: 38 of 275 with model FFT for Validation 1
38 - FFT with avg smape 5.15:
Model Number: 39 of 275 with model FBProphet for Validation 1
39 - FBProphet with avg smape 5.99:
Model Number: 40 of 275 with model DatepartRegression for Validation 1
40 - DatepartRegression with avg smape 5.36:
Model Number: 41 of 275 with model DatepartRegression for Validation 1
41 - DatepartRegression with avg smape 5.44:
Model Number: 42 of 275 with model FBProphet for Validation 1
42 - FBProphet with avg smape 5.97:
Model Number: 43 of 275 with model FFT for Validation 1
43 - FFT with avg smape 5.0:
Model Number: 44 of 275 with model FFT for Validation 1
44 - FFT with avg smape 6.15:
Model Number: 45 of 275 with model SeasonalNaive for Validation 1
45 - SeasonalNaive with avg smape 5.09:
Model Number: 46 of 275 with model Cassandra for Validation 1
46 - Cassandra with avg smape 5.08:
Model Number: 47 of 275 with model FBProphet for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

47 - FBProphet with avg smape 5.72:
Model Number: 48 of 275 with model SeasonalityMotif for Validation 1
48 - SeasonalityMotif with avg smape 5.39:
Model Number: 49 of 275 with model SeasonalityMotif for Validation 1
49 - SeasonalityMotif with avg smape 5.68:
Model Number: 50 of 275 with model SeasonalNaive for Validation 1
50 - SeasonalNaive with avg smape 5.09:
Model Number: 51 of 275 with model Cassandra for Validation 1
📈 51 - Cassandra with avg smape 3.97:
Model Number: 52 of 275 with model SeasonalityMotif for Validation 1
52 - SeasonalityMotif with avg smape 5.15:
Model Number: 53 of 275 with model BasicLinearModel for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

53 - BasicLinearModel with avg smape 5.31:
Model Number: 54 of 275 with model FBProphet for Validation 1
54 - FBProphet with avg smape 5.91:
Model Number: 55 of 275 with model Cassandra for Validation 1
55 - Cassandra with avg smape 4.03:
Model Number: 56 of 275 with model FFT for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

56 - FFT with avg smape 5.68:
Model Number: 57 of 275 with model FFT for Validation 1
57 - FFT with avg smape 5.68:
Model Number: 58 of 275 with model FFT for Validation 1
58 - FFT with avg smape 5.68:
Model Number: 59 of 275 with model FFT for Validation 1
59 - FFT with avg smape 5.73:
Model Number: 60 of 275 with model FFT for Validation 1
60 - FFT with avg smape 5.73:
Model Number: 61 of 275 with model FFT for Validation 1
61 - FFT with avg smape 5.73:
Model Number: 62 of 275 with model FFT for Validation 1
62 - FFT with avg smape 5.73:
Model Number: 63 of 275 with model SeasonalNaive for Validation 1
63 - SeasonalNaive with avg smape 5.07:
Model Number: 64 of 275 with model Cassandra for Validation 1
64 - Cassandra with avg smape 4.41:
Model Number: 65 of 275 with model SeasonalNaive for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

65 - SeasonalNaive with avg smape 5.06:
Model Number: 66 of 275 with model SeasonalNaive for Validation 1
66 - SeasonalNaive with avg smape 5.06:
Model Number: 67 of 275 with model SeasonalNaive for Validation 1
67 - SeasonalNaive with avg smape 6.05:
Model Number: 68 of 275 with model ARDL for Validation 1
68 - ARDL with avg smape 5.94:
Model Number: 69 of 275 with model ARDL for Validation 1
69 - ARDL with avg smape 5.94:
Model Number: 70 of 275 with model FBProphet for Validation 1
70 - FBProphet with avg smape 6.02:
Model Number: 71 of 275 with model Cassandra for Validation 1
71 - Cassandra with avg smape 5.66:
Model Number: 72 of 275 with model DatepartRegression for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

72 - DatepartRegression with avg smape 6.06:
Model Number: 73 of 275 with model DatepartRegression for Validation 1
73 - DatepartRegression with avg smape 6.06:
Model Number: 74 of 275 with model ARDL for Validation 1
74 - ARDL with avg smape 5.93:
Model Number: 75 of 275 with model ARDL for Validation 1
75 - ARDL with avg smape 5.93:
Model Number: 76 of 275 with model Cassandra for Validation 1
76 - Cassandra with avg smape 4.22:
Model Number: 77 of 275 with model ARDL for Validation 1
77 - ARDL with avg smape 6.04:
Model Number: 78 of 275 with model ARDL for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

78 - ARDL with avg smape 6.04:
Model Number: 79 of 275 with model Cassandra for Validation 1
79 - Cassandra with avg smape 5.06:
Model Number: 80 of 275 with model ARDL for Validation 1
80 - ARDL with avg smape 5.94:
Model Number: 81 of 275 with model ARDL for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

81 - ARDL with avg smape 5.94:
Model Number: 82 of 275 with model ARDL for Validation 1
82 - ARDL with avg smape 5.99:
Model Number: 83 of 275 with model SeasonalNaive for Validation 1
83 - SeasonalNaive with avg smape 5.57:
Model Number: 84 of 275 with model Cassandra for Validation 1
84 - Cassandra with avg smape 5.05:
Model Number: 85 of 275 with model SeasonalNaive for Validation 1
85 - SeasonalNaive with avg smape 5.56:
Model Number: 86 of 275 with model ARDL for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

86 - ARDL with avg smape 5.99:
Model Number: 87 of 275 with model UnivariateMotif for Validation 1
87 - UnivariateMotif with avg smape 6.28:
Model Number: 88 of 275 with model ARDL for Validation 1
88 - ARDL with avg smape 6.04:
Model Number: 89 of 275 with model Cassandra for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.276e+10, tolerance: 4.428e+07

89 - Cassandra with avg smape 4.62:
Model Number: 90 of 275 with model SeasonalNaive for Validation 1
90 - SeasonalNaive with avg smape 5.36:
Model Number: 91 of 275 with model Cassandra for Validation 1
📈 91 - Cassandra with avg smape 3.89:
Model Number: 92 of 275 with model ARDL for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

92 - ARDL with avg smape 6.04:
Model Number: 93 of 275 with model Cassandra for Validation 1
93 - Cassandra with avg smape 4.27:
Model Number: 94 of 275 with model Cassandra for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

94 - Cassandra with avg smape 4.56:
Model Number: 95 of 275 with model Cassandra for Validation 1
95 - Cassandra with avg smape 5.31:

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.276e+10, tolerance: 4.428e+07

Model Number: 96 of 275 with model SeasonalNaive for Validation 1
96 - SeasonalNaive with avg smape 5.02:
Model Number: 97 of 275 with model ARDL for Validation 1
97 - ARDL with avg smape 5.98:
Model Number: 98 of 275 with model SeasonalNaive for Validation 1
98 - SeasonalNaive with avg smape 5.4:
Model Number: 99 of 275 with model SeasonalNaive for Validation 1
99 - SeasonalNaive with avg smape 5.41:
Model Number: 100 of 275 with model SeasonalNaive for Validation 1
100 - SeasonalNaive with avg smape 5.99:
Model Number: 101 of 275 with model DatepartRegression for Validation 1
101 - DatepartRegression with avg smape 5.15:
Model Number: 102 of 275 with model BasicLinearModel for Validation 1
102 - BasicLinearModel with avg smape 7.65:
Model Number: 103 of 275 with model BasicLinearModel for Validation 1
103 - BasicLinearModel with avg smape 7.6:
Model Number: 104 of 275 with model SeasonalNaive for Validation 1
104 - SeasonalNaive with avg smape 6.17:
Model Number: 105 of 275 with model ARDL for Validation 1
105 - ARDL with avg smape 5.42:
Model Number: 106 of 275 with model BasicLinearModel for Validation 1
106 - BasicLinearModel with avg smape 6.49:
Model Number: 107 of 275 with model ARDL for Validation 1
107 - ARDL with avg smape 5.2:
Model Number: 108 of 275 with model BasicLinearModel for Validation 1
108 - BasicLinearModel with avg smape 8.27:
Model Number: 109 of 275 with model BasicLinearModel for Validation 1
109 - BasicLinearModel with avg smape 6.63:
Model Number: 110 of 275 with model BasicLinearModel for Validation 1
110 - BasicLinearModel with avg smape 6.64:
Model Number: 111 of 275 with model ETS for Validation 1
111 - ETS with avg smape 5.4:
Model Number: 112 of 275 with model ETS for Validation 1
112 - ETS with avg smape 5.4:
Model Number: 113 of 275 with model GLS for Validation 1
113 - GLS with avg smape 5.35:
Model Number: 114 of 275 with model GLS for Validation 1
114 - GLS with avg smape 5.35:
Model Number: 115 of 275 with model GLS for Validation 1

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

115 - GLS with avg smape 5.35:
Model Number: 116 of 275 with model GLS for Validation 1
116 - GLS with avg smape 5.31:
Model Number: 117 of 275 with model BasicLinearModel for Validation 1
117 - BasicLinearModel with avg smape 12.52:
Model Number: 118 of 275 with model GLS for Validation 1
118 - GLS with avg smape 5.3:
Model Number: 119 of 275 with model GLS for Validation 1
119 - GLS with avg smape 5.3:
Model Number: 120 of 275 with model GLS for Validation 1
120 - GLS with avg smape 5.35:
Model Number: 121 of 275 with model GLS for Validation 1
121 - GLS with avg smape 5.35:
Model Number: 122 of 275 with model DatepartRegression for Validation 1

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

122 - DatepartRegression with avg smape 5.66:
Model Number: 123 of 275 with model BasicLinearModel for Validation 1
123 - BasicLinearModel with avg smape 5.7:
Model Number: 124 of 275 with model DatepartRegression for Validation 1
124 - DatepartRegression with avg smape 5.37:
Model Number: 125 of 275 with model BasicLinearModel for Validation 1
125 - BasicLinearModel with avg smape 5.7:
Model Number: 126 of 275 with model BasicLinearModel for Validation 1
126 - BasicLinearModel with avg smape 5.84:
Model Number: 127 of 275 with model BasicLinearModel for Validation 1
127 - BasicLinearModel with avg smape 5.84:
Model Number: 128 of 275 with model BasicLinearModel for Validation 1
128 - BasicLinearModel with avg smape 5.95:
Model Number: 129 of 275 with model BasicLinearModel for Validation 1
129 - BasicLinearModel with avg smape 5.46:
Model Number: 130 of 275 with model ETS for Validation 1
130 - ETS with avg smape 5.31:
Model Number: 131 of 275 with model FBProphet for Validation 1
131 - FBProphet with avg smape 4.78:
Model Number: 132 of 275 with model ETS for Validation 1
132 - ETS with avg smape 5.3:
Model Number: 133 of 275 with model ETS for Validation 1
133 - ETS with avg smape 5.3:
Model Number: 134 of 275 with model ETS for Validation 1
134 - ETS with avg smape 5.3:
Model Number: 135 of 275 with model FBProphet for Validation 1
135 - FBProphet with avg smape 4.78:
Model Number: 136 of 275 with model FBProphet for Validation 1
136 - FBProphet with avg smape 5.27:
Model Number: 137 of 275 with model FBProphet for Validation 1
137 - FBProphet with avg smape 4.78:
Model Number: 138 of 275 with model FBProphet for Validation 1
138 - FBProphet with avg smape 4.78:
Model Number: 139 of 275 with model GLS for Validation 1
139 - GLS with avg smape 5.31:
Model Number: 140 of 275 with model GLS for Validation 1
140 - GLS with avg smape 5.31:
Model Number: 141 of 275 with model GLS for Validation 1
141 - GLS with avg smape 5.31:
Model Number: 142 of 275 with model GLS for Validation 1
142 - GLS with avg smape 5.31:
Model Number: 143 of 275 with model GLS for Validation 1
143 - GLS with avg smape 5.31:
Model Number: 144 of 275 with model GLS for Validation 1
144 - GLS with avg smape 5.31:
Model Number: 145 of 275 with model ETS for Validation 1
145 - ETS with avg smape 5.31:
Model Number: 146 of 275 with model ETS for Validation 1
146 - ETS with avg smape 5.31:
Model Number: 147 of 275 with model DatepartRegression for Validation 1
147 - DatepartRegression with avg smape 5.29:
Model Number: 148 of 275 with model GLS for Validation 1
148 - GLS with avg smape 5.3:
Model Number: 149 of 275 with model FBProphet for Validation 1

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

149 - FBProphet with avg smape 5.28:
Model Number: 150 of 275 with model DatepartRegression for Validation 1

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

150 - DatepartRegression with avg smape 5.3:
Model Number: 151 of 275 with model DatepartRegression for Validation 1
151 - DatepartRegression with avg smape 5.3:
Model Number: 152 of 275 with model DatepartRegression for Validation 1
152 - DatepartRegression with avg smape 5.3:
Model Number: 153 of 275 with model DatepartRegression for Validation 1
153 - DatepartRegression with avg smape 5.3:
Model Number: 154 of 275 with model ETS for Validation 1
154 - ETS with avg smape 5.3:
Model Number: 155 of 275 with model ETS for Validation 1
155 - ETS with avg smape 5.3:
Model Number: 156 of 275 with model GLM for Validation 1
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 156 in generation 0: GLM
Model Number: 157 of 275 with model GLM for Validation 1
157 - GLM with avg smape 5.3:
Model Number: 158 of 275 with model GLM for Validation 1
158 - GLM with avg smape 5.3:
Model Number: 159 of 275 with model GLM for Validation 1

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:445: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

159 - GLM with avg smape 5.3:
Model Number: 160 of 275 with model GLM for Validation 1
160 - GLM with avg smape 5.3:
Model Number: 161 of 275 with model GLM for Validation 1
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 161 in generation 0: GLM
Model Number: 162 of 275 with model GLM for Validation 1

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1402: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:445: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1402: RuntimeWarning:

divide by zero encountered in divide

162 - GLM with avg smape 5.3:
Model Number: 163 of 275 with model GLM for Validation 1
163 - GLM with avg smape 5.3:
Model Number: 164 of 275 with model ETS for Validation 1
164 - ETS with avg smape 5.3:
Model Number: 165 of 275 with model GLM for Validation 1

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1402: RuntimeWarning:

divide by zero encountered in divide

165 - GLM with avg smape 5.3:
Model Number: 166 of 275 with model DatepartRegression for Validation 1
166 - DatepartRegression with avg smape 5.11:
Model Number: 167 of 275 with model DatepartRegression for Validation 1

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

167 - DatepartRegression with avg smape 5.3:
Model Number: 168 of 275 with model ETS for Validation 1
168 - ETS with avg smape 5.3:
Model Number: 169 of 275 with model ETS for Validation 1
169 - ETS with avg smape 5.3:
Model Number: 170 of 275 with model ETS for Validation 1
170 - ETS with avg smape 5.3:
Model Number: 171 of 275 with model GLM for Validation 1
171 - GLM with avg smape 5.3:
Model Number: 172 of 275 with model ETS for Validation 1

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

172 - ETS with avg smape 5.3:
Model Number: 173 of 275 with model BasicLinearModel for Validation 1
173 - BasicLinearModel with avg smape 5.27:
Model Number: 174 of 275 with model SectionalMotif for Validation 1
174 - SectionalMotif with avg smape 5.25:
Model Number: 175 of 275 with model FBProphet for Validation 1
175 - FBProphet with avg smape 5.8:
Model Number: 176 of 275 with model FBProphet for Validation 1
176 - FBProphet with avg smape 5.8:
Model Number: 177 of 275 with model RRVAR for Validation 1
177 - RRVAR with avg smape 5.29:
Model Number: 178 of 275 with model RRVAR for Validation 1
178 - RRVAR with avg smape 5.29:
Model Number: 179 of 275 with model FBProphet for Validation 1
179 - FBProphet with avg smape 5.18:
Model Number: 180 of 275 with model LastValueNaive for Validation 1
180 - LastValueNaive with avg smape 5.25:
Model Number: 181 of 275 with model GLM for Validation 1
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 181 in generation 0: GLM
Model Number: 182 of 275 with model UnivariateMotif for Validation 1
182 - UnivariateMotif with avg smape 5.38:
Model Number: 183 of 275 with model GLM for Validation 1

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:308: DomainWarning:

The InversePower link function does not respect the domain of the Gamma family.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

overflow encountered in square

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:325: RuntimeWarning:

divide by zero encountered in power

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:775: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:1328: RuntimeWarning:

invalid value encountered in multiply

183 - GLM with avg smape 5.3:
Model Number: 184 of 275 with model GLM for Validation 1
184 - GLM with avg smape 5.3:
Model Number: 185 of 275 with model GLM for Validation 1
185 - GLM with avg smape 5.3:
Model Number: 186 of 275 with model GLM for Validation 1

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

186 - GLM with avg smape 5.3:
Model Number: 187 of 275 with model LastValueNaive for Validation 1
187 - LastValueNaive with avg smape 5.18:
Model Number: 188 of 275 with model LastValueNaive for Validation 1
188 - LastValueNaive with avg smape 5.18:
Model Number: 189 of 275 with model LastValueNaive for Validation 1
189 - LastValueNaive with avg smape 5.18:
Model Number: 190 of 275 with model LastValueNaive for Validation 1
190 - LastValueNaive with avg smape 5.18:
Model Number: 191 of 275 with model LastValueNaive for Validation 1
191 - LastValueNaive with avg smape 5.18:
Model Number: 192 of 275 with model LastValueNaive for Validation 1
192 - LastValueNaive with avg smape 5.18:
Model Number: 193 of 275 with model LastValueNaive for Validation 1
📈 193 - LastValueNaive with avg smape 3.82:
Model Number: 194 of 275 with model LastValueNaive for Validation 1
194 - LastValueNaive with avg smape 5.68:
Model Number: 195 of 275 with model LastValueNaive for Validation 1
195 - LastValueNaive with avg smape 5.68:
Model Number: 196 of 275 with model LastValueNaive for Validation 1
196 - LastValueNaive with avg smape 5.68:
Model Number: 197 of 275 with model LastValueNaive for Validation 1
197 - LastValueNaive with avg smape 5.68:
Model Number: 198 of 275 with model LastValueNaive for Validation 1
198 - LastValueNaive with avg smape 5.68:
Model Number: 199 of 275 with model LastValueNaive for Validation 1
199 - LastValueNaive with avg smape 5.66:
Model Number: 200 of 275 with model SectionalMotif for Validation 1
200 - SectionalMotif with avg smape 5.39:
Model Number: 201 of 275 with model SectionalMotif for Validation 1
201 - SectionalMotif with avg smape 6.47:
Model Number: 202 of 275 with model SectionalMotif for Validation 1
202 - SectionalMotif with avg smape 5.09:
Model Number: 203 of 275 with model UnivariateMotif for Validation 1
203 - UnivariateMotif with avg smape 6.14:
Model Number: 204 of 275 with model RRVAR for Validation 1
204 - RRVAR with avg smape 6.58:
Model Number: 205 of 275 with model UnivariateMotif for Validation 1
205 - UnivariateMotif with avg smape 5.94:
Model Number: 206 of 275 with model UnivariateMotif for Validation 1
206 - UnivariateMotif with avg smape 12.15:
Model Number: 207 of 275 with model UnivariateMotif for Validation 1
207 - UnivariateMotif with avg smape 6.14:
Model Number: 208 of 275 with model UnivariateMotif for Validation 1
208 - UnivariateMotif with avg smape 5.2:
Model Number: 209 of 275 with model MetricMotif for Validation 1
209 - MetricMotif with avg smape 4.99:
Model Number: 210 of 275 with model UnivariateMotif for Validation 1
210 - UnivariateMotif with avg smape 5.27:
Model Number: 211 of 275 with model MetricMotif for Validation 1
211 - MetricMotif with avg smape 10.08:
Model Number: 212 of 275 with model SectionalMotif for Validation 1
212 - SectionalMotif with avg smape 5.02:
Model Number: 213 of 275 with model SectionalMotif for Validation 1
213 - SectionalMotif with avg smape 4.99:
Model Number: 214 of 275 with model ConstantNaive for Validation 1
214 - ConstantNaive with avg smape 5.41:
Model Number: 215 of 275 with model UnivariateMotif for Validation 1
215 - UnivariateMotif with avg smape 5.2:
Model Number: 216 of 275 with model UnivariateMotif for Validation 1
216 - UnivariateMotif with avg smape 5.22:
Model Number: 217 of 275 with model MetricMotif for Validation 1
217 - MetricMotif with avg smape 5.12:
Model Number: 218 of 275 with model MetricMotif for Validation 1
218 - MetricMotif with avg smape 4.11:
Model Number: 219 of 275 with model SectionalMotif for Validation 1
219 - SectionalMotif with avg smape 5.28:
Model Number: 220 of 275 with model SectionalMotif for Validation 1
220 - SectionalMotif with avg smape 4.97:
Model Number: 221 of 275 with model SectionalMotif for Validation 1
221 - SectionalMotif with avg smape 5.29:
Model Number: 222 of 275 with model ConstantNaive for Validation 1
222 - ConstantNaive with avg smape 5.3:
Model Number: 223 of 275 with model MetricMotif for Validation 1
223 - MetricMotif with avg smape 5.23:
Model Number: 224 of 275 with model MetricMotif for Validation 1
224 - MetricMotif with avg smape 5.96:
Model Number: 225 of 275 with model SectionalMotif for Validation 1
225 - SectionalMotif with avg smape 8.03:
Model Number: 226 of 275 with model UnivariateMotif for Validation 1
226 - UnivariateMotif with avg smape 8.82:
Model Number: 227 of 275 with model MetricMotif for Validation 1
227 - MetricMotif with avg smape 5.24:
Model Number: 228 of 275 with model SectionalMotif for Validation 1
228 - SectionalMotif with avg smape 6.71:
Model Number: 229 of 275 with model ConstantNaive for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

229 - ConstantNaive with avg smape 5.42:
Model Number: 230 of 275 with model ConstantNaive for Validation 1
230 - ConstantNaive with avg smape 5.42:
Model Number: 231 of 275 with model MetricMotif for Validation 1
231 - MetricMotif with avg smape 4.62:
Model Number: 232 of 275 with model SectionalMotif for Validation 1
232 - SectionalMotif with avg smape 6.97:
Model Number: 233 of 275 with model SectionalMotif for Validation 1
233 - SectionalMotif with avg smape 5.59:
Model Number: 234 of 275 with model LastValueNaive for Validation 1
234 - LastValueNaive with avg smape 6.11:
Model Number: 235 of 275 with model SectionalMotif for Validation 1
235 - SectionalMotif with avg smape 6.48:
Model Number: 236 of 275 with model MetricMotif for Validation 1
236 - MetricMotif with avg smape 9.71:
Model Number: 237 of 275 with model SectionalMotif for Validation 1
237 - SectionalMotif with avg smape 5.74:
Model Number: 238 of 275 with model UnivariateMotif for Validation 1
238 - UnivariateMotif with avg smape 5.81:
Model Number: 239 of 275 with model UnivariateMotif for Validation 1
239 - UnivariateMotif with avg smape 7.37:
Model Number: 240 of 275 with model ConstantNaive for Validation 1
240 - ConstantNaive with avg smape 8.27:
Model Number: 241 of 275 with model MetricMotif for Validation 1
241 - MetricMotif with avg smape 14.9:
Model Number: 242 of 275 with model UnivariateMotif for Validation 1
📈 242 - UnivariateMotif with avg smape 1.68:
Model Number: 243 of 275 with model UnivariateMotif for Validation 1
243 - UnivariateMotif with avg smape 3.34:
Model Number: 244 of 275 with model MetricMotif for Validation 1
244 - MetricMotif with avg smape 5.25:
Model Number: 245 of 275 with model MetricMotif for Validation 1
245 - MetricMotif with avg smape 10.58:
Model Number: 246 of 275 with model ConstantNaive for Validation 1
246 - ConstantNaive with avg smape 7.85:
Model Number: 247 of 275 with model ConstantNaive for Validation 1
247 - ConstantNaive with avg smape 5.63:
Model Number: 248 of 275 with model MetricMotif for Validation 1
248 - MetricMotif with avg smape 18.24:
Model Number: 249 of 275 with model ConstantNaive for Validation 1
249 - ConstantNaive with avg smape 7.98:
Model Number: 250 of 275 with model ConstantNaive for Validation 1
250 - ConstantNaive with avg smape 6.72:
Model Number: 251 of 275 with model ConstantNaive for Validation 1
251 - ConstantNaive with avg smape 6.11:
Model Number: 252 of 275 with model MetricMotif for Validation 1
252 - MetricMotif with avg smape 6.11:
Model Number: 253 of 275 with model ConstantNaive for Validation 1
253 - ConstantNaive with avg smape 6.11:
Model Number: 254 of 275 with model ConstantNaive for Validation 1
254 - ConstantNaive with avg smape 6.51:
Model Number: 255 of 275 with model VAR for Validation 1
255 - VAR with avg smape 5.07:
Model Number: 256 of 275 with model MetricMotif for Validation 1
256 - MetricMotif with avg smape 10.52:
Model Number: 257 of 275 with model ConstantNaive for Validation 1
257 - ConstantNaive with avg smape 7.24:
Model Number: 258 of 275 with model ConstantNaive for Validation 1
258 - ConstantNaive with avg smape 7.23:
Model Number: 259 of 275 with model ConstantNaive for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

259 - ConstantNaive with avg smape 145.53:
Model Number: 260 of 275 with model RRVAR for Validation 1
260 - RRVAR with avg smape 7.18:
Model Number: 261 of 275 with model RRVAR for Validation 1
261 - RRVAR with avg smape 9.67:
Model Number: 262 of 275 with model WindowRegression for Validation 1
262 - WindowRegression with avg smape 9.92:
Model Number: 263 of 275 with model RRVAR for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

263 - RRVAR with avg smape 4.51:
Model Number: 264 of 275 with model RRVAR for Validation 1
264 - RRVAR with avg smape 6.61:
Model Number: 265 of 275 with model RRVAR for Validation 1
265 - RRVAR with avg smape 8.04:
Model Number: 266 of 275 with model RRVAR for Validation 1
266 - RRVAR with avg smape 5.48:
Model Number: 267 of 275 with model RRVAR for Validation 1
267 - RRVAR with avg smape 4.5:
Model Number: 268 of 275 with model RRVAR for Validation 1
268 - RRVAR with avg smape 4.44:
Model Number: 269 of 275 with model RRVAR for Validation 1
269 - RRVAR with avg smape 8.95:
Model Number: 270 of 275 with model WindowRegression for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

270 - WindowRegression with avg smape 30.18:
Model Number: 271 of 275 with model RRVAR for Validation 1
271 - RRVAR with avg smape 6.4:
Model Number: 272 of 275 with model WindowRegression for Validation 1
272 - WindowRegression with avg smape 8.34:
Model Number: 273 of 275 with model RRVAR for Validation 1

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.50609e-25): result may not be accurate.

273 - RRVAR with avg smape 15.69:
Model Number: 274 of 275 with model WindowRegression for Validation 1
Epoch 1/10

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 2105.0740
Epoch 2/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 485.4809
Epoch 3/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 241.3202
Epoch 4/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 151.4521
Epoch 5/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 100.6902
Epoch 6/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 59.2535
Epoch 7/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 31.1375
Epoch 8/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 16.1275
Epoch 9/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.2921
Epoch 10/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.3408

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7e76e485e980> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
274 - WindowRegression with avg smape 36.46:
Model Number: 275 of 275 with model RRVAR for Validation 1
275 - RRVAR with avg smape 199.35:
Validation Round: 2
Model Number: 1 of 275 with model FFT for Validation 2
📈 1 - FFT with avg smape 2.34:
Model Number: 2 of 275 with model Cassandra for Validation 2
2 - Cassandra with avg smape 3.34:
Model Number: 3 of 275 with model FFT for Validation 2

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

3 - FFT with avg smape 2.4:
Model Number: 4 of 275 with model FFT for Validation 2
4 - FFT with avg smape 2.4:
Model Number: 5 of 275 with model FFT for Validation 2
5 - FFT with avg smape 2.4:
Model Number: 6 of 275 with model SeasonalityMotif for Validation 2
📈 6 - SeasonalityMotif with avg smape 1.97:
Model Number: 7 of 275 with model SeasonalityMotif for Validation 2
7 - SeasonalityMotif with avg smape 1.97:
Model Number: 8 of 275 with model SeasonalityMotif for Validation 2
8 - SeasonalityMotif with avg smape 1.97:
Model Number: 9 of 275 with model SeasonalityMotif for Validation 2
📈 9 - SeasonalityMotif with avg smape 1.58:
Model Number: 10 of 275 with model SeasonalityMotif for Validation 2
10 - SeasonalityMotif with avg smape 1.58:
Model Number: 11 of 275 with model SeasonalityMotif for Validation 2
11 - SeasonalityMotif with avg smape 1.8:
Model Number: 12 of 275 with model SeasonalityMotif for Validation 2
12 - SeasonalityMotif with avg smape 1.58:
Model Number: 13 of 275 with model SeasonalityMotif for Validation 2
13 - SeasonalityMotif with avg smape 2.02:
Model Number: 14 of 275 with model SeasonalityMotif for Validation 2
14 - SeasonalityMotif with avg smape 2.0:
Model Number: 15 of 275 with model AverageValueNaive for Validation 2
15 - AverageValueNaive with avg smape 3.31:
Model Number: 16 of 275 with model AverageValueNaive for Validation 2
16 - AverageValueNaive with avg smape 3.31:
Model Number: 17 of 275 with model AverageValueNaive for Validation 2
17 - AverageValueNaive with avg smape 3.13:
Model Number: 18 of 275 with model AverageValueNaive for Validation 2
18 - AverageValueNaive with avg smape 3.13:
Model Number: 19 of 275 with model AverageValueNaive for Validation 2
19 - AverageValueNaive with avg smape 3.13:
Model Number: 20 of 275 with model AverageValueNaive for Validation 2
20 - AverageValueNaive with avg smape 3.13:
Model Number: 21 of 275 with model AverageValueNaive for Validation 2
21 - AverageValueNaive with avg smape 3.13:
Model Number: 22 of 275 with model AverageValueNaive for Validation 2
22 - AverageValueNaive with avg smape 3.13:
Model Number: 23 of 275 with model AverageValueNaive for Validation 2
23 - AverageValueNaive with avg smape 3.2:
Model Number: 24 of 275 with model AverageValueNaive for Validation 2
24 - AverageValueNaive with avg smape 3.12:
Model Number: 25 of 275 with model AverageValueNaive for Validation 2
25 - AverageValueNaive with avg smape 3.12:
Model Number: 26 of 275 with model SeasonalNaive for Validation 2
26 - SeasonalNaive with avg smape 2.64:
Model Number: 27 of 275 with model AverageValueNaive for Validation 2
27 - AverageValueNaive with avg smape 3.19:
Model Number: 28 of 275 with model AverageValueNaive for Validation 2
28 - AverageValueNaive with avg smape 3.19:
Model Number: 29 of 275 with model AverageValueNaive for Validation 2
29 - AverageValueNaive with avg smape 3.19:
Model Number: 30 of 275 with model Cassandra for Validation 2
30 - Cassandra with avg smape 4.22:
Model Number: 31 of 275 with model DatepartRegression for Validation 2
31 - DatepartRegression with avg smape 1.78:
Model Number: 32 of 275 with model AverageValueNaive for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

32 - AverageValueNaive with avg smape 3.29:
Model Number: 33 of 275 with model SeasonalityMotif for Validation 2
33 - SeasonalityMotif with avg smape 1.58:
Model Number: 34 of 275 with model FFT for Validation 2
34 - FFT with avg smape 2.28:
Model Number: 35 of 275 with model SeasonalityMotif for Validation 2
35 - SeasonalityMotif with avg smape 1.62:
Model Number: 36 of 275 with model SeasonalityMotif for Validation 2
📈 36 - SeasonalityMotif with avg smape 1.5:
Model Number: 37 of 275 with model FBProphet for Validation 2
37 - FBProphet with avg smape 2.98:
Model Number: 38 of 275 with model FFT for Validation 2
38 - FFT with avg smape 2.36:
Model Number: 39 of 275 with model FBProphet for Validation 2
39 - FBProphet with avg smape 2.96:
Model Number: 40 of 275 with model DatepartRegression for Validation 2
40 - DatepartRegression with avg smape 1.77:
Model Number: 41 of 275 with model DatepartRegression for Validation 2
41 - DatepartRegression with avg smape 1.91:
Model Number: 42 of 275 with model FBProphet for Validation 2
42 - FBProphet with avg smape 3.06:
Model Number: 43 of 275 with model FFT for Validation 2
43 - FFT with avg smape 2.45:
Model Number: 44 of 275 with model FFT for Validation 2
44 - FFT with avg smape 3.02:
Model Number: 45 of 275 with model SeasonalNaive for Validation 2
45 - SeasonalNaive with avg smape 2.9:
Model Number: 46 of 275 with model Cassandra for Validation 2
46 - Cassandra with avg smape 3.73:

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Model Number: 47 of 275 with model FBProphet for Validation 2
47 - FBProphet with avg smape 2.92:
Model Number: 48 of 275 with model SeasonalityMotif for Validation 2
48 - SeasonalityMotif with avg smape 2.71:
Model Number: 49 of 275 with model SeasonalityMotif for Validation 2
49 - SeasonalityMotif with avg smape 1.66:
Model Number: 50 of 275 with model SeasonalNaive for Validation 2
50 - SeasonalNaive with avg smape 2.95:
Model Number: 51 of 275 with model Cassandra for Validation 2
51 - Cassandra with avg smape 1.82:
Model Number: 52 of 275 with model SeasonalityMotif for Validation 2
52 - SeasonalityMotif with avg smape 2.81:
Model Number: 53 of 275 with model BasicLinearModel for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

53 - BasicLinearModel with avg smape 3.21:
Model Number: 54 of 275 with model FBProphet for Validation 2
54 - FBProphet with avg smape 3.18:
Model Number: 55 of 275 with model Cassandra for Validation 2
55 - Cassandra with avg smape 1.78:
Model Number: 56 of 275 with model FFT for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

56 - FFT with avg smape 2.3:
Model Number: 57 of 275 with model FFT for Validation 2
57 - FFT with avg smape 2.3:
Model Number: 58 of 275 with model FFT for Validation 2
58 - FFT with avg smape 2.3:
Model Number: 59 of 275 with model FFT for Validation 2
59 - FFT with avg smape 2.26:
Model Number: 60 of 275 with model FFT for Validation 2
60 - FFT with avg smape 2.26:
Model Number: 61 of 275 with model FFT for Validation 2
61 - FFT with avg smape 2.26:
Model Number: 62 of 275 with model FFT for Validation 2
62 - FFT with avg smape 2.26:
Model Number: 63 of 275 with model SeasonalNaive for Validation 2
63 - SeasonalNaive with avg smape 2.67:
Model Number: 64 of 275 with model Cassandra for Validation 2
64 - Cassandra with avg smape 2.45:
Model Number: 65 of 275 with model SeasonalNaive for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

65 - SeasonalNaive with avg smape 2.71:
Model Number: 66 of 275 with model SeasonalNaive for Validation 2
66 - SeasonalNaive with avg smape 2.71:
Model Number: 67 of 275 with model SeasonalNaive for Validation 2
67 - SeasonalNaive with avg smape 3.09:
Model Number: 68 of 275 with model ARDL for Validation 2
68 - ARDL with avg smape 3.12:
Model Number: 69 of 275 with model ARDL for Validation 2
69 - ARDL with avg smape 3.12:
Model Number: 70 of 275 with model FBProphet for Validation 2
70 - FBProphet with avg smape 3.0:
Model Number: 71 of 275 with model Cassandra for Validation 2
71 - Cassandra with avg smape 3.13:
Model Number: 72 of 275 with model DatepartRegression for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

72 - DatepartRegression with avg smape 3.13:
Model Number: 73 of 275 with model DatepartRegression for Validation 2
73 - DatepartRegression with avg smape 3.13:
Model Number: 74 of 275 with model ARDL for Validation 2
74 - ARDL with avg smape 3.08:
Model Number: 75 of 275 with model ARDL for Validation 2
75 - ARDL with avg smape 3.08:
Model Number: 76 of 275 with model Cassandra for Validation 2
76 - Cassandra with avg smape 2.64:
Model Number: 77 of 275 with model ARDL for Validation 2
77 - ARDL with avg smape 3.08:
Model Number: 78 of 275 with model ARDL for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

78 - ARDL with avg smape 3.08:
Model Number: 79 of 275 with model Cassandra for Validation 2
79 - Cassandra with avg smape 2.49:
Model Number: 80 of 275 with model ARDL for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

80 - ARDL with avg smape 3.12:
Model Number: 81 of 275 with model ARDL for Validation 2
81 - ARDL with avg smape 3.12:
Model Number: 82 of 275 with model ARDL for Validation 2
82 - ARDL with avg smape 3.12:
Model Number: 83 of 275 with model SeasonalNaive for Validation 2
83 - SeasonalNaive with avg smape 3.21:
Model Number: 84 of 275 with model Cassandra for Validation 2
84 - Cassandra with avg smape 2.77:
Model Number: 85 of 275 with model SeasonalNaive for Validation 2
85 - SeasonalNaive with avg smape 3.28:
Model Number: 86 of 275 with model ARDL for Validation 2
86 - ARDL with avg smape 3.11:
Model Number: 87 of 275 with model UnivariateMotif for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

87 - UnivariateMotif with avg smape 2.16:
Model Number: 88 of 275 with model ARDL for Validation 2
88 - ARDL with avg smape 3.09:
Model Number: 89 of 275 with model Cassandra for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.259e+10, tolerance: 3.930e+07

89 - Cassandra with avg smape 1.73:
Model Number: 90 of 275 with model SeasonalNaive for Validation 2
90 - SeasonalNaive with avg smape 1.58:
Model Number: 91 of 275 with model Cassandra for Validation 2
91 - Cassandra with avg smape 2.17:
Model Number: 92 of 275 with model ARDL for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

92 - ARDL with avg smape 3.09:
Model Number: 93 of 275 with model Cassandra for Validation 2
93 - Cassandra with avg smape 4.33:
Model Number: 94 of 275 with model Cassandra for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

94 - Cassandra with avg smape 3.69:
Model Number: 95 of 275 with model Cassandra for Validation 2

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

95 - Cassandra with avg smape 3.54:
Model Number: 96 of 275 with model SeasonalNaive for Validation 2
96 - SeasonalNaive with avg smape 1.91:
Model Number: 97 of 275 with model ARDL for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.259e+10, tolerance: 3.930e+07

97 - ARDL with avg smape 3.11:
Model Number: 98 of 275 with model SeasonalNaive for Validation 2
98 - SeasonalNaive with avg smape 2.81:
Model Number: 99 of 275 with model SeasonalNaive for Validation 2
99 - SeasonalNaive with avg smape 2.8:
Model Number: 100 of 275 with model SeasonalNaive for Validation 2
100 - SeasonalNaive with avg smape 3.76:
Model Number: 101 of 275 with model DatepartRegression for Validation 2
101 - DatepartRegression with avg smape 1.95:
Model Number: 102 of 275 with model BasicLinearModel for Validation 2
102 - BasicLinearModel with avg smape 3.69:
Model Number: 103 of 275 with model BasicLinearModel for Validation 2
103 - BasicLinearModel with avg smape 3.78:
Model Number: 104 of 275 with model SeasonalNaive for Validation 2
104 - SeasonalNaive with avg smape 3.77:
Model Number: 105 of 275 with model ARDL for Validation 2
105 - ARDL with avg smape 1.83:
Model Number: 106 of 275 with model BasicLinearModel for Validation 2
106 - BasicLinearModel with avg smape 2.12:
Model Number: 107 of 275 with model ARDL for Validation 2
107 - ARDL with avg smape 1.63:
Model Number: 108 of 275 with model BasicLinearModel for Validation 2
108 - BasicLinearModel with avg smape 2.4:
Model Number: 109 of 275 with model BasicLinearModel for Validation 2
109 - BasicLinearModel with avg smape 1.83:
Model Number: 110 of 275 with model BasicLinearModel for Validation 2
110 - BasicLinearModel with avg smape 1.81:
Model Number: 111 of 275 with model ETS for Validation 2
111 - ETS with avg smape 1.61:
Model Number: 112 of 275 with model ETS for Validation 2
112 - ETS with avg smape 1.61:
Model Number: 113 of 275 with model GLS for Validation 2
113 - GLS with avg smape 2.0:
Model Number: 114 of 275 with model GLS for Validation 2
114 - GLS with avg smape 2.0:
Model Number: 115 of 275 with model GLS for Validation 2

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

115 - GLS with avg smape 2.0:
Model Number: 116 of 275 with model GLS for Validation 2
116 - GLS with avg smape 2.01:
Model Number: 117 of 275 with model BasicLinearModel for Validation 2
117 - BasicLinearModel with avg smape 3.57:
Model Number: 118 of 275 with model GLS for Validation 2
118 - GLS with avg smape 2.0:
Model Number: 119 of 275 with model GLS for Validation 2
119 - GLS with avg smape 2.0:
Model Number: 120 of 275 with model GLS for Validation 2
120 - GLS with avg smape 2.0:
Model Number: 121 of 275 with model GLS for Validation 2
121 - GLS with avg smape 2.0:
Model Number: 122 of 275 with model DatepartRegression for Validation 2

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

122 - DatepartRegression with avg smape 2.82:
Model Number: 123 of 275 with model BasicLinearModel for Validation 2
123 - BasicLinearModel with avg smape 2.69:
Model Number: 124 of 275 with model DatepartRegression for Validation 2
124 - DatepartRegression with avg smape 1.7:
Model Number: 125 of 275 with model BasicLinearModel for Validation 2
125 - BasicLinearModel with avg smape 2.5:
Model Number: 126 of 275 with model BasicLinearModel for Validation 2
126 - BasicLinearModel with avg smape 2.5:
Model Number: 127 of 275 with model BasicLinearModel for Validation 2
127 - BasicLinearModel with avg smape 2.5:
Model Number: 128 of 275 with model BasicLinearModel for Validation 2
128 - BasicLinearModel with avg smape 2.24:
Model Number: 129 of 275 with model BasicLinearModel for Validation 2
129 - BasicLinearModel with avg smape 2.59:
Model Number: 130 of 275 with model ETS for Validation 2
130 - ETS with avg smape 2.01:
Model Number: 131 of 275 with model FBProphet for Validation 2
131 - FBProphet with avg smape 2.39:
Model Number: 132 of 275 with model ETS for Validation 2
132 - ETS with avg smape 2.0:
Model Number: 133 of 275 with model ETS for Validation 2
133 - ETS with avg smape 2.0:
Model Number: 134 of 275 with model ETS for Validation 2
134 - ETS with avg smape 2.0:
Model Number: 135 of 275 with model FBProphet for Validation 2
135 - FBProphet with avg smape 2.39:
Model Number: 136 of 275 with model FBProphet for Validation 2
136 - FBProphet with avg smape 3.03:
Model Number: 137 of 275 with model FBProphet for Validation 2
137 - FBProphet with avg smape 2.39:
Model Number: 138 of 275 with model FBProphet for Validation 2
138 - FBProphet with avg smape 2.39:
Model Number: 139 of 275 with model GLS for Validation 2
139 - GLS with avg smape 2.02:
Model Number: 140 of 275 with model GLS for Validation 2
140 - GLS with avg smape 2.02:
Model Number: 141 of 275 with model GLS for Validation 2
141 - GLS with avg smape 2.02:
Model Number: 142 of 275 with model GLS for Validation 2
142 - GLS with avg smape 2.02:
Model Number: 143 of 275 with model GLS for Validation 2
143 - GLS with avg smape 2.02:
Model Number: 144 of 275 with model GLS for Validation 2
144 - GLS with avg smape 2.02:
Model Number: 145 of 275 with model ETS for Validation 2
145 - ETS with avg smape 2.01:
Model Number: 146 of 275 with model ETS for Validation 2
146 - ETS with avg smape 2.01:
Model Number: 147 of 275 with model DatepartRegression for Validation 2
147 - DatepartRegression with avg smape 2.12:
Model Number: 148 of 275 with model GLS for Validation 2
148 - GLS with avg smape 2.0:
Model Number: 149 of 275 with model FBProphet for Validation 2

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

149 - FBProphet with avg smape 1.98:
Model Number: 150 of 275 with model DatepartRegression for Validation 2

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

150 - DatepartRegression with avg smape 2.0:
Model Number: 151 of 275 with model DatepartRegression for Validation 2
151 - DatepartRegression with avg smape 2.0:
Model Number: 152 of 275 with model DatepartRegression for Validation 2
152 - DatepartRegression with avg smape 2.0:
Model Number: 153 of 275 with model DatepartRegression for Validation 2
153 - DatepartRegression with avg smape 2.0:
Model Number: 154 of 275 with model ETS for Validation 2
154 - ETS with avg smape 2.0:
Model Number: 155 of 275 with model ETS for Validation 2
155 - ETS with avg smape 2.0:
Model Number: 156 of 275 with model GLM for Validation 2
156 - GLM with avg smape 2.0:
Model Number: 157 of 275 with model GLM for Validation 2
157 - GLM with avg smape 2.0:
Model Number: 158 of 275 with model GLM for Validation 2
158 - GLM with avg smape 2.0:
Model Number: 159 of 275 with model GLM for Validation 2
159 - GLM with avg smape 2.0:
Model Number: 160 of 275 with model GLM for Validation 2
160 - GLM with avg smape 2.0:
Model Number: 161 of 275 with model GLM for Validation 2
161 - GLM with avg smape 2.0:
Model Number: 162 of 275 with model GLM for Validation 2

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

162 - GLM with avg smape 2.0:
Model Number: 163 of 275 with model GLM for Validation 2
163 - GLM with avg smape 2.0:
Model Number: 164 of 275 with model ETS for Validation 2
164 - ETS with avg smape 2.0:

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 165 of 275 with model GLM for Validation 2
165 - GLM with avg smape 2.0:
Model Number: 166 of 275 with model DatepartRegression for Validation 2
166 - DatepartRegression with avg smape 1.8:
Model Number: 167 of 275 with model DatepartRegression for Validation 2
167 - DatepartRegression with avg smape 2.0:
Model Number: 168 of 275 with model ETS for Validation 2
168 - ETS with avg smape 2.0:
Model Number: 169 of 275 with model ETS for Validation 2
169 - ETS with avg smape 2.11:
Model Number: 170 of 275 with model ETS for Validation 2
170 - ETS with avg smape 2.11:
Model Number: 171 of 275 with model GLM for Validation 2
171 - GLM with avg smape 2.0:
Model Number: 172 of 275 with model ETS for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

172 - ETS with avg smape 2.0:
Model Number: 173 of 275 with model BasicLinearModel for Validation 2
173 - BasicLinearModel with avg smape 1.87:
Model Number: 174 of 275 with model SectionalMotif for Validation 2
174 - SectionalMotif with avg smape 2.77:
Model Number: 175 of 275 with model FBProphet for Validation 2
175 - FBProphet with avg smape 2.16:
Model Number: 176 of 275 with model FBProphet for Validation 2
176 - FBProphet with avg smape 2.16:
Model Number: 177 of 275 with model RRVAR for Validation 2
177 - RRVAR with avg smape 1.88:
Model Number: 178 of 275 with model RRVAR for Validation 2
178 - RRVAR with avg smape 1.88:
Model Number: 179 of 275 with model FBProphet for Validation 2
179 - FBProphet with avg smape 2.13:
Model Number: 180 of 275 with model LastValueNaive for Validation 2
180 - LastValueNaive with avg smape 2.2:
Model Number: 181 of 275 with model GLM for Validation 2
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 181 in generation 0: GLM
Model Number: 182 of 275 with model UnivariateMotif for Validation 2
182 - UnivariateMotif with avg smape 2.22:
Model Number: 183 of 275 with model GLM for Validation 2

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:308: DomainWarning:

The InversePower link function does not respect the domain of the Gamma family.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

overflow encountered in square

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:325: RuntimeWarning:

divide by zero encountered in power

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:775: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:1328: RuntimeWarning:

invalid value encountered in multiply

183 - GLM with avg smape 2.01:
Model Number: 184 of 275 with model GLM for Validation 2
184 - GLM with avg smape 2.01:
Model Number: 185 of 275 with model GLM for Validation 2

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

185 - GLM with avg smape 2.01:
Model Number: 186 of 275 with model GLM for Validation 2
186 - GLM with avg smape 2.01:
Model Number: 187 of 275 with model LastValueNaive for Validation 2
187 - LastValueNaive with avg smape 2.13:
Model Number: 188 of 275 with model LastValueNaive for Validation 2
188 - LastValueNaive with avg smape 2.13:

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

Model Number: 189 of 275 with model LastValueNaive for Validation 2
189 - LastValueNaive with avg smape 2.13:
Model Number: 190 of 275 with model LastValueNaive for Validation 2
190 - LastValueNaive with avg smape 2.13:
Model Number: 191 of 275 with model LastValueNaive for Validation 2
191 - LastValueNaive with avg smape 2.13:
Model Number: 192 of 275 with model LastValueNaive for Validation 2
192 - LastValueNaive with avg smape 2.13:
Model Number: 193 of 275 with model LastValueNaive for Validation 2
193 - LastValueNaive with avg smape 3.04:
Model Number: 194 of 275 with model LastValueNaive for Validation 2
194 - LastValueNaive with avg smape 1.66:
Model Number: 195 of 275 with model LastValueNaive for Validation 2
195 - LastValueNaive with avg smape 1.66:
Model Number: 196 of 275 with model LastValueNaive for Validation 2
196 - LastValueNaive with avg smape 1.66:
Model Number: 197 of 275 with model LastValueNaive for Validation 2
197 - LastValueNaive with avg smape 1.66:
Model Number: 198 of 275 with model LastValueNaive for Validation 2
198 - LastValueNaive with avg smape 1.66:
Model Number: 199 of 275 with model LastValueNaive for Validation 2
199 - LastValueNaive with avg smape 1.67:
Model Number: 200 of 275 with model SectionalMotif for Validation 2
200 - SectionalMotif with avg smape 1.65:
Model Number: 201 of 275 with model SectionalMotif for Validation 2
201 - SectionalMotif with avg smape 10.5:
Model Number: 202 of 275 with model SectionalMotif for Validation 2
202 - SectionalMotif with avg smape 1.95:
Model Number: 203 of 275 with model UnivariateMotif for Validation 2
203 - UnivariateMotif with avg smape 2.29:
Model Number: 204 of 275 with model RRVAR for Validation 2
204 - RRVAR with avg smape 3.24:
Model Number: 205 of 275 with model UnivariateMotif for Validation 2
205 - UnivariateMotif with avg smape 3.19:
Model Number: 206 of 275 with model UnivariateMotif for Validation 2
206 - UnivariateMotif with avg smape 7.51:
Model Number: 207 of 275 with model UnivariateMotif for Validation 2
207 - UnivariateMotif with avg smape 2.06:
Model Number: 208 of 275 with model UnivariateMotif for Validation 2
208 - UnivariateMotif with avg smape 1.5:
Model Number: 209 of 275 with model MetricMotif for Validation 2
209 - MetricMotif with avg smape 1.92:
Model Number: 210 of 275 with model UnivariateMotif for Validation 2
📈 210 - UnivariateMotif with avg smape 1.48:
Model Number: 211 of 275 with model MetricMotif for Validation 2
211 - MetricMotif with avg smape 3.08:
Model Number: 212 of 275 with model SectionalMotif for Validation 2
212 - SectionalMotif with avg smape 2.26:
Model Number: 213 of 275 with model SectionalMotif for Validation 2
213 - SectionalMotif with avg smape 3.21:
Model Number: 214 of 275 with model ConstantNaive for Validation 2
214 - ConstantNaive with avg smape 1.72:
Model Number: 215 of 275 with model UnivariateMotif for Validation 2
215 - UnivariateMotif with avg smape 2.19:
Model Number: 216 of 275 with model UnivariateMotif for Validation 2
216 - UnivariateMotif with avg smape 2.47:
Model Number: 217 of 275 with model MetricMotif for Validation 2
217 - MetricMotif with avg smape 2.67:
Model Number: 218 of 275 with model MetricMotif for Validation 2
218 - MetricMotif with avg smape 1.88:
Model Number: 219 of 275 with model SectionalMotif for Validation 2
219 - SectionalMotif with avg smape 18.46:
Model Number: 220 of 275 with model SectionalMotif for Validation 2
220 - SectionalMotif with avg smape 1.92:
Model Number: 221 of 275 with model SectionalMotif for Validation 2
221 - SectionalMotif with avg smape 3.4:
Model Number: 222 of 275 with model ConstantNaive for Validation 2
222 - ConstantNaive with avg smape 2.0:
Model Number: 223 of 275 with model MetricMotif for Validation 2
223 - MetricMotif with avg smape 2.23:
Model Number: 224 of 275 with model MetricMotif for Validation 2
224 - MetricMotif with avg smape 11.2:
Model Number: 225 of 275 with model SectionalMotif for Validation 2
225 - SectionalMotif with avg smape 2.99:
Model Number: 226 of 275 with model UnivariateMotif for Validation 2
226 - UnivariateMotif with avg smape 2.87:
Model Number: 227 of 275 with model MetricMotif for Validation 2
227 - MetricMotif with avg smape 2.19:
Model Number: 228 of 275 with model SectionalMotif for Validation 2
228 - SectionalMotif with avg smape 3.19:
Model Number: 229 of 275 with model ConstantNaive for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

229 - ConstantNaive with avg smape 1.68:
Model Number: 230 of 275 with model ConstantNaive for Validation 2
230 - ConstantNaive with avg smape 1.68:
Model Number: 231 of 275 with model MetricMotif for Validation 2
231 - MetricMotif with avg smape 2.59:
Model Number: 232 of 275 with model SectionalMotif for Validation 2
232 - SectionalMotif with avg smape 8.12:
Model Number: 233 of 275 with model SectionalMotif for Validation 2
233 - SectionalMotif with avg smape 2.4:
Model Number: 234 of 275 with model LastValueNaive for Validation 2
234 - LastValueNaive with avg smape 2.15:
Model Number: 235 of 275 with model SectionalMotif for Validation 2
235 - SectionalMotif with avg smape 3.01:
Model Number: 236 of 275 with model MetricMotif for Validation 2
236 - MetricMotif with avg smape 12.39:
Model Number: 237 of 275 with model SectionalMotif for Validation 2
237 - SectionalMotif with avg smape 2.5:
Model Number: 238 of 275 with model UnivariateMotif for Validation 2
📈 238 - UnivariateMotif with avg smape 1.31:
Model Number: 239 of 275 with model UnivariateMotif for Validation 2
239 - UnivariateMotif with avg smape 2.24:
Model Number: 240 of 275 with model ConstantNaive for Validation 2
240 - ConstantNaive with avg smape 2.25:
Model Number: 241 of 275 with model MetricMotif for Validation 2
241 - MetricMotif with avg smape 40.35:
Model Number: 242 of 275 with model UnivariateMotif for Validation 2
242 - UnivariateMotif with avg smape 8.8:
Model Number: 243 of 275 with model UnivariateMotif for Validation 2
243 - UnivariateMotif with avg smape 6.28:
Model Number: 244 of 275 with model MetricMotif for Validation 2
244 - MetricMotif with avg smape 2.75:
Model Number: 245 of 275 with model MetricMotif for Validation 2
245 - MetricMotif with avg smape 30.97:
Model Number: 246 of 275 with model ConstantNaive for Validation 2
246 - ConstantNaive with avg smape 31.13:
Model Number: 247 of 275 with model ConstantNaive for Validation 2
247 - ConstantNaive with avg smape 2.84:
Model Number: 248 of 275 with model MetricMotif for Validation 2
248 - MetricMotif with avg smape 53.96:
Model Number: 249 of 275 with model ConstantNaive for Validation 2
249 - ConstantNaive with avg smape 30.89:
Model Number: 250 of 275 with model ConstantNaive for Validation 2
250 - ConstantNaive with avg smape 27.49:
Model Number: 251 of 275 with model ConstantNaive for Validation 2
251 - ConstantNaive with avg smape 2.15:
Model Number: 252 of 275 with model MetricMotif for Validation 2
252 - MetricMotif with avg smape 2.15:
Model Number: 253 of 275 with model ConstantNaive for Validation 2
253 - ConstantNaive with avg smape 2.15:
Model Number: 254 of 275 with model ConstantNaive for Validation 2
254 - ConstantNaive with avg smape 1.84:
Model Number: 255 of 275 with model VAR for Validation 2
255 - VAR with avg smape 1.48:
Model Number: 256 of 275 with model MetricMotif for Validation 2
256 - MetricMotif with avg smape 2.31:
Model Number: 257 of 275 with model ConstantNaive for Validation 2
257 - ConstantNaive with avg smape 2.37:
Model Number: 258 of 275 with model ConstantNaive for Validation 2
258 - ConstantNaive with avg smape 2.16:
Model Number: 259 of 275 with model ConstantNaive for Validation 2
259 - ConstantNaive with avg smape 5.65:
Model Number: 260 of 275 with model RRVAR for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

260 - RRVAR with avg smape 3.13:
Model Number: 261 of 275 with model RRVAR for Validation 2
261 - RRVAR with avg smape 1.94:
Model Number: 262 of 275 with model WindowRegression for Validation 2
262 - WindowRegression with avg smape 10.03:
Model Number: 263 of 275 with model RRVAR for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

263 - RRVAR with avg smape 1.53:
Model Number: 264 of 275 with model RRVAR for Validation 2
264 - RRVAR with avg smape 1.41:
Model Number: 265 of 275 with model RRVAR for Validation 2
265 - RRVAR with avg smape 1.93:
Model Number: 266 of 275 with model RRVAR for Validation 2
266 - RRVAR with avg smape 1.75:
Model Number: 267 of 275 with model RRVAR for Validation 2
267 - RRVAR with avg smape 1.53:
Model Number: 268 of 275 with model RRVAR for Validation 2
268 - RRVAR with avg smape 1.52:
Model Number: 269 of 275 with model RRVAR for Validation 2
269 - RRVAR with avg smape 5.16:
Model Number: 270 of 275 with model WindowRegression for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

270 - WindowRegression with avg smape 29.14:
Model Number: 271 of 275 with model RRVAR for Validation 2
271 - RRVAR with avg smape 6.0:
Model Number: 272 of 275 with model WindowRegression for Validation 2
272 - WindowRegression with avg smape 62.19:
Model Number: 273 of 275 with model RRVAR for Validation 2

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.57282e-25): result may not be accurate.

273 - RRVAR with avg smape 17.3:
Model Number: 274 of 275 with model WindowRegression for Validation 2
Epoch 1/10

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:151: DeprecationWarning:

datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 2024.7404
Epoch 2/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 455.6850
Epoch 3/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 277.1457
Epoch 4/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 193.9952
Epoch 5/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 112.5932
Epoch 6/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 51.2313
Epoch 7/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 21.4915
Epoch 8/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 10.6285
Epoch 9/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.0514
Epoch 10/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 4.6072

WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7e76e486f7e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step
274 - WindowRegression with avg smape 64.14:
Model Number: 275 of 275 with model RRVAR for Validation 2
275 - RRVAR with avg smape 199.46:
Validation Round: 3
Model Number: 1 of 275 with model FFT for Validation 3
📈 1 - FFT with avg smape 4.66:
Model Number: 2 of 275 with model Cassandra for Validation 3

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

📈 2 - Cassandra with avg smape 3.73:
Model Number: 3 of 275 with model FFT for Validation 3
3 - FFT with avg smape 4.72:
Model Number: 4 of 275 with model FFT for Validation 3
4 - FFT with avg smape 4.72:
Model Number: 5 of 275 with model FFT for Validation 3
5 - FFT with avg smape 4.75:
Model Number: 6 of 275 with model SeasonalityMotif for Validation 3
6 - SeasonalityMotif with avg smape 4.48:
Model Number: 7 of 275 with model SeasonalityMotif for Validation 3
7 - SeasonalityMotif with avg smape 4.35:
Model Number: 8 of 275 with model SeasonalityMotif for Validation 3
8 - SeasonalityMotif with avg smape 4.35:
Model Number: 9 of 275 with model SeasonalityMotif for Validation 3
9 - SeasonalityMotif with avg smape 4.34:
Model Number: 10 of 275 with model SeasonalityMotif for Validation 3
10 - SeasonalityMotif with avg smape 4.34:
Model Number: 11 of 275 with model SeasonalityMotif for Validation 3
11 - SeasonalityMotif with avg smape 4.53:
Model Number: 12 of 275 with model SeasonalityMotif for Validation 3
📈 12 - SeasonalityMotif with avg smape 3.42:
Model Number: 13 of 275 with model SeasonalityMotif for Validation 3
13 - SeasonalityMotif with avg smape 4.2:
Model Number: 14 of 275 with model SeasonalityMotif for Validation 3
14 - SeasonalityMotif with avg smape 4.19:
Model Number: 15 of 275 with model AverageValueNaive for Validation 3
15 - AverageValueNaive with avg smape 4.38:
Model Number: 16 of 275 with model AverageValueNaive for Validation 3
16 - AverageValueNaive with avg smape 4.38:
Model Number: 17 of 275 with model AverageValueNaive for Validation 3
17 - AverageValueNaive with avg smape 3.94:
Model Number: 18 of 275 with model AverageValueNaive for Validation 3
18 - AverageValueNaive with avg smape 3.94:
Model Number: 19 of 275 with model AverageValueNaive for Validation 3
19 - AverageValueNaive with avg smape 3.94:
Model Number: 20 of 275 with model AverageValueNaive for Validation 3
20 - AverageValueNaive with avg smape 4.0:
Model Number: 21 of 275 with model AverageValueNaive for Validation 3
21 - AverageValueNaive with avg smape 4.0:
Model Number: 22 of 275 with model AverageValueNaive for Validation 3
22 - AverageValueNaive with avg smape 4.0:
Model Number: 23 of 275 with model AverageValueNaive for Validation 3
23 - AverageValueNaive with avg smape 3.96:
Model Number: 24 of 275 with model AverageValueNaive for Validation 3
24 - AverageValueNaive with avg smape 4.09:
Model Number: 25 of 275 with model AverageValueNaive for Validation 3
25 - AverageValueNaive with avg smape 4.09:
Model Number: 26 of 275 with model SeasonalNaive for Validation 3
26 - SeasonalNaive with avg smape 3.9:
Model Number: 27 of 275 with model AverageValueNaive for Validation 3
27 - AverageValueNaive with avg smape 4.12:
Model Number: 28 of 275 with model AverageValueNaive for Validation 3
28 - AverageValueNaive with avg smape 4.12:
Model Number: 29 of 275 with model AverageValueNaive for Validation 3
29 - AverageValueNaive with avg smape 4.12:
Model Number: 30 of 275 with model Cassandra for Validation 3

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

30 - Cassandra with avg smape 4.2:
Model Number: 31 of 275 with model DatepartRegression for Validation 3
31 - DatepartRegression with avg smape 4.7:
Model Number: 32 of 275 with model AverageValueNaive for Validation 3
32 - AverageValueNaive with avg smape 4.03:
Model Number: 33 of 275 with model SeasonalityMotif for Validation 3
33 - SeasonalityMotif with avg smape 4.51:
Model Number: 34 of 275 with model FFT for Validation 3
34 - FFT with avg smape 4.02:
Model Number: 35 of 275 with model SeasonalityMotif for Validation 3
35 - SeasonalityMotif with avg smape 4.08:
Model Number: 36 of 275 with model SeasonalityMotif for Validation 3
36 - SeasonalityMotif with avg smape 4.76:
Model Number: 37 of 275 with model FBProphet for Validation 3
37 - FBProphet with avg smape 3.93:
Model Number: 38 of 275 with model FFT for Validation 3
38 - FFT with avg smape 3.99:
Model Number: 39 of 275 with model FBProphet for Validation 3
39 - FBProphet with avg smape 3.93:
Model Number: 40 of 275 with model DatepartRegression for Validation 3
40 - DatepartRegression with avg smape 4.78:
Model Number: 41 of 275 with model DatepartRegression for Validation 3
41 - DatepartRegression with avg smape 4.68:
Model Number: 42 of 275 with model FBProphet for Validation 3
42 - FBProphet with avg smape 3.95:
Model Number: 43 of 275 with model FFT for Validation 3
43 - FFT with avg smape 5.43:
Model Number: 44 of 275 with model FFT for Validation 3
44 - FFT with avg smape 4.35:
Model Number: 45 of 275 with model SeasonalNaive for Validation 3
45 - SeasonalNaive with avg smape 3.95:
Model Number: 46 of 275 with model Cassandra for Validation 3
46 - Cassandra with avg smape 4.27:
Model Number: 47 of 275 with model FBProphet for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

47 - FBProphet with avg smape 3.81:
Model Number: 48 of 275 with model SeasonalityMotif for Validation 3
48 - SeasonalityMotif with avg smape 4.04:
Model Number: 49 of 275 with model SeasonalityMotif for Validation 3
49 - SeasonalityMotif with avg smape 3.9:
Model Number: 50 of 275 with model SeasonalNaive for Validation 3
50 - SeasonalNaive with avg smape 3.96:
Model Number: 51 of 275 with model Cassandra for Validation 3
51 - Cassandra with avg smape 4.61:
Model Number: 52 of 275 with model SeasonalityMotif for Validation 3
52 - SeasonalityMotif with avg smape 4.0:
Model Number: 53 of 275 with model BasicLinearModel for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

53 - BasicLinearModel with avg smape 4.58:
Model Number: 54 of 275 with model FBProphet for Validation 3
54 - FBProphet with avg smape 4.19:
Model Number: 55 of 275 with model Cassandra for Validation 3
55 - Cassandra with avg smape 4.3:
Model Number: 56 of 275 with model FFT for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

56 - FFT with avg smape 4.64:
Model Number: 57 of 275 with model FFT for Validation 3
57 - FFT with avg smape 4.64:
Model Number: 58 of 275 with model FFT for Validation 3
58 - FFT with avg smape 4.64:
Model Number: 59 of 275 with model FFT for Validation 3
59 - FFT with avg smape 4.57:
Model Number: 60 of 275 with model FFT for Validation 3
60 - FFT with avg smape 4.57:
Model Number: 61 of 275 with model FFT for Validation 3
61 - FFT with avg smape 4.57:
Model Number: 62 of 275 with model FFT for Validation 3
62 - FFT with avg smape 4.57:
Model Number: 63 of 275 with model SeasonalNaive for Validation 3
63 - SeasonalNaive with avg smape 3.91:
Model Number: 64 of 275 with model Cassandra for Validation 3
64 - Cassandra with avg smape 4.33:
Model Number: 65 of 275 with model SeasonalNaive for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

65 - SeasonalNaive with avg smape 3.92:
Model Number: 66 of 275 with model SeasonalNaive for Validation 3
66 - SeasonalNaive with avg smape 3.92:
Model Number: 67 of 275 with model SeasonalNaive for Validation 3
67 - SeasonalNaive with avg smape 3.91:
Model Number: 68 of 275 with model ARDL for Validation 3
68 - ARDL with avg smape 3.81:
Model Number: 69 of 275 with model ARDL for Validation 3
69 - ARDL with avg smape 3.81:
Model Number: 70 of 275 with model FBProphet for Validation 3
70 - FBProphet with avg smape 4.27:
Model Number: 71 of 275 with model Cassandra for Validation 3
71 - Cassandra with avg smape 3.59:
Model Number: 72 of 275 with model DatepartRegression for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

72 - DatepartRegression with avg smape 3.94:
Model Number: 73 of 275 with model DatepartRegression for Validation 3
73 - DatepartRegression with avg smape 3.94:
Model Number: 74 of 275 with model ARDL for Validation 3
74 - ARDL with avg smape 3.79:
Model Number: 75 of 275 with model ARDL for Validation 3
75 - ARDL with avg smape 3.79:
Model Number: 76 of 275 with model Cassandra for Validation 3
76 - Cassandra with avg smape 4.32:
Model Number: 77 of 275 with model ARDL for Validation 3
77 - ARDL with avg smape 3.82:
Model Number: 78 of 275 with model ARDL for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

78 - ARDL with avg smape 3.82:
Model Number: 79 of 275 with model Cassandra for Validation 3
79 - Cassandra with avg smape 4.73:
Model Number: 80 of 275 with model ARDL for Validation 3
80 - ARDL with avg smape 3.8:
Model Number: 81 of 275 with model ARDL for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

81 - ARDL with avg smape 3.8:
Model Number: 82 of 275 with model ARDL for Validation 3
82 - ARDL with avg smape 3.97:
Model Number: 83 of 275 with model SeasonalNaive for Validation 3
83 - SeasonalNaive with avg smape 3.42:
Model Number: 84 of 275 with model Cassandra for Validation 3
84 - Cassandra with avg smape 4.98:
Model Number: 85 of 275 with model SeasonalNaive for Validation 3
85 - SeasonalNaive with avg smape 3.45:
Model Number: 86 of 275 with model ARDL for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

86 - ARDL with avg smape 3.79:
Model Number: 87 of 275 with model UnivariateMotif for Validation 3
87 - UnivariateMotif with avg smape 3.65:
Model Number: 88 of 275 with model ARDL for Validation 3
88 - ARDL with avg smape 3.82:
Model Number: 89 of 275 with model Cassandra for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.222e+10, tolerance: 3.438e+07

89 - Cassandra with avg smape 4.29:
Model Number: 90 of 275 with model SeasonalNaive for Validation 3
90 - SeasonalNaive with avg smape 4.07:
Model Number: 91 of 275 with model Cassandra for Validation 3
91 - Cassandra with avg smape 3.82:
Model Number: 92 of 275 with model ARDL for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

92 - ARDL with avg smape 3.8:
Model Number: 93 of 275 with model Cassandra for Validation 3
93 - Cassandra with avg smape 4.34:
Model Number: 94 of 275 with model Cassandra for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

94 - Cassandra with avg smape 3.82:
Model Number: 95 of 275 with model Cassandra for Validation 3

/usr/local/lib/python3.12/dist-packages/autots/tools/percentile.py:47: RuntimeWarning:

All-NaN slice encountered

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

95 - Cassandra with avg smape 4.13:
Model Number: 96 of 275 with model SeasonalNaive for Validation 3
96 - SeasonalNaive with avg smape 4.03:
Model Number: 97 of 275 with model ARDL for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.222e+10, tolerance: 3.438e+07

97 - ARDL with avg smape 3.98:
Model Number: 98 of 275 with model SeasonalNaive for Validation 3
98 - SeasonalNaive with avg smape 5.67:
Model Number: 99 of 275 with model SeasonalNaive for Validation 3
99 - SeasonalNaive with avg smape 5.74:
Model Number: 100 of 275 with model SeasonalNaive for Validation 3
100 - SeasonalNaive with avg smape 3.98:
Model Number: 101 of 275 with model DatepartRegression for Validation 3
101 - DatepartRegression with avg smape 3.66:
Model Number: 102 of 275 with model BasicLinearModel for Validation 3
102 - BasicLinearModel with avg smape 5.46:
Model Number: 103 of 275 with model BasicLinearModel for Validation 3
103 - BasicLinearModel with avg smape 5.47:
Model Number: 104 of 275 with model SeasonalNaive for Validation 3
104 - SeasonalNaive with avg smape 3.84:
Model Number: 105 of 275 with model ARDL for Validation 3
105 - ARDL with avg smape 8.19:
Model Number: 106 of 275 with model BasicLinearModel for Validation 3
106 - BasicLinearModel with avg smape 4.59:
Model Number: 107 of 275 with model ARDL for Validation 3
📈 107 - ARDL with avg smape 2.69:
Model Number: 108 of 275 with model BasicLinearModel for Validation 3
108 - BasicLinearModel with avg smape 5.47:
Model Number: 109 of 275 with model BasicLinearModel for Validation 3
109 - BasicLinearModel with avg smape 4.94:
Model Number: 110 of 275 with model BasicLinearModel for Validation 3
110 - BasicLinearModel with avg smape 4.93:
Model Number: 111 of 275 with model ETS for Validation 3
111 - ETS with avg smape 3.73:
Model Number: 112 of 275 with model ETS for Validation 3
112 - ETS with avg smape 3.73:
Model Number: 113 of 275 with model GLS for Validation 3
113 - GLS with avg smape 3.86:
Model Number: 114 of 275 with model GLS for Validation 3

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

114 - GLS with avg smape 3.86:
Model Number: 115 of 275 with model GLS for Validation 3
115 - GLS with avg smape 3.86:
Model Number: 116 of 275 with model GLS for Validation 3

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

116 - GLS with avg smape 3.87:
Model Number: 117 of 275 with model BasicLinearModel for Validation 3
117 - BasicLinearModel with avg smape 4.72:
Model Number: 118 of 275 with model GLS for Validation 3
118 - GLS with avg smape 3.87:
Model Number: 119 of 275 with model GLS for Validation 3
119 - GLS with avg smape 3.87:
Model Number: 120 of 275 with model GLS for Validation 3
120 - GLS with avg smape 3.86:
Model Number: 121 of 275 with model GLS for Validation 3

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/filters/hp_filter.py:100: SparseEfficiencyWarning:

spsolve requires A be CSC or CSR matrix format

121 - GLS with avg smape 3.86:
Model Number: 122 of 275 with model DatepartRegression for Validation 3
122 - DatepartRegression with avg smape 4.4:
Model Number: 123 of 275 with model BasicLinearModel for Validation 3
123 - BasicLinearModel with avg smape 4.69:
Model Number: 124 of 275 with model DatepartRegression for Validation 3
124 - DatepartRegression with avg smape 3.93:
Model Number: 125 of 275 with model BasicLinearModel for Validation 3
125 - BasicLinearModel with avg smape 4.88:
Model Number: 126 of 275 with model BasicLinearModel for Validation 3
126 - BasicLinearModel with avg smape 4.89:
Model Number: 127 of 275 with model BasicLinearModel for Validation 3
127 - BasicLinearModel with avg smape 4.89:
Model Number: 128 of 275 with model BasicLinearModel for Validation 3
128 - BasicLinearModel with avg smape 4.74:
Model Number: 129 of 275 with model BasicLinearModel for Validation 3
129 - BasicLinearModel with avg smape 4.78:
Model Number: 130 of 275 with model ETS for Validation 3
130 - ETS with avg smape 3.87:
Model Number: 131 of 275 with model FBProphet for Validation 3
131 - FBProphet with avg smape 4.95:
Model Number: 132 of 275 with model ETS for Validation 3
132 - ETS with avg smape 3.87:
Model Number: 133 of 275 with model ETS for Validation 3
133 - ETS with avg smape 3.87:
Model Number: 134 of 275 with model ETS for Validation 3
134 - ETS with avg smape 3.87:
Model Number: 135 of 275 with model FBProphet for Validation 3
135 - FBProphet with avg smape 4.95:
Model Number: 136 of 275 with model FBProphet for Validation 3
136 - FBProphet with avg smape 3.76:
Model Number: 137 of 275 with model FBProphet for Validation 3
137 - FBProphet with avg smape 4.95:
Model Number: 138 of 275 with model FBProphet for Validation 3
138 - FBProphet with avg smape 4.95:
Model Number: 139 of 275 with model GLS for Validation 3
139 - GLS with avg smape 3.87:
Model Number: 140 of 275 with model GLS for Validation 3
140 - GLS with avg smape 3.87:
Model Number: 141 of 275 with model GLS for Validation 3
141 - GLS with avg smape 3.87:
Model Number: 142 of 275 with model GLS for Validation 3
142 - GLS with avg smape 3.87:
Model Number: 143 of 275 with model GLS for Validation 3
143 - GLS with avg smape 3.87:
Model Number: 144 of 275 with model GLS for Validation 3
144 - GLS with avg smape 3.87:
Model Number: 145 of 275 with model ETS for Validation 3
145 - ETS with avg smape 3.87:
Model Number: 146 of 275 with model ETS for Validation 3
146 - ETS with avg smape 3.87:
Model Number: 147 of 275 with model DatepartRegression for Validation 3
147 - DatepartRegression with avg smape 3.89:
Model Number: 148 of 275 with model GLS for Validation 3
148 - GLS with avg smape 3.87:
Model Number: 149 of 275 with model FBProphet for Validation 3

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

149 - FBProphet with avg smape 3.86:
Model Number: 150 of 275 with model DatepartRegression for Validation 3

/usr/local/lib/python3.12/dist-packages/prophet/forecaster.py:536: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

150 - DatepartRegression with avg smape 3.87:
Model Number: 151 of 275 with model DatepartRegression for Validation 3
151 - DatepartRegression with avg smape 3.87:
Model Number: 152 of 275 with model DatepartRegression for Validation 3
152 - DatepartRegression with avg smape 3.87:
Model Number: 153 of 275 with model DatepartRegression for Validation 3
153 - DatepartRegression with avg smape 3.87:
Model Number: 154 of 275 with model ETS for Validation 3
154 - ETS with avg smape 3.87:
Model Number: 155 of 275 with model ETS for Validation 3
155 - ETS with avg smape 3.87:
Model Number: 156 of 275 with model GLM for Validation 3
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 156 in generation 0: GLM
Model Number: 157 of 275 with model GLM for Validation 3
157 - GLM with avg smape 3.87:
Model Number: 158 of 275 with model GLM for Validation 3
158 - GLM with avg smape 3.87:
Model Number: 159 of 275 with model GLM for Validation 3

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:445: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

159 - GLM with avg smape 3.87:
Model Number: 160 of 275 with model GLM for Validation 3
160 - GLM with avg smape 3.87:
Model Number: 161 of 275 with model GLM for Validation 3
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 161 in generation 0: GLM
Model Number: 162 of 275 with model GLM for Validation 3
162 - GLM with avg smape 3.87:
Model Number: 163 of 275 with model GLM for Validation 3

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1402: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:445: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1402: RuntimeWarning:

divide by zero encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1402: RuntimeWarning:

divide by zero encountered in divide

163 - GLM with avg smape 3.87:
Model Number: 164 of 275 with model ETS for Validation 3
164 - ETS with avg smape 3.87:
Model Number: 165 of 275 with model GLM for Validation 3
165 - GLM with avg smape 3.87:
Model Number: 166 of 275 with model DatepartRegression for Validation 3
166 - DatepartRegression with avg smape 3.94:
Model Number: 167 of 275 with model DatepartRegression for Validation 3

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

167 - DatepartRegression with avg smape 3.87:
Model Number: 168 of 275 with model ETS for Validation 3
168 - ETS with avg smape 3.87:
Model Number: 169 of 275 with model ETS for Validation 3
169 - ETS with avg smape 3.89:
Model Number: 170 of 275 with model ETS for Validation 3
170 - ETS with avg smape 3.89:
Model Number: 171 of 275 with model GLM for Validation 3
171 - GLM with avg smape 3.87:
Model Number: 172 of 275 with model ETS for Validation 3

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:198: RuntimeWarning:

overflow encountered in exp

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

172 - ETS with avg smape 3.87:
Model Number: 173 of 275 with model BasicLinearModel for Validation 3
173 - BasicLinearModel with avg smape 3.74:
Model Number: 174 of 275 with model SectionalMotif for Validation 3
174 - SectionalMotif with avg smape 5.94:
Model Number: 175 of 275 with model FBProphet for Validation 3
175 - FBProphet with avg smape 5.2:
Model Number: 176 of 275 with model FBProphet for Validation 3
176 - FBProphet with avg smape 5.19:
Model Number: 177 of 275 with model RRVAR for Validation 3
177 - RRVAR with avg smape 3.85:
Model Number: 178 of 275 with model RRVAR for Validation 3
178 - RRVAR with avg smape 3.85:
Model Number: 179 of 275 with model FBProphet for Validation 3
179 - FBProphet with avg smape 5.36:
Model Number: 180 of 275 with model LastValueNaive for Validation 3
180 - LastValueNaive with avg smape 5.74:
Model Number: 181 of 275 with model GLM for Validation 3
Template Eval Error: ValueError('NaN, inf or invalid value detected in weights, estimation infeasible.') in model 181 in generation 0: GLM
Model Number: 182 of 275 with model UnivariateMotif for Validation 3
182 - UnivariateMotif with avg smape 3.65:
Model Number: 183 of 275 with model GLM for Validation 3

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:308: DomainWarning:

The InversePower link function does not respect the domain of the Gamma family.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

overflow encountered in square

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/links.py:325: RuntimeWarning:

divide by zero encountered in power

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:775: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:898: RuntimeWarning:

invalid value encountered in divide

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:143: RuntimeWarning:

invalid value encountered in multiply

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/generalized_linear_model.py:1328: RuntimeWarning:

invalid value encountered in multiply

183 - GLM with avg smape 3.87:
Model Number: 184 of 275 with model GLM for Validation 3
184 - GLM with avg smape 3.87:
Model Number: 185 of 275 with model GLM for Validation 3
185 - GLM with avg smape 3.87:
Model Number: 186 of 275 with model GLM for Validation 3

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

/usr/local/lib/python3.12/dist-packages/statsmodels/genmod/families/family.py:1367: ValueWarning:

Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.

186 - GLM with avg smape 3.87:
Model Number: 187 of 275 with model LastValueNaive for Validation 3
187 - LastValueNaive with avg smape 5.34:
Model Number: 188 of 275 with model LastValueNaive for Validation 3
188 - LastValueNaive with avg smape 5.34:
Model Number: 189 of 275 with model LastValueNaive for Validation 3
189 - LastValueNaive with avg smape 5.34:
Model Number: 190 of 275 with model LastValueNaive for Validation 3
190 - LastValueNaive with avg smape 5.34:
Model Number: 191 of 275 with model LastValueNaive for Validation 3
191 - LastValueNaive with avg smape 5.34:
Model Number: 192 of 275 with model LastValueNaive for Validation 3
192 - LastValueNaive with avg smape 5.34:
Model Number: 193 of 275 with model LastValueNaive for Validation 3
193 - LastValueNaive with avg smape 3.77:
Model Number: 194 of 275 with model LastValueNaive for Validation 3
194 - LastValueNaive with avg smape 4.93:
Model Number: 195 of 275 with model LastValueNaive for Validation 3
195 - LastValueNaive with avg smape 4.93:
Model Number: 196 of 275 with model LastValueNaive for Validation 3
196 - LastValueNaive with avg smape 4.93:
Model Number: 197 of 275 with model LastValueNaive for Validation 3
197 - LastValueNaive with avg smape 4.93:
Model Number: 198 of 275 with model LastValueNaive for Validation 3
198 - LastValueNaive with avg smape 4.93:
Model Number: 199 of 275 with model LastValueNaive for Validation 3
199 - LastValueNaive with avg smape 4.91:
Model Number: 200 of 275 with model SectionalMotif for Validation 3
200 - SectionalMotif with avg smape 5.59:
Model Number: 201 of 275 with model SectionalMotif for Validation 3
201 - SectionalMotif with avg smape 8.01:
Model Number: 202 of 275 with model SectionalMotif for Validation 3
202 - SectionalMotif with avg smape 3.45:
Model Number: 203 of 275 with model UnivariateMotif for Validation 3
203 - UnivariateMotif with avg smape 3.65:
Model Number: 204 of 275 with model RRVAR for Validation 3
204 - RRVAR with avg smape 5.62:
Model Number: 205 of 275 with model UnivariateMotif for Validation 3
205 - UnivariateMotif with avg smape 4.77:
Model Number: 206 of 275 with model UnivariateMotif for Validation 3
206 - UnivariateMotif with avg smape 13.7:
Model Number: 207 of 275 with model UnivariateMotif for Validation 3
207 - UnivariateMotif with avg smape 5.05:
Model Number: 208 of 275 with model UnivariateMotif for Validation 3
208 - UnivariateMotif with avg smape 6.78:
Model Number: 209 of 275 with model MetricMotif for Validation 3
209 - MetricMotif with avg smape 3.69:
Model Number: 210 of 275 with model UnivariateMotif for Validation 3
210 - UnivariateMotif with avg smape 6.8:
Model Number: 211 of 275 with model MetricMotif for Validation 3
211 - MetricMotif with avg smape 6.24:
Model Number: 212 of 275 with model SectionalMotif for Validation 3
212 - SectionalMotif with avg smape 3.86:
Model Number: 213 of 275 with model SectionalMotif for Validation 3
213 - SectionalMotif with avg smape 3.64:
Model Number: 214 of 275 with model ConstantNaive for Validation 3
214 - ConstantNaive with avg smape 3.93:
Model Number: 215 of 275 with model UnivariateMotif for Validation 3
215 - UnivariateMotif with avg smape 4.07:
Model Number: 216 of 275 with model UnivariateMotif for Validation 3
216 - UnivariateMotif with avg smape 4.23:
Model Number: 217 of 275 with model MetricMotif for Validation 3
217 - MetricMotif with avg smape 5.07:
Model Number: 218 of 275 with model MetricMotif for Validation 3
218 - MetricMotif with avg smape 3.76:
Model Number: 219 of 275 with model SectionalMotif for Validation 3
219 - SectionalMotif with avg smape 5.14:
Model Number: 220 of 275 with model SectionalMotif for Validation 3
220 - SectionalMotif with avg smape 3.72:
Model Number: 221 of 275 with model SectionalMotif for Validation 3
221 - SectionalMotif with avg smape 4.34:
Model Number: 222 of 275 with model ConstantNaive for Validation 3
222 - ConstantNaive with avg smape 3.87:
Model Number: 223 of 275 with model MetricMotif for Validation 3
223 - MetricMotif with avg smape 5.76:
Model Number: 224 of 275 with model MetricMotif for Validation 3
224 - MetricMotif with avg smape 3.57:
Model Number: 225 of 275 with model SectionalMotif for Validation 3
225 - SectionalMotif with avg smape 9.81:
Model Number: 226 of 275 with model UnivariateMotif for Validation 3
226 - UnivariateMotif with avg smape 5.21:
Model Number: 227 of 275 with model MetricMotif for Validation 3
227 - MetricMotif with avg smape 5.95:
Model Number: 228 of 275 with model SectionalMotif for Validation 3
📈 228 - SectionalMotif with avg smape 2.17:
Model Number: 229 of 275 with model ConstantNaive for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

229 - ConstantNaive with avg smape 5.13:
Model Number: 230 of 275 with model ConstantNaive for Validation 3
230 - ConstantNaive with avg smape 5.13:
Model Number: 231 of 275 with model MetricMotif for Validation 3
231 - MetricMotif with avg smape 4.98:
Model Number: 232 of 275 with model SectionalMotif for Validation 3
232 - SectionalMotif with avg smape 7.71:
Model Number: 233 of 275 with model SectionalMotif for Validation 3
233 - SectionalMotif with avg smape 3.54:
Model Number: 234 of 275 with model LastValueNaive for Validation 3
234 - LastValueNaive with avg smape 9.4:
Model Number: 235 of 275 with model SectionalMotif for Validation 3
235 - SectionalMotif with avg smape 3.57:
Model Number: 236 of 275 with model MetricMotif for Validation 3
236 - MetricMotif with avg smape 6.07:
Model Number: 237 of 275 with model SectionalMotif for Validation 3
237 - SectionalMotif with avg smape 3.33:
Model Number: 238 of 275 with model UnivariateMotif for Validation 3
238 - UnivariateMotif with avg smape 4.72:
Model Number: 239 of 275 with model UnivariateMotif for Validation 3
239 - UnivariateMotif with avg smape 5.25:
Model Number: 240 of 275 with model ConstantNaive for Validation 3
240 - ConstantNaive with avg smape 10.42:
Model Number: 241 of 275 with model MetricMotif for Validation 3
241 - MetricMotif with avg smape 36.89:
Model Number: 242 of 275 with model UnivariateMotif for Validation 3
242 - UnivariateMotif with avg smape 5.98:
Model Number: 243 of 275 with model UnivariateMotif for Validation 3
243 - UnivariateMotif with avg smape 2.73:
Model Number: 244 of 275 with model MetricMotif for Validation 3
244 - MetricMotif with avg smape 3.23:
Model Number: 245 of 275 with model MetricMotif for Validation 3
245 - MetricMotif with avg smape 28.42:
Model Number: 246 of 275 with model ConstantNaive for Validation 3
246 - ConstantNaive with avg smape 10.85:
Model Number: 247 of 275 with model ConstantNaive for Validation 3
247 - ConstantNaive with avg smape 9.21:
Model Number: 248 of 275 with model MetricMotif for Validation 3
248 - MetricMotif with avg smape 51.96:
Model Number: 249 of 275 with model ConstantNaive for Validation 3
249 - ConstantNaive with avg smape 10.68:
Model Number: 250 of 275 with model ConstantNaive for Validation 3
250 - ConstantNaive with avg smape 10.55:
Model Number: 251 of 275 with model ConstantNaive for Validation 3
251 - ConstantNaive with avg smape 9.4:
Model Number: 252 of 275 with model MetricMotif for Validation 3
252 - MetricMotif with avg smape 9.4:
Model Number: 253 of 275 with model ConstantNaive for Validation 3
253 - ConstantNaive with avg smape 9.4:
Model Number: 254 of 275 with model ConstantNaive for Validation 3
254 - ConstantNaive with avg smape 9.35:
Model Number: 255 of 275 with model VAR for Validation 3
255 - VAR with avg smape 6.47:
Model Number: 256 of 275 with model MetricMotif for Validation 3
256 - MetricMotif with avg smape 5.16:
Model Number: 257 of 275 with model ConstantNaive for Validation 3
257 - ConstantNaive with avg smape 9.25:
Model Number: 258 of 275 with model ConstantNaive for Validation 3
258 - ConstantNaive with avg smape 9.23:
Model Number: 259 of 275 with model ConstantNaive for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

259 - ConstantNaive with avg smape 2.82:
Model Number: 260 of 275 with model RRVAR for Validation 3
260 - RRVAR with avg smape 10.99:
Model Number: 261 of 275 with model RRVAR for Validation 3
261 - RRVAR with avg smape 11.2:
Model Number: 262 of 275 with model WindowRegression for Validation 3
262 - WindowRegression with avg smape 12.59:
Model Number: 263 of 275 with model RRVAR for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

263 - RRVAR with avg smape 7.82:
Model Number: 264 of 275 with model RRVAR for Validation 3
264 - RRVAR with avg smape 12.33:
Model Number: 265 of 275 with model RRVAR for Validation 3
265 - RRVAR with avg smape 10.78:
Model Number: 266 of 275 with model RRVAR for Validation 3
266 - RRVAR with avg smape 9.25:
Model Number: 267 of 275 with model RRVAR for Validation 3
267 - RRVAR with avg smape 7.9:
Model Number: 268 of 275 with model RRVAR for Validation 3
268 - RRVAR with avg smape 7.82:
Model Number: 269 of 275 with model RRVAR for Validation 3
269 - RRVAR with avg smape 14.55:
Model Number: 270 of 275 with model WindowRegression for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

270 - WindowRegression with avg smape 30.13:
Model Number: 271 of 275 with model RRVAR for Validation 3
271 - RRVAR with avg smape 21.99:
Model Number: 272 of 275 with model WindowRegression for Validation 3
272 - WindowRegression with avg smape 26.93:
Model Number: 273 of 275 with model RRVAR for Validation 3

/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning:

Ill-conditioned matrix (rcond=1.64564e-25): result may not be accurate.

273 - RRVAR with avg smape 17.83:
Model Number: 274 of 275 with model WindowRegression for Validation 3
Epoch 1/10

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 2938.3110
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 934.4591
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 556.2020
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 219.8636
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 186.4562
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 79.9868
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 63.9268
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 42.0994
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 14.1975
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 15.5129
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
274 - WindowRegression with avg smape 58.31:
Model Number: 275 of 275 with model RRVAR for Validation 3
275 - RRVAR with avg smape 199.21:

/usr/local/lib/python3.12/dist-packages/autots/evaluator/auto_model.py:3068: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Model Number: 2705 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 2710 in generation 27: Ensemble
Model Number: 2711 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 2716 in generation 27: Ensemble
Model Number: 2717 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 2722 in generation 27: Ensemble
Model Number: 2723 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 2728 in generation 27: Ensemble
Model Number: 2729 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 2734 in generation 27: Ensemble
Model Number: 2735 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 2740 in generation 27: Ensemble
Model Number: 2741 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 2746 in generation 27: Ensemble
Model Number: 2747 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 2752 in generation 27: Ensemble
Model Number: 2753 with model Ensemble in generation 27 of Ensembles

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 2758 in generation 27: Ensemble
Validation Round: 1
Model Number: 1 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

📈 1 - Ensemble with avg smape 4.49:
📈 2 - Ensemble with avg smape 4.48:
3 - Ensemble with avg smape 4.88:
4 - Ensemble with avg smape 5.08:
5 - Ensemble with avg smape 6.33:
6 - Ensemble with avg smape 20.06:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 6 in generation 0: Ensemble
Model Number: 7 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

📈 7 - Ensemble with avg smape 4.0:
📈 8 - Ensemble with avg smape 3.99:
9 - Ensemble with avg smape 4.3:
10 - Ensemble with avg smape 4.75:
11 - Ensemble with avg smape 6.26:
12 - Ensemble with avg smape 20.06:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 12 in generation 0: Ensemble
Model Number: 13 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

13 - Ensemble with avg smape 4.7:
14 - Ensemble with avg smape 4.7:
15 - Ensemble with avg smape 4.99:
16 - Ensemble with avg smape 5.19:
17 - Ensemble with avg smape 6.33:
18 - Ensemble with avg smape 20.06:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 18 in generation 0: Ensemble
Model Number: 19 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

19 - Ensemble with avg smape 4.37:
20 - Ensemble with avg smape 4.37:
21 - Ensemble with avg smape 4.8:
22 - Ensemble with avg smape 5.08:
23 - Ensemble with avg smape 6.33:
24 - Ensemble with avg smape 20.06:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 24 in generation 0: Ensemble
Model Number: 25 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

25 - Ensemble with avg smape 4.74:
26 - Ensemble with avg smape 4.75:
27 - Ensemble with avg smape 4.93:
28 - Ensemble with avg smape 5.31:
29 - Ensemble with avg smape 6.34:
30 - Ensemble with avg smape 20.06:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 30 in generation 0: Ensemble
Model Number: 31 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

31 - Ensemble with avg smape 5.18:
32 - Ensemble with avg smape 5.18:
33 - Ensemble with avg smape 5.81:
34 - Ensemble with avg smape 5.53:
35 - Ensemble with avg smape 6.41:
36 - Ensemble with avg smape 20.06:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 36 in generation 0: Ensemble
Model Number: 37 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

37 - Ensemble with avg smape 4.8:
38 - Ensemble with avg smape 4.8:
39 - Ensemble with avg smape 5.22:
40 - Ensemble with avg smape 5.35:
41 - Ensemble with avg smape 6.36:
42 - Ensemble with avg smape 20.06:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 42 in generation 0: Ensemble
Model Number: 43 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

43 - Ensemble with avg smape 4.73:
44 - Ensemble with avg smape 4.73:
45 - Ensemble with avg smape 5.26:
46 - Ensemble with avg smape 5.26:
47 - Ensemble with avg smape 6.37:
48 - Ensemble with avg smape 20.06:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 48 in generation 0: Ensemble
Model Number: 49 of 9 with model Ensemble for Validation 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

49 - Ensemble with avg smape 4.56:
50 - Ensemble with avg smape 4.55:
51 - Ensemble with avg smape 5.1:
52 - Ensemble with avg smape 5.15:
53 - Ensemble with avg smape 6.35:
54 - Ensemble with avg smape 20.06:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 54 in generation 0: Ensemble
Validation Round: 2
Model Number: 1 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

📈 1 - Ensemble with avg smape 1.96:
📈 2 - Ensemble with avg smape 1.93:
3 - Ensemble with avg smape 2.63:
📈 4 - Ensemble with avg smape 1.87:
5 - Ensemble with avg smape 3.71:
6 - Ensemble with avg smape 11.8:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 6 in generation 0: Ensemble
Model Number: 7 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

📈 7 - Ensemble with avg smape 1.66:
📈 8 - Ensemble with avg smape 1.64:
9 - Ensemble with avg smape 2.96:
📈 10 - Ensemble with avg smape 1.6:
11 - Ensemble with avg smape 3.72:
12 - Ensemble with avg smape 11.8:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 12 in generation 0: Ensemble
Model Number: 13 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

13 - Ensemble with avg smape 2.21:
14 - Ensemble with avg smape 2.19:
15 - Ensemble with avg smape 2.3:
16 - Ensemble with avg smape 2.21:
17 - Ensemble with avg smape 3.7:
18 - Ensemble with avg smape 11.8:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 18 in generation 0: Ensemble
Model Number: 19 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

19 - Ensemble with avg smape 1.74:
20 - Ensemble with avg smape 1.75:
21 - Ensemble with avg smape 2.73:
22 - Ensemble with avg smape 1.64:
23 - Ensemble with avg smape 3.71:
24 - Ensemble with avg smape 11.8:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 24 in generation 0: Ensemble
Model Number: 25 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

25 - Ensemble with avg smape 1.63:
26 - Ensemble with avg smape 1.63:
27 - Ensemble with avg smape 2.84:
📈 28 - Ensemble with avg smape 1.59:
29 - Ensemble with avg smape 3.71:
30 - Ensemble with avg smape 11.8:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 30 in generation 0: Ensemble
Model Number: 31 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

31 - Ensemble with avg smape 2.02:
32 - Ensemble with avg smape 2.0:
33 - Ensemble with avg smape 2.54:
34 - Ensemble with avg smape 1.95:
35 - Ensemble with avg smape 3.7:
36 - Ensemble with avg smape 11.8:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 36 in generation 0: Ensemble
Model Number: 37 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

37 - Ensemble with avg smape 1.73:
38 - Ensemble with avg smape 1.7:
39 - Ensemble with avg smape 3.27:
📈 40 - Ensemble with avg smape 1.58:
41 - Ensemble with avg smape 3.73:
42 - Ensemble with avg smape 11.8:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 42 in generation 0: Ensemble
Model Number: 43 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

📈 43 - Ensemble with avg smape 1.55:
📈 44 - Ensemble with avg smape 1.52:
45 - Ensemble with avg smape 3.51:
📈 46 - Ensemble with avg smape 1.48:
47 - Ensemble with avg smape 3.73:
48 - Ensemble with avg smape 11.8:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 48 in generation 0: Ensemble
Model Number: 49 of 9 with model Ensemble for Validation 2

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

49 - Ensemble with avg smape 1.81:
50 - Ensemble with avg smape 1.78:
51 - Ensemble with avg smape 2.99:
52 - Ensemble with avg smape 1.74:
53 - Ensemble with avg smape 3.72:
54 - Ensemble with avg smape 11.8:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 54 in generation 0: Ensemble
Validation Round: 3
Model Number: 1 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

📈 1 - Ensemble with avg smape 3.47:
2 - Ensemble with avg smape 3.53:
3 - Ensemble with avg smape 6.51:
4 - Ensemble with avg smape 4.87:
5 - Ensemble with avg smape 12.96:
6 - Ensemble with avg smape 9.67:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 6 in generation 0: Ensemble
Model Number: 7 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

7 - Ensemble with avg smape 3.74:
8 - Ensemble with avg smape 3.77:
9 - Ensemble with avg smape 6.52:
10 - Ensemble with avg smape 5.15:
11 - Ensemble with avg smape 12.96:
12 - Ensemble with avg smape 9.67:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 12 in generation 0: Ensemble
Model Number: 13 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

13 - Ensemble with avg smape 3.49:
14 - Ensemble with avg smape 3.54:
15 - Ensemble with avg smape 6.64:
16 - Ensemble with avg smape 4.88:
17 - Ensemble with avg smape 12.96:
18 - Ensemble with avg smape 9.67:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 18 in generation 0: Ensemble
Model Number: 19 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

19 - Ensemble with avg smape 3.96:
20 - Ensemble with avg smape 3.99:
21 - Ensemble with avg smape 6.54:
22 - Ensemble with avg smape 5.28:
23 - Ensemble with avg smape 12.96:
24 - Ensemble with avg smape 9.67:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 24 in generation 0: Ensemble
Model Number: 25 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

25 - Ensemble with avg smape 3.84:
26 - Ensemble with avg smape 3.89:
27 - Ensemble with avg smape 6.73:
28 - Ensemble with avg smape 5.18:
29 - Ensemble with avg smape 12.95:
30 - Ensemble with avg smape 9.67:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 30 in generation 0: Ensemble
Model Number: 31 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

📈 31 - Ensemble with avg smape 3.29:
32 - Ensemble with avg smape 3.35:
33 - Ensemble with avg smape 7.46:
34 - Ensemble with avg smape 4.54:
35 - Ensemble with avg smape 12.91:
36 - Ensemble with avg smape 9.67:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 36 in generation 0: Ensemble
Model Number: 37 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

📈 37 - Ensemble with avg smape 3.2:
38 - Ensemble with avg smape 3.28:
39 - Ensemble with avg smape 6.66:
40 - Ensemble with avg smape 4.62:
41 - Ensemble with avg smape 12.95:
42 - Ensemble with avg smape 9.67:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 42 in generation 0: Ensemble
Model Number: 43 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

📈 43 - Ensemble with avg smape 3.15:
44 - Ensemble with avg smape 3.2:
45 - Ensemble with avg smape 7.26:
46 - Ensemble with avg smape 4.47:
47 - Ensemble with avg smape 12.92:
48 - Ensemble with avg smape 9.67:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 48 in generation 0: Ensemble
Model Number: 49 of 9 with model Ensemble for Validation 3

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names

📈 49 - Ensemble with avg smape 2.9:
50 - Ensemble with avg smape 2.94:
51 - Ensemble with avg smape 7.21:
52 - Ensemble with avg smape 4.22:
53 - Ensemble with avg smape 12.92:
54 - Ensemble with avg smape 9.67:
Template Eval Error: Exception("Transformer HistoricValues failed on fit from params fake_date {'0': {'rows': 1, 'lag': 1, 'method': 'additive', 'strength': 1.0, 'first_value_only': False, 'threshold': 10, 'threshold_method': 'mean'}, '1': {'window': 28}} with error KeyError('2')") in model 54 in generation 0: Ensemble

/usr/local/lib/python3.12/dist-packages/autots/evaluator/auto_model.py:3068: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/usr/local/lib/python3.12/dist-packages/autots/evaluator/auto_model.py:3068: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

                    Close
2025-08-29  112544.804688
2025-08-30  114709.240806
2025-08-31  115235.656523
2025-09-01  114832.404677
2025-09-02  114520.507604
2025-09-03  114775.254185
2025-09-04  114573.485168
2025-09-05  115061.752136
2025-09-06  115026.951863
2025-09-07  115242.992164
2025-09-08  115830.145078
2025-09-09  115971.649661
2025-09-10  116226.453999
2025-09-11  116038.050484
2025-09-12  116543.605877
2025-09-13  116719.370234
2025-09-14  117065.262975
2025-09-15  117707.525080
2025-09-16  117157.754849
2025-09-17  117049.780519
2025-09-18  117054.216725
2025-09-19  117405.055636
2025-09-20  117189.801269
2025-09-21  116856.140003
2025-09-22  116870.429043
2025-09-23  116966.695569
2025-09-24  117087.301432
2025-09-25  117057.979268
2025-09-26  116986.787349
2025-09-27  116996.901673

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but StandardScaler was fitted without feature names